del ..\test.o3\*.*
del ..\text.o3\*.*
..\masmx a1 ..\test.o3\a2 -z > ..\text.o3\a2.txt
..\masmx a1 ..\test.o3\a3 -c > ..\text.o3\a3.txt
..\masmx a1 ..\test.o3\a4 -zc > ..\text.o3\a4.txt
..\masmx 1101 -lnoy ..\test.o3\1101 > ..\text.o3\1101.txt
..\masmx 1103 -lnoy ..\test.o3\1103 > ..\text.o3\1103.txt
..\masmx 14 -lnoy ..\test.o3\14 > ..\text.o3\14.txt
..\masmx 16lib24 -lnoy ..\test.o3\16lib24 > ..\text.o3\16lib24.txt
..\masmx 1st -lnoy ..\test.o3\1st > ..\text.o3\1st.txt
..\masmx 2468 -lnoy ..\test.o3\2468 > ..\text.o3\2468.txt
..\masmx 2manif -lnoy ..\test.o3\2manif > ..\text.o3\2manif.txt
..\masmx 2nd -lnoy ..\test.o3\2nd > ..\text.o3\2nd.txt
..\masmx 3byte -lnoy ..\test.o3\3byte > ..\text.o3\3byte.txt
..\masmx 3rd -lnoy ..\test.o3\3rd > ..\text.o3\3rd.txt
..\masmx @ -lnoy ..\test.o3\@ > ..\text.o3\@.txt
..\masmx @1 -lnoy ..\test.o3\@1 > ..\text.o3\@1.txt
..\masmx a1 -lnoy ..\test.o3\a1 > ..\text.o3\a1.txt
..\masmx abit -lnoy ..\test.o3\abit > ..\text.o3\abit.txt
..\masmx about -lnoy ..\test.o3\about > ..\text.o3\about.txt
..\masmx addo -lnoy ..\test.o3\addo > ..\text.o3\addo.txt
..\masmx addu -lnoy ..\test.o3\addu > ..\text.o3\addu.txt
..\masmx addz -lnoy ..\test.o3\addz > ..\text.o3\addz.txt
..\masmx adsomor1 -lnoy ..\test.o3\adsomor1 > ..\text.o3\adsomor1.txt
..\masmx adsomor2 -lnoy ..\test.o3\adsomor2 > ..\text.o3\adsomor2.txt
..\masmx adsomor3 -lnoy ..\test.o3\adsomor3 > ..\text.o3\adsomor3.txt
..\masmx adsomor4 -lnoy ..\test.o3\adsomor4 > ..\text.o3\adsomor4.txt
..\masmx afile -lnoy ..\test.o3\afile > ..\text.o3\afile.txt
..\masmx aglimpse -lnoy ..\test.o3\aglimpse > ..\text.o3\aglimpse.txt
..\masmx agranoy -lnoy ..\test.o3\agranoy > ..\text.o3\agranoy.txt
..\masmx ajoko -lnoy ..\test.o3\ajoko > ..\text.o3\ajoko.txt
..\masmx algebra -lnoy ..\test.o3\algebra > ..\text.o3\algebra.txt
..\masmx align -lnoy ..\test.o3\align > ..\text.o3\align.txt
..\masmx allyoobl -lnoy ..\test.o3\allyoobl > ..\text.o3\allyoobl.txt
..\masmx alyat -lnoy ..\test.o3\alyat > ..\text.o3\alyat.txt
..\masmx anew -lnoy ..\test.o3\anew > ..\text.o3\anew.txt
..\masmx another -lnoy ..\test.o3\another > ..\text.o3\another.txt
..\masmx aon -lnoy ..\test.o3\aon > ..\text.o3\aon.txt
..\masmx app -lnoy ..\test.o3\app > ..\text.o3\app.txt
..\masmx app1 -lnoy ..\test.o3\app1 > ..\text.o3\app1.txt
..\masmx app2 -lnoy ..\test.o3\app2 > ..\text.o3\app2.txt
..\masmx app3 -lnoy ..\test.o3\app3 > ..\text.o3\app3.txt
..\masmx app4 -lnoy ..\test.o3\app4 > ..\text.o3\app4.txt
..\masmx app7 -lnoy ..\test.o3\app7 > ..\text.o3\app7.txt
..\masmx appoint -lnoy ..\test.o3\appoint > ..\text.o3\appoint.txt
..\masmx approx -lnoy ..\test.o3\approx > ..\text.o3\approx.txt
..\masmx aqt -lnoy ..\test.o3\aqt > ..\text.o3\aqt.txt
..\masmx arm -lnoy ..\test.o3\arm > ..\text.o3\arm.txt
..\masmx array -lnoy ..\test.o3\array > ..\text.o3\array.txt
..\masmx arrayok -lnoy ..\test.o3\arrayok > ..\text.o3\arrayok.txt
..\masmx asample -lnoy ..\test.o3\asample > ..\text.o3\asample.txt
..\masmx ast -lnoy ..\test.o3\ast > ..\text.o3\ast.txt
..\masmx atest -lnoy ..\test.o3\atest > ..\text.o3\atest.txt
..\masmx attempt -lnoy ..\test.o3\attempt > ..\text.o3\attempt.txt
..\masmx avast -lnoy ..\test.o3\avast > ..\text.o3\avast.txt
..\masmx avastok -lnoy ..\test.o3\avastok > ..\text.o3\avastok.txt
..\masmx avenu -lnoy ..\test.o3\avenu > ..\text.o3\avenu.txt
..\masmx awail -lnoy ..\test.o3\awail > ..\text.o3\awail.txt
..\masmx awain -lnoy ..\test.o3\awain > ..\text.o3\awain.txt
..\masmx away -lnoy ..\test.o3\away > ..\text.o3\away.txt
..\masmx awkward -lnoy ..\test.o3\awkward > ..\text.o3\awkward.txt
..\masmx azuli -lnoy ..\test.o3\azuli > ..\text.o3\azuli.txt
..\masmx b -lnoy ..\test.o3\b > ..\text.o3\b.txt
..\masmx badly -lnoy ..\test.o3\badly > ..\text.o3\badly.txt
..\masmx balance -lnoy ..\test.o3\balance > ..\text.o3\balance.txt
..\masmx banks -lnoy ..\test.o3\banks > ..\text.o3\banks.txt
..\masmx banks2 -lnoy ..\test.o3\banks2 > ..\text.o3\banks2.txt
..\masmx basal1 -lnoy ..\test.o3\basal1 > ..\text.o3\basal1.txt
..\masmx basalall -lnoy ..\test.o3\basalall > ..\text.o3\basalall.txt
..\masmx basalone -lnoy ..\test.o3\basalone > ..\text.o3\basalone.txt
..\masmx basalthr -lnoy ..\test.o3\basalthr > ..\text.o3\basalthr.txt
..\masmx basaltwo -lnoy ..\test.o3\basaltwo > ..\text.o3\basaltwo.txt
..\masmx basis -lnoy ..\test.o3\basis > ..\text.o3\basis.txt
..\masmx bb -lnoy ..\test.o3\bb > ..\text.o3\bb.txt
..\masmx bdw -lnoy ..\test.o3\bdw > ..\text.o3\bdw.txt
..\masmx bequf -lnoy ..\test.o3\bequf > ..\text.o3\bequf.txt
..\masmx big -lnoy ..\test.o3\big > ..\text.o3\big.txt
..\masmx big48 -lnoy ..\test.o3\big48 > ..\text.o3\big48.txt
..\masmx bitsof -lnoy ..\test.o3\bitsof > ..\text.o3\bitsof.txt
..\masmx blanks -lnoy ..\test.o3\blanks > ..\text.o3\blanks.txt
..\masmx blanquo -lnoy ..\test.o3\blanquo > ..\text.o3\blanquo.txt
..\masmx bogle -lnoy ..\test.o3\bogle > ..\text.o3\bogle.txt
..\masmx bonkers -lnoy ..\test.o3\bonkers > ..\text.o3\bonkers.txt
..\masmx bounded -lnoy ..\test.o3\bounded > ..\text.o3\bounded.txt
..\masmx boxy -lnoy ..\test.o3\boxy > ..\text.o3\boxy.txt
..\masmx bqt -lnoy ..\test.o3\bqt > ..\text.o3\bqt.txt
..\masmx brickie -lnoy ..\test.o3\brickie > ..\text.o3\brickie.txt
..\masmx brozzing -lnoy ..\test.o3\brozzing > ..\text.o3\brozzing.txt
..\masmx btest -lnoy ..\test.o3\btest > ..\text.o3\btest.txt
..\masmx buy_sell -lnoy ..\test.o3\buy_sell > ..\text.o3\buy_sell.txt
..\masmx bway -lnoy ..\test.o3\bway > ..\text.o3\bway.txt
..\masmx cancan -lnoy ..\test.o3\cancan > ..\text.o3\cancan.txt
..\masmx capsule -lnoy ..\test.o3\capsule > ..\text.o3\capsule.txt
..\masmx carryon -lnoy ..\test.o3\carryon > ..\text.o3\carryon.txt
..\masmx case -lnoy ..\test.o3\case > ..\text.o3\case.txt
..\masmx cases -lnoy ..\test.o3\cases > ..\text.o3\cases.txt
..\masmx cc -lnoy ..\test.o3\cc > ..\text.o3\cc.txt
..\masmx cdml -lnoy ..\test.o3\cdml > ..\text.o3\cdml.txt
..\masmx cheese -lnoy ..\test.o3\cheese > ..\text.o3\cheese.txt
..\masmx code -lnoy ..\test.o3\code > ..\text.o3\code.txt
..\masmx commas -lnoy ..\test.o3\commas > ..\text.o3\commas.txt
..\masmx comment -lnoy ..\test.o3\comment > ..\text.o3\comment.txt
..\masmx comment1 -lnoy ..\test.o3\comment1 > ..\text.o3\comment1.txt
..\masmx complex -lnoy ..\test.o3\complex > ..\text.o3\complex.txt
..\masmx compo -lnoy ..\test.o3\compo > ..\text.o3\compo.txt
..\masmx compose -lnoy ..\test.o3\compose > ..\text.o3\compose.txt
..\masmx constanz -lnoy ..\test.o3\constanz > ..\text.o3\constanz.txt
..\masmx context -lnoy ..\test.o3\context > ..\text.o3\context.txt
..\masmx continu -lnoy ..\test.o3\continu > ..\text.o3\continu.txt
..\masmx contrary -lnoy ..\test.o3\contrary > ..\text.o3\contrary.txt
..\masmx controb2 -lnoy ..\test.o3\controb2 > ..\text.o3\controb2.txt
..\masmx control1 -lnoy ..\test.o3\control1 > ..\text.o3\control1.txt
..\masmx control2 -lnoy ..\test.o3\control2 > ..\text.o3\control2.txt
..\masmx control3 -lnoy ..\test.o3\control3 > ..\text.o3\control3.txt
..\masmx control4 -lnoy ..\test.o3\control4 > ..\text.o3\control4.txt
..\masmx cqt -lnoy ..\test.o3\cqt > ..\text.o3\cqt.txt
..\masmx crabble -lnoy ..\test.o3\crabble > ..\text.o3\crabble.txt
..\masmx ctest -lnoy ..\test.o3\ctest > ..\text.o3\ctest.txt
..\masmx d -lnoy ..\test.o3\d > ..\text.o3\d.txt
..\masmx dd -lnoy ..\test.o3\dd > ..\text.o3\dd.txt
..\masmx ddd -lnoy ..\test.o3\ddd > ..\text.o3\ddd.txt
..\masmx dde -lnoy ..\test.o3\dde > ..\text.o3\dde.txt
..\masmx decode -lnoy ..\test.o3\decode > ..\text.o3\decode.txt
..\masmx deep -lnoy ..\test.o3\deep > ..\text.o3\deep.txt
..\masmx deep_lit -lnoy ..\test.o3\deep_lit > ..\text.o3\deep_lit.txt
..\masmx demo1 -lnoy ..\test.o3\demo1 > ..\text.o3\demo1.txt
..\masmx demo2 -lnoy ..\test.o3\demo2 > ..\text.o3\demo2.txt
..\masmx demo3 -lnoy ..\test.o3\demo3 > ..\text.o3\demo3.txt
..\masmx detune -lnoy ..\test.o3\detune > ..\text.o3\detune.txt
..\masmx dfp -lnoy ..\test.o3\dfp > ..\text.o3\dfp.txt
..\masmx dfp16 -lnoy ..\test.o3\dfp16 > ..\text.o3\dfp16.txt
..\masmx diffi -lnoy ..\test.o3\diffi > ..\text.o3\diffi.txt
..\masmx dl -lnoy ..\test.o3\dl > ..\text.o3\dl.txt
..\masmx do -lnoy ..\test.o3\do > ..\text.o3\do.txt
..\masmx do1 -lnoy ..\test.o3\do1 > ..\text.o3\do1.txt
..\masmx do2 -lnoy ..\test.o3\do2 > ..\text.o3\do2.txt
..\masmx do3 -lnoy ..\test.o3\do3 > ..\text.o3\do3.txt
..\masmx do32 -lnoy ..\test.o3\do32 > ..\text.o3\do32.txt
..\masmx do4 -lnoy ..\test.o3\do4 > ..\text.o3\do4.txt
..\masmx dogma -lnoy ..\test.o3\dogma > ..\text.o3\dogma.txt
..\masmx dollar -lnoy ..\test.o3\dollar > ..\text.o3\dollar.txt
..\masmx dollar1 -lnoy ..\test.o3\dollar1 > ..\text.o3\dollar1.txt
..\masmx dormouse -lnoy ..\test.o3\dormouse > ..\text.o3\dormouse.txt
..\masmx dotable -lnoy ..\test.o3\dotable > ..\text.o3\dotable.txt
..\masmx drat -lnoy ..\test.o3\drat > ..\text.o3\drat.txt
..\masmx dudif -lnoy ..\test.o3\dudif > ..\text.o3\dudif.txt
..\masmx dumexa -lnoy ..\test.o3\dumexa > ..\text.o3\dumexa.txt
..\masmx dup -lnoy ..\test.o3\dup > ..\text.o3\dup.txt
..\masmx dx -lnoy ..\test.o3\dx > ..\text.o3\dx.txt
..\masmx edit -lnoy ..\test.o3\edit > ..\text.o3\edit.txt
..\masmx elboaze -lnoy ..\test.o3\elboaze > ..\text.o3\elboaze.txt
..\masmx elf -lnoy ..\test.o3\elf > ..\text.o3\elf.txt
..\masmx entrada -lnoy ..\test.o3\entrada > ..\text.o3\entrada.txt
..\masmx environ -lnoy ..\test.o3\environ > ..\text.o3\environ.txt
..\masmx eq -lnoy ..\test.o3\eq > ..\text.o3\eq.txt
..\masmx equf -lnoy ..\test.o3\equf > ..\text.o3\equf.txt
..\masmx equf32 -lnoy ..\test.o3\equf32 > ..\text.o3\equf32.txt
..\masmx expo -lnoy ..\test.o3\expo > ..\text.o3\expo.txt
..\masmx export -lnoy ..\test.o3\export > ..\text.o3\export.txt
..\masmx f -lnoy ..\test.o3\f > ..\text.o3\f.txt
..\masmx f2f -lnoy ..\test.o3\f2f > ..\text.o3\f2f.txt
..\masmx factor -lnoy ..\test.o3\factor > ..\text.o3\factor.txt
..\masmx fames -lnoy ..\test.o3\fames > ..\text.o3\fames.txt
..\masmx fatalp -lnoy ..\test.o3\fatalp > ..\text.o3\fatalp.txt
..\masmx feelup -lnoy ..\test.o3\feelup > ..\text.o3\feelup.txt
..\masmx fff -lnoy ..\test.o3\fff > ..\text.o3\fff.txt
..\masmx flags -lnoy ..\test.o3\flags > ..\text.o3\flags.txt
..\masmx forgot -lnoy ..\test.o3\forgot > ..\text.o3\forgot.txt
..\masmx forjoy -lnoy ..\test.o3\forjoy > ..\text.o3\forjoy.txt
..\masmx form -lnoy ..\test.o3\form > ..\text.o3\form.txt
..\masmx fp -lnoy ..\test.o3\fp > ..\text.o3\fp.txt
..\masmx fp32 -lnoy ..\test.o3\fp32 > ..\text.o3\fp32.txt
..\masmx fpsize -lnoy ..\test.o3\fpsize > ..\text.o3\fpsize.txt
..\masmx fptest -lnoy ..\test.o3\fptest > ..\text.o3\fptest.txt
..\masmx fptestu -lnoy ..\test.o3\fptestu > ..\text.o3\fptestu.txt
..\masmx fpx -lnoy ..\test.o3\fpx > ..\text.o3\fpx.txt
..\masmx fragment -lnoy ..\test.o3\fragment > ..\text.o3\fragment.txt
..\masmx frame2 -lnoy ..\test.o3\frame2 > ..\text.o3\frame2.txt
..\masmx fref -lnoy ..\test.o3\fref > ..\text.o3\fref.txt
..\masmx fruit -lnoy ..\test.o3\fruit > ..\text.o3\fruit.txt
..\masmx frung -lnoy ..\test.o3\frung > ..\text.o3\frung.txt
..\masmx fs -lnoy ..\test.o3\fs > ..\text.o3\fs.txt
..\masmx fs32 -lnoy ..\test.o3\fs32 > ..\text.o3\fs32.txt
..\masmx fs48 -lnoy ..\test.o3\fs48 > ..\text.o3\fs48.txt
..\masmx further -lnoy ..\test.o3\further > ..\text.o3\further.txt
..\masmx fx -lnoy ..\test.o3\fx > ..\text.o3\fx.txt
..\masmx fzero -lnoy ..\test.o3\fzero > ..\text.o3\fzero.txt
..\masmx gap -lnoy ..\test.o3\gap > ..\text.o3\gap.txt
..\masmx general -lnoy ..\test.o3\general > ..\text.o3\general.txt
..\masmx gfactor -lnoy ..\test.o3\gfactor > ..\text.o3\gfactor.txt
..\masmx gfar -lnoy ..\test.o3\gfar > ..\text.o3\gfar.txt
..\masmx gflo -lnoy ..\test.o3\gflo > ..\text.o3\gflo.txt
..\masmx gframe2 -lnoy ..\test.o3\gframe2 > ..\text.o3\gframe2.txt
..\masmx gfurther -lnoy ..\test.o3\gfurther > ..\text.o3\gfurther.txt
..\masmx goodbit -lnoy ..\test.o3\goodbit > ..\text.o3\goodbit.txt
..\masmx grade -lnoy ..\test.o3\grade > ..\text.o3\grade.txt
..\masmx gram -lnoy ..\test.o3\gram > ..\text.o3\gram.txt
..\masmx grig -lnoy ..\test.o3\grig > ..\text.o3\grig.txt
..\masmx grobags -lnoy ..\test.o3\grobags > ..\text.o3\grobags.txt
..\masmx gross -lnoy ..\test.o3\gross > ..\text.o3\gross.txt
..\masmx grum -lnoy ..\test.o3\grum > ..\text.o3\grum.txt
..\masmx gscale22 -lnoy ..\test.o3\gscale22 > ..\text.o3\gscale22.txt
..\masmx gscale23 -lnoy ..\test.o3\gscale23 > ..\text.o3\gscale23.txt
..\masmx gscale24 -lnoy ..\test.o3\gscale24 > ..\text.o3\gscale24.txt
..\masmx gsoso -lnoy ..\test.o3\gsoso > ..\text.o3\gsoso.txt
..\masmx gworser -lnoy ..\test.o3\gworser > ..\text.o3\gworser.txt
..\masmx gwyllmp -lnoy ..\test.o3\gwyllmp > ..\text.o3\gwyllmp.txt
..\masmx gzactor -lnoy ..\test.o3\gzactor > ..\text.o3\gzactor.txt
..\masmx haive -lnoy ..\test.o3\haive > ..\text.o3\haive.txt
..\masmx handfull -lnoy ..\test.o3\handfull > ..\text.o3\handfull.txt
..\masmx hangobar -lnoy ..\test.o3\hangobar > ..\text.o3\hangobar.txt
..\masmx hflo -lnoy ..\test.o3\hflo > ..\text.o3\hflo.txt
..\masmx high -lnoy ..\test.o3\high > ..\text.o3\high.txt
..\masmx hinge -lnoy ..\test.o3\hinge > ..\text.o3\hinge.txt
..\masmx howmany -lnoy ..\test.o3\howmany > ..\text.o3\howmany.txt
..\masmx howslow -lnoy ..\test.o3\howslow > ..\text.o3\howslow.txt
..\masmx hubert -lnoy ..\test.o3\hubert > ..\text.o3\hubert.txt
..\masmx hwis -lnoy ..\test.o3\hwis > ..\text.o3\hwis.txt
..\masmx ican -lnoy ..\test.o3\ican > ..\text.o3\ican.txt
..\masmx ieee754 -lnoy ..\test.o3\ieee754 > ..\text.o3\ieee754.txt
..\masmx ieee754s -lnoy ..\test.o3\ieee754s > ..\text.o3\ieee754s.txt
..\masmx ieeef -lnoy ..\test.o3\ieeef > ..\text.o3\ieeef.txt
..\masmx if -lnoy ..\test.o3\if > ..\text.o3\if.txt
..\masmx iffy -lnoy ..\test.o3\iffy > ..\text.o3\iffy.txt
..\masmx ifp -lnoy ..\test.o3\ifp > ..\text.o3\ifp.txt
..\masmx ifwise -lnoy ..\test.o3\ifwise > ..\text.o3\ifwise.txt
..\masmx iii -lnoy ..\test.o3\iii > ..\text.o3\iii.txt
..\masmx immediat -lnoy ..\test.o3\immediat > ..\text.o3\immediat.txt
..\masmx import -lnoy ..\test.o3\import > ..\text.o3\import.txt
..\masmx inc -lnoy ..\test.o3\inc > ..\text.o3\inc.txt
..\masmx inc1 -lnoy ..\test.o3\inc1 > ..\text.o3\inc1.txt
..\masmx inc2 -lnoy ..\test.o3\inc2 > ..\text.o3\inc2.txt
..\masmx inc3 -lnoy ..\test.o3\inc3 > ..\text.o3\inc3.txt
..\masmx info -lnoy ..\test.o3\info > ..\text.o3\info.txt
..\masmx inside -lnoy ..\test.o3\inside > ..\text.o3\inside.txt
..\masmx intrepid -lnoy ..\test.o3\intrepid > ..\text.o3\intrepid.txt
..\masmx intune -lnoy ..\test.o3\intune > ..\text.o3\intune.txt
..\masmx iscale1 -lnoy ..\test.o3\iscale1 > ..\text.o3\iscale1.txt
..\masmx iscale2 -lnoy ..\test.o3\iscale2 > ..\text.o3\iscale2.txt
..\masmx iscale3 -lnoy ..\test.o3\iscale3 > ..\text.o3\iscale3.txt
..\masmx iside1 -lnoy ..\test.o3\iside1 > ..\text.o3\iside1.txt
..\masmx isobar -lnoy ..\test.o3\isobar > ..\text.o3\isobar.txt
..\masmx isobar1 -lnoy ..\test.o3\isobar1 > ..\text.o3\isobar1.txt
..\masmx isthatso -lnoy ..\test.o3\isthatso > ..\text.o3\isthatso.txt
..\masmx j2 -lnoy ..\test.o3\j2 > ..\text.o3\j2.txt
..\masmx j3 -lnoy ..\test.o3\j3 > ..\text.o3\j3.txt
..\masmx justname -lnoy ..\test.o3\justname > ..\text.o3\justname.txt
..\masmx keeptry -lnoy ..\test.o3\keeptry > ..\text.o3\keeptry.txt
..\masmx kette -lnoy ..\test.o3\kette > ..\text.o3\kette.txt
..\masmx keyword -lnoy ..\test.o3\keyword > ..\text.o3\keyword.txt
..\masmx l -lnoy ..\test.o3\l > ..\text.o3\l.txt
..\masmx labels -lnoy ..\test.o3\labels > ..\text.o3\labels.txt
..\masmx langobar -lnoy ..\test.o3\langobar > ..\text.o3\langobar.txt
..\masmx largle -lnoy ..\test.o3\largle > ..\text.o3\largle.txt
..\masmx lcodes -lnoy ..\test.o3\lcodes > ..\text.o3\lcodes.txt
..\masmx ldes -lnoy ..\test.o3\ldes > ..\text.o3\ldes.txt
..\masmx ldes2 -lnoy ..\test.o3\ldes2 > ..\text.o3\ldes2.txt
..\masmx leggy -lnoy ..\test.o3\leggy > ..\text.o3\leggy.txt
..\masmx letsbya -lnoy ..\test.o3\letsbya > ..\text.o3\letsbya.txt
..\masmx liable -lnoy ..\test.o3\liable > ..\text.o3\liable.txt
..\masmx linitup -lnoy ..\test.o3\linitup > ..\text.o3\linitup.txt
..\masmx lit -lnoy ..\test.o3\lit > ..\text.o3\lit.txt
..\masmx lit8051 -lnoy ..\test.o3\lit8051 > ..\text.o3\lit8051.txt
..\masmx literal -lnoy ..\test.o3\literal > ..\text.o3\literal.txt
..\masmx little -lnoy ..\test.o3\little > ..\text.o3\little.txt
..\masmx ll -lnoy ..\test.o3\ll > ..\text.o3\ll.txt
..\masmx ll2 -lnoy ..\test.o3\ll2 > ..\text.o3\ll2.txt
..\masmx ll3 -lnoy ..\test.o3\ll3 > ..\text.o3\ll3.txt
..\masmx ll4 -lnoy ..\test.o3\ll4 > ..\text.o3\ll4.txt
..\masmx ll5 -lnoy ..\test.o3\ll5 > ..\text.o3\ll5.txt
..\masmx ll5abs -lnoy ..\test.o3\ll5abs > ..\text.o3\ll5abs.txt
..\masmx ll6 -lnoy ..\test.o3\ll6 > ..\text.o3\ll6.txt
..\masmx ll6abs -lnoy ..\test.o3\ll6abs > ..\text.o3\ll6abs.txt
..\masmx lodation -lnoy ..\test.o3\lodation > ..\text.o3\lodation.txt
..\masmx longjump -lnoy ..\test.o3\longjump > ..\text.o3\longjump.txt
..\masmx loopy -lnoy ..\test.o3\loopy > ..\text.o3\loopy.txt
..\masmx lorg -lnoy ..\test.o3\lorg > ..\text.o3\lorg.txt
..\masmx lorgle -lnoy ..\test.o3\lorgle > ..\text.o3\lorgle.txt
..\masmx luri -lnoy ..\test.o3\luri > ..\text.o3\luri.txt
..\masmx m -lnoy ..\test.o3\m > ..\text.o3\m.txt
..\masmx mafcol1 -lnoy ..\test.o3\mafcol1 > ..\text.o3\mafcol1.txt
..\masmx mangle -lnoy ..\test.o3\mangle > ..\text.o3\mangle.txt
..\masmx mango -lnoy ..\test.o3\mango > ..\text.o3\mango.txt
..\masmx manif -lnoy ..\test.o3\manif > ..\text.o3\manif.txt
..\masmx many -lnoy ..\test.o3\many > ..\text.o3\many.txt
..\masmx map -lnoy ..\test.o3\map > ..\text.o3\map.txt
..\masmx map1 -lnoy ..\test.o3\map1 > ..\text.o3\map1.txt
..\masmx map10 -lnoy ..\test.o3\map10 > ..\text.o3\map10.txt
..\masmx map10g -lnoy ..\test.o3\map10g > ..\text.o3\map10g.txt
..\masmx map11 -lnoy ..\test.o3\map11 > ..\text.o3\map11.txt
..\masmx map12 -lnoy ..\test.o3\map12 > ..\text.o3\map12.txt
..\masmx map15 -lnoy ..\test.o3\map15 > ..\text.o3\map15.txt
..\masmx map2 -lnoy ..\test.o3\map2 > ..\text.o3\map2.txt
..\masmx map3 -lnoy ..\test.o3\map3 > ..\text.o3\map3.txt
..\masmx map4 -lnoy ..\test.o3\map4 > ..\text.o3\map4.txt
..\masmx map5 -lnoy ..\test.o3\map5 > ..\text.o3\map5.txt
..\masmx map6 -lnoy ..\test.o3\map6 > ..\text.o3\map6.txt
..\masmx map7 -lnoy ..\test.o3\map7 > ..\text.o3\map7.txt
..\masmx map7g -lnoy ..\test.o3\map7g > ..\text.o3\map7g.txt
..\masmx map8 -lnoy ..\test.o3\map8 > ..\text.o3\map8.txt
..\masmx map8g -lnoy ..\test.o3\map8g > ..\text.o3\map8g.txt
..\masmx map9 -lnoy ..\test.o3\map9 > ..\text.o3\map9.txt
..\masmx mary -lnoy ..\test.o3\mary > ..\text.o3\mary.txt
..\masmx masm7 -lnoy ..\test.o3\masm7 > ..\text.o3\masm7.txt
..\masmx maxfloat -lnoy ..\test.o3\maxfloat > ..\text.o3\maxfloat.txt
..\masmx maxmaxi -lnoz ..\test.o3\maxmaxi > ..\text.o3\maxmaxi.txt
..\masmx maxtini -lnoz ..\test.o3\maxtini > ..\text.o3\maxtini.txt
..\masmx maxwini -lnoz ..\test.o3\maxwini > ..\text.o3\maxwini.txt
..\masmx mbank -lnoy ..\test.o3\mbank > ..\text.o3\mbank.txt
..\masmx mbank1 -lnoy ..\test.o3\mbank1 > ..\text.o3\mbank1.txt
..\masmx mikros -lnoy ..\test.o3\mikros > ..\text.o3\mikros.txt
..\masmx ml -lnoy ..\test.o3\ml > ..\text.o3\ml.txt
..\masmx mlingba -lnoy ..\test.o3\mlingba > ..\text.o3\mlingba.txt
..\masmx modest -lnoy ..\test.o3\modest > ..\text.o3\modest.txt
..\masmx mojo -lnoy ..\test.o3\mojo > ..\text.o3\mojo.txt
..\masmx more -lnoy ..\test.o3\more > ..\text.o3\more.txt
..\masmx mouli -lnoy ..\test.o3\mouli > ..\text.o3\mouli.txt
..\masmx movem -lnoy ..\test.o3\movem > ..\text.o3\movem.txt
..\masmx multest -lnoy ..\test.o3\multest > ..\text.o3\multest.txt
..\masmx multitr -lnoy ..\test.o3\multitr > ..\text.o3\multitr.txt
..\masmx mungle -lnoy ..\test.o3\mungle > ..\text.o3\mungle.txt
..\masmx n -lnoy ..\test.o3\n > ..\text.o3\n.txt
..\masmx name -lnoy ..\test.o3\name > ..\text.o3\name.txt
..\masmx names -lnoy ..\test.o3\names > ..\text.o3\names.txt
..\masmx nang -lnoy ..\test.o3\nang > ..\text.o3\nang.txt
..\masmx needle -lnoy ..\test.o3\needle > ..\text.o3\needle.txt
..\masmx nest -lnoy ..\test.o3\nest > ..\text.o3\nest.txt
..\masmx netbio -lnoy ..\test.o3\netbio > ..\text.o3\netbio.txt
..\masmx netio -lnoy ..\test.o3\netio > ..\text.o3\netio.txt
..\masmx netvalue -lnoy ..\test.o3\netvalue > ..\text.o3\netvalue.txt
..\masmx new -lnoy ..\test.o3\new > ..\text.o3\new.txt
..\masmx newby -lnoy ..\test.o3\newby > ..\text.o3\newby.txt
..\masmx nipit -lnoy ..\test.o3\nipit > ..\text.o3\nipit.txt
..\masmx norkette -lnoy ..\test.o3\norkette > ..\text.o3\norkette.txt
..\masmx nosedive -lnoy ..\test.o3\nosedive > ..\text.o3\nosedive.txt
..\masmx noso -lnoy ..\test.o3\noso > ..\text.o3\noso.txt
..\masmx nostroph -lnoy ..\test.o3\nostroph > ..\text.o3\nostroph.txt
..\masmx notmany -lnoy ..\test.o3\notmany > ..\text.o3\notmany.txt
..\masmx notso -lnoy ..\test.o3\notso > ..\text.o3\notso.txt
..\masmx notvast -lnoy ..\test.o3\notvast > ..\text.o3\notvast.txt
..\masmx nuri -lnoy ..\test.o3\nuri > ..\text.o3\nuri.txt
..\masmx nvg -lnoy ..\test.o3\nvg > ..\text.o3\nvg.txt
..\masmx o -lnoy ..\test.o3\o > ..\text.o3\o.txt
..\masmx ocycle -lnoy ..\test.o3\ocycle > ..\text.o3\ocycle.txt
..\masmx oddly -lnoy ..\test.o3\oddly > ..\text.o3\oddly.txt
..\masmx offset -lnoy ..\test.o3\offset > ..\text.o3\offset.txt
..\masmx ok1 -lnoy ..\test.o3\ok1 > ..\text.o3\ok1.txt
..\masmx one -lnoy ..\test.o3\one > ..\text.o3\one.txt
..\masmx onetwo -lnoy ..\test.o3\onetwo > ..\text.o3\onetwo.txt
..\masmx oreally -lnoy ..\test.o3\oreally > ..\text.o3\oreally.txt
..\masmx orgalign -lnoy ..\test.o3\orgalign > ..\text.o3\orgalign.txt
..\masmx otherwis -lnoy ..\test.o3\otherwis > ..\text.o3\otherwis.txt
..\masmx outline -lnoy ..\test.o3\outline > ..\text.o3\outline.txt
..\masmx outrage -lnoy ..\test.o3\outrage > ..\text.o3\outrage.txt
..\masmx outside -lnoy ..\test.o3\outside > ..\text.o3\outside.txt
..\masmx overlaid -lnoy ..\test.o3\overlaid > ..\text.o3\overlaid.txt
..\masmx overlay -lnoy ..\test.o3\overlay > ..\text.o3\overlay.txt
..\masmx p -lnoy ..\test.o3\p > ..\text.o3\p.txt
..\masmx packem -lnoy ..\test.o3\packem > ..\text.o3\packem.txt
..\masmx paraform -lnoy ..\test.o3\paraform > ..\text.o3\paraform.txt
..\masmx param -lnoy ..\test.o3\param > ..\text.o3\param.txt
..\masmx paren -lnoy ..\test.o3\paren > ..\text.o3\paren.txt
..\masmx passes -lnoy ..\test.o3\passes > ..\text.o3\passes.txt
..\masmx passive -lnoy ..\test.o3\passive > ..\text.o3\passive.txt
..\masmx perform -lnoy ..\test.o3\perform > ..\text.o3\perform.txt
..\masmx plain -lnoy ..\test.o3\plain > ..\text.o3\plain.txt
..\masmx plank -lnoy ..\test.o3\plank > ..\text.o3\plank.txt
..\masmx plobbo -lnoy ..\test.o3\plobbo > ..\text.o3\plobbo.txt
..\masmx ppc1 -lnoy ..\test.o3\ppc1 > ..\text.o3\ppc1.txt
..\masmx ppcsinga -lnoy ..\test.o3\ppcsinga > ..\text.o3\ppcsinga.txt
..\masmx ppcsingb -lnoy ..\test.o3\ppcsingb > ..\text.o3\ppcsingb.txt
..\masmx ppcsingr -lnoy ..\test.o3\ppcsingr > ..\text.o3\ppcsingr.txt
..\masmx ppcuvast -lnoy ..\test.o3\ppcuvast > ..\text.o3\ppcuvast.txt
..\masmx prango -lnoy ..\test.o3\prango > ..\text.o3\prango.txt
..\masmx prango32 -lnoy ..\test.o3\prango32 > ..\text.o3\prango32.txt
..\masmx pratisla -lnoy ..\test.o3\pratisla > ..\text.o3\pratisla.txt
..\masmx predikat -lnoy ..\test.o3\predikat > ..\text.o3\predikat.txt
..\masmx prelink -lnoy ..\test.o3\prelink > ..\text.o3\prelink.txt
..\masmx proceds -lnoy ..\test.o3\proceds > ..\text.o3\proceds.txt
..\masmx proxy -lnoy ..\test.o3\proxy > ..\text.o3\proxy.txt
..\masmx ptup -lnoy ..\test.o3\ptup > ..\text.o3\ptup.txt
..\masmx pusingv -lnoy ..\test.o3\pusingv > ..\text.o3\pusingv.txt
..\masmx pvusinga -lnoy ..\test.o3\pvusinga > ..\text.o3\pvusinga.txt
..\masmx pzero -lnoy ..\test.o3\pzero > ..\text.o3\pzero.txt
..\masmx q -lnoy ..\test.o3\q > ..\text.o3\q.txt
..\masmx q1 -lnoy ..\test.o3\q1 > ..\text.o3\q1.txt
..\masmx qati -lnoy ..\test.o3\qati > ..\text.o3\qati.txt
..\masmx qb2i -lnoy ..\test.o3\qb2i > ..\text.o3\qb2i.txt
..\masmx qbig -lnoy ..\test.o3\qbig > ..\text.o3\qbig.txt
..\masmx qf -lnoy ..\test.o3\qf > ..\text.o3\qf.txt
..\masmx qflic -lnoy ..\test.o3\qflic > ..\text.o3\qflic.txt
..\masmx qpart -lnoy ..\test.o3\qpart > ..\text.o3\qpart.txt
..\masmx qplain -lnoy ..\test.o3\qplain > ..\text.o3\qplain.txt
..\masmx qt -lnoy ..\test.o3\qt > ..\text.o3\qt.txt
..\masmx quicki -lnoy ..\test.o3\quicki > ..\text.o3\quicki.txt
..\masmx quidgeo -lnoy ..\test.o3\quidgeo > ..\text.o3\quidgeo.txt
..\masmx quitebad -lnoy ..\test.o3\quitebad > ..\text.o3\quitebad.txt
..\masmx quo -lnoy ..\test.o3\quo > ..\text.o3\quo.txt
..\masmx quo1 -lnoy ..\test.o3\quo1 > ..\text.o3\quo1.txt
..\masmx quo2 -lnoy ..\test.o3\quo2 > ..\text.o3\quo2.txt
..\masmx quo3 -lnoy ..\test.o3\quo3 > ..\text.o3\quo3.txt
..\masmx quo4 -lnoy ..\test.o3\quo4 > ..\text.o3\quo4.txt
..\masmx quo5 -lnoy ..\test.o3\quo5 > ..\text.o3\quo5.txt
..\masmx qzuli -lnoy ..\test.o3\qzuli > ..\text.o3\qzuli.txt
..\masmx qzweli -lnoy ..\test.o3\qzweli > ..\text.o3\qzweli.txt
..\masmx r -lnoy ..\test.o3\r > ..\text.o3\r.txt
..\masmx r_u_rel -lnoy ..\test.o3\r_u_rel > ..\text.o3\r_u_rel.txt
..\masmx radalupu -lnoy ..\test.o3\radalupu > ..\text.o3\radalupu.txt
..\masmx random -lnoy ..\test.o3\random > ..\text.o3\random.txt
..\masmx really -lnoy ..\test.o3\really > ..\text.o3\really.txt
..\masmx reappear -lnoy ..\test.o3\reappear > ..\text.o3\reappear.txt
..\masmx reco -lnoy ..\test.o3\reco > ..\text.o3\reco.txt
..\masmx recurs -lnoy ..\test.o3\recurs > ..\text.o3\recurs.txt
..\masmx rel -lnoy ..\test.o3\rel > ..\text.o3\rel.txt
..\masmx rel2 -lnoy ..\test.o3\rel2 > ..\text.o3\rel2.txt
..\masmx relj -lnoy ..\test.o3\relj > ..\text.o3\relj.txt
..\masmx relja -lnoy ..\test.o3\relja > ..\text.o3\relja.txt
..\masmx relstack -lnoy ..\test.o3\relstack > ..\text.o3\relstack.txt
..\masmx remindme -lnoy ..\test.o3\remindme > ..\text.o3\remindme.txt
..\masmx rempack -lnoy ..\test.o3\rempack > ..\text.o3\rempack.txt
..\masmx rempart -lnoy ..\test.o3\rempart > ..\text.o3\rempart.txt
..\masmx rename -lnoy ..\test.o3\rename > ..\text.o3\rename.txt
..\masmx rep -lnoy ..\test.o3\rep > ..\text.o3\rep.txt
..\masmx res -lnoy ..\test.o3\res > ..\text.o3\res.txt
..\masmx rino -lnoy ..\test.o3\rino > ..\text.o3\rino.txt
..\masmx risobar -lnoy ..\test.o3\risobar > ..\text.o3\risobar.txt
..\masmx rough -lnoy ..\test.o3\rough > ..\text.o3\rough.txt
..\masmx roundelay -lnoy ..\test.o3\roundelay > ..\text.o3\roundelay.txt
..\masmx rounding -lnoy ..\test.o3\rounding > ..\text.o3\rounding.txt
..\masmx rplain -lnoy ..\test.o3\rplain > ..\text.o3\rplain.txt
..\masmx rumad -lnoy ..\test.o3\rumad > ..\text.o3\rumad.txt
..\masmx ryatha -lnoy ..\test.o3\ryatha > ..\text.o3\ryatha.txt
..\masmx s -lnoy ..\test.o3\s > ..\text.o3\s.txt
..\masmx sample -lnoy ..\test.o3\sample > ..\text.o3\sample.txt
..\masmx sample2 -lnoy ..\test.o3\sample2 > ..\text.o3\sample2.txt
..\masmx scabrous -lnoy ..\test.o3\scabrous > ..\text.o3\scabrous.txt
..\masmx scale -lnoy ..\test.o3\scale > ..\text.o3\scale.txt
..\masmx scale1 -lnoy ..\test.o3\scale1 > ..\text.o3\scale1.txt
..\masmx scale2 -lnoy ..\test.o3\scale2 > ..\text.o3\scale2.txt
..\masmx scale22 -lnoy ..\test.o3\scale22 > ..\text.o3\scale22.txt
..\masmx scale23 -lnoy ..\test.o3\scale23 > ..\text.o3\scale23.txt
..\masmx scale24 -lnoy ..\test.o3\scale24 > ..\text.o3\scale24.txt
..\masmx scale3 -lnoy ..\test.o3\scale3 > ..\text.o3\scale3.txt
..\masmx scale4 -lnoy ..\test.o3\scale4 > ..\text.o3\scale4.txt
..\masmx scale5 -lnoy ..\test.o3\scale5 > ..\text.o3\scale5.txt
..\masmx scale6 -lnoy ..\test.o3\scale6 > ..\text.o3\scale6.txt
..\masmx scale8 -lnoy ..\test.o3\scale8 > ..\text.o3\scale8.txt
..\masmx scally -lnoy ..\test.o3\scally > ..\text.o3\scally.txt
..\masmx scally2 -lnoy ..\test.o3\scally2 > ..\text.o3\scally2.txt
..\masmx scally3 -lnoy ..\test.o3\scally3 > ..\text.o3\scally3.txt
..\masmx scally4 -lnoy ..\test.o3\scally4 > ..\text.o3\scally4.txt
..\masmx scandal -lnoy ..\test.o3\scandal > ..\text.o3\scandal.txt
..\masmx scrabble -lnoy ..\test.o3\scrabble > ..\text.o3\scrabble.txt
..\masmx see -lnoy ..\test.o3\see > ..\text.o3\see.txt
..\masmx see2it -lnoy ..\test.o3\see2it > ..\text.o3\see2it.txt
..\masmx seomac -lnoy ..\test.o3\seomac > ..\text.o3\seomac.txt
..\masmx set -lnoy ..\test.o3\set > ..\text.o3\set.txt
..\masmx shifty -lnoy ..\test.o3\shifty > ..\text.o3\shifty.txt
..\masmx sim -lnoy ..\test.o3\sim > ..\text.o3\sim.txt
..\masmx similar -lnoy ..\test.o3\similar > ..\text.o3\similar.txt
..\masmx simple -lnoy ..\test.o3\simple > ..\text.o3\simple.txt
..\masmx simpler -lnoy ..\test.o3\simpler > ..\text.o3\simpler.txt
..\masmx simples -lnoy ..\test.o3\simples > ..\text.o3\simples.txt
..\masmx simplify -lnoy ..\test.o3\simplify > ..\text.o3\simplify.txt
..\masmx sipit -lnoy ..\test.o3\sipit > ..\text.o3\sipit.txt
..\masmx sky -lnoy ..\test.o3\sky > ..\text.o3\sky.txt
..\masmx sleunig -lnoy ..\test.o3\sleunig > ..\text.o3\sleunig.txt
..\masmx slingba -lnoy ..\test.o3\slingba > ..\text.o3\slingba.txt
..\masmx slipcan -lnoy ..\test.o3\slipcan > ..\text.o3\slipcan.txt
..\masmx slipshod -lnoy ..\test.o3\slipshod > ..\text.o3\slipshod.txt
..\masmx smaragd -lnoy ..\test.o3\smaragd > ..\text.o3\smaragd.txt
..\masmx smaragd1 -lnoy ..\test.o3\smaragd1 > ..\text.o3\smaragd1.txt
..\masmx smaragd7 -lnoy ..\test.o3\smaragd7 > ..\text.o3\smaragd7.txt
..\masmx snappie -lnoy ..\test.o3\snappie > ..\text.o3\snappie.txt
..\masmx snippie -lnoy ..\test.o3\snippie > ..\text.o3\snippie.txt
..\masmx snozeli -lnoy ..\test.o3\snozeli > ..\text.o3\snozeli.txt
..\masmx somestuf -lnoy ..\test.o3\somestuf > ..\text.o3\somestuf.txt
..\masmx somular -lnoy ..\test.o3\somular > ..\text.o3\somular.txt
..\masmx soso -lnoy ..\test.o3\soso > ..\text.o3\soso.txt
..\masmx space -lnoy ..\test.o3\space > ..\text.o3\space.txt
..\masmx spitz -lnoy ..\test.o3\spitz > ..\text.o3\spitz.txt
..\masmx splativo -lnoy ..\test.o3\splativo > ..\text.o3\splativo.txt
..\masmx sprativo -lnoy ..\test.o3\sprativo > ..\text.o3\sprativo.txt
..\masmx squeeze -lnoy ..\test.o3\squeeze > ..\text.o3\squeeze.txt
..\masmx stack -lnoy ..\test.o3\stack > ..\text.o3\stack.txt
..\masmx stcomple -lnoy ..\test.o3\stcomple > ..\text.o3\stcomple.txt
..\masmx steamer -lnoy ..\test.o3\steamer > ..\text.o3\steamer.txt
..\masmx step1 -lnoy ..\test.o3\step1 > ..\text.o3\step1.txt
..\masmx step2 -lnoy ..\test.o3\step2 > ..\text.o3\step2.txt
..\masmx steps -lnoy ..\test.o3\steps > ..\text.o3\steps.txt
..\masmx sterm -lnoy ..\test.o3\sterm > ..\text.o3\sterm.txt
..\masmx strahl -lnoy ..\test.o3\strahl > ..\text.o3\strahl.txt
..\masmx strain -lnoy ..\test.o3\strain > ..\text.o3\strain.txt
..\masmx straling -lnoy ..\test.o3\straling > ..\text.o3\straling.txt
..\masmx strange -lnoy ..\test.o3\strange > ..\text.o3\strange.txt
..\masmx strangely -lnoy ..\test.o3\strangely > ..\text.o3\strangely.txt
..\masmx stretch -lnoy ..\test.o3\stretch > ..\text.o3\stretch.txt
..\masmx strial1 -lnoy ..\test.o3\strial1 > ..\text.o3\strial1.txt
..\masmx strial2 -lnoy ..\test.o3\strial2 > ..\text.o3\strial2.txt
..\masmx strial3 -lnoy ..\test.o3\strial3 > ..\text.o3\strial3.txt
..\masmx strial4 -lnoy ..\test.o3\strial4 > ..\text.o3\strial4.txt
..\masmx strial5 -lnoy ..\test.o3\strial5 > ..\text.o3\strial5.txt
..\masmx strial6 -lnoy ..\test.o3\strial6 > ..\text.o3\strial6.txt
..\masmx stringli -lnoy ..\test.o3\stringli > ..\text.o3\stringli.txt
..\masmx strophe -lnoy ..\test.o3\strophe > ..\text.o3\strophe.txt
..\masmx strugl5 -lnoy ..\test.o3\strugl5 > ..\text.o3\strugl5.txt
..\masmx stsimple -lnoy ..\test.o3\stsimple > ..\text.o3\stsimple.txt
..\masmx stt -lnoy ..\test.o3\stt > ..\text.o3\stt.txt
..\masmx subfi -lnoy ..\test.o3\subfi > ..\text.o3\subfi.txt
..\masmx submarine -lnoy ..\test.o3\submarine > ..\text.o3\submarine.txt
..\masmx subs -lnoy ..\test.o3\subs > ..\text.o3\subs.txt
..\masmx subs1 -lnoy ..\test.o3\subs1 > ..\text.o3\subs1.txt
..\masmx suficsee -lnoy ..\test.o3\suficsee > ..\text.o3\suficsee.txt
..\masmx suppose -lnoy ..\test.o3\suppose > ..\text.o3\suppose.txt
..\masmx synonyms -lnoy ..\test.o3\synonyms > ..\text.o3\synonyms.txt
..\masmx sysgo -lnoy ..\test.o3\sysgo > ..\text.o3\sysgo.txt
..\masmx table -lnoy ..\test.o3\table > ..\text.o3\table.txt
..\masmx tally2 -lnoy ..\test.o3\tally2 > ..\text.o3\tally2.txt
..\masmx tally3 -lnoy ..\test.o3\tally3 > ..\text.o3\tally3.txt
..\masmx tally4 -lnoy ..\test.o3\tally4 > ..\text.o3\tally4.txt
..\masmx tarsub -lnoy ..\test.o3\tarsub > ..\text.o3\tarsub.txt
..\masmx tcp_in -lnoy ..\test.o3\tcp_in > ..\text.o3\tcp_in.txt
..\masmx tcp_rxip -lnoy ..\test.o3\tcp_rxip > ..\text.o3\tcp_rxip.txt
..\masmx temp -lnoy ..\test.o3\temp > ..\text.o3\temp.txt
..\masmx temper -lnoy ..\test.o3\temper > ..\text.o3\temper.txt
..\masmx tempo -lnoy ..\test.o3\tempo > ..\text.o3\tempo.txt
..\masmx term -lnoy ..\test.o3\term > ..\text.o3\term.txt
..\masmx terrify1 -lnoy ..\test.o3\terrify1 > ..\text.o3\terrify1.txt
..\masmx terrify2 -lnoy ..\test.o3\terrify2 > ..\text.o3\terrify2.txt
..\masmx terrify3 -lnoy ..\test.o3\terrify3 > ..\text.o3\terrify3.txt
..\masmx these -lnoy ..\test.o3\these > ..\text.o3\these.txt
..\masmx thing -lnoy ..\test.o3\thing > ..\text.o3\thing.txt
..\masmx three4 -lnoy ..\test.o3\three4 > ..\text.o3\three4.txt
..\masmx thru -lnoy ..\test.o3\thru > ..\text.o3\thru.txt
..\masmx times -lnoy ..\test.o3\times > ..\text.o3\times.txt
..\masmx tisobar -lnoy ..\test.o3\tisobar > ..\text.o3\tisobar.txt
..\masmx tla -lnoy ..\test.o3\tla > ..\text.o3\tla.txt
..\masmx together -lnoy ..\test.o3\together > ..\text.o3\together.txt
..\masmx tomp -lnoy ..\test.o3\tomp > ..\text.o3\tomp.txt
..\masmx toozl -lnoy ..\test.o3\toozl > ..\text.o3\toozl.txt
..\masmx trail -lnoy ..\test.o3\trail > ..\text.o3\trail.txt
..\masmx trait -lnoy ..\test.o3\trait > ..\text.o3\trait.txt
..\masmx trangle -lnoy ..\test.o3\trangle > ..\text.o3\trangle.txt
..\masmx transport -lnoy ..\test.o3\transport > ..\text.o3\transport.txt
..\masmx tranwys -lnoy ..\test.o3\tranwys > ..\text.o3\tranwys.txt
..\masmx trau -lnoy ..\test.o3\trau > ..\text.o3\trau.txt
..\masmx trbyte -lnoy ..\test.o3\trbyte > ..\text.o3\trbyte.txt
..\masmx tree -lnoy ..\test.o3\tree > ..\text.o3\tree.txt
..\masmx trees -lnoy ..\test.o3\trees > ..\text.o3\trees.txt
..\masmx tribit -lnoy ..\test.o3\tribit > ..\text.o3\tribit.txt
..\masmx tricki -lnoy ..\test.o3\tricki > ..\text.o3\tricki.txt
..\masmx trinsic -lnoy ..\test.o3\trinsic > ..\text.o3\trinsic.txt
..\masmx trip -lnoy ..\test.o3\trip > ..\text.o3\trip.txt
..\masmx trivial -lnoy ..\test.o3\trivial > ..\text.o3\trivial.txt
..\masmx trivs -lnoy ..\test.o3\trivs > ..\text.o3\trivs.txt
..\masmx trtab -lnoy ..\test.o3\trtab > ..\text.o3\trtab.txt
..\masmx trtab2 -lnoy ..\test.o3\trtab2 > ..\text.o3\trtab2.txt
..\masmx tryafew -lnoy ..\test.o3\tryafew > ..\text.o3\tryafew.txt
..\masmx trysome -lnoy ..\test.o3\trysome > ..\text.o3\trysome.txt
..\masmx ttable -lnoy ..\test.o3\ttable > ..\text.o3\ttable.txt
..\masmx tump -lnoy ..\test.o3\tump > ..\text.o3\tump.txt
..\masmx tumpoon -lnoy ..\test.o3\tumpoon > ..\text.o3\tumpoon.txt
..\masmx tumpshie -lnoy ..\test.o3\tumpshie > ..\text.o3\tumpshie.txt
..\masmx twiggy -lnoy ..\test.o3\twiggy > ..\text.o3\twiggy.txt
..\masmx tz -lnoy ..\test.o3\tz > ..\text.o3\tz.txt
..\masmx uart -lnoy ..\test.o3\uart > ..\text.o3\uart.txt
..\masmx udp_rxip -lnoy ..\test.o3\udp_rxip > ..\text.o3\udp_rxip.txt
..\masmx updown -lnoy ..\test.o3\updown > ..\text.o3\updown.txt
..\masmx using -lnoy ..\test.o3\using > ..\text.o3\using.txt
..\masmx usinga -lnoy ..\test.o3\usinga > ..\text.o3\usinga.txt
..\masmx usingb -lnoy ..\test.o3\usingb > ..\text.o3\usingb.txt
..\masmx usingl -lnoy ..\test.o3\usingl > ..\text.o3\usingl.txt
..\masmx usingpv -lnoy ..\test.o3\usingpv > ..\text.o3\usingpv.txt
..\masmx usingr -lnoy ..\test.o3\usingr > ..\text.o3\usingr.txt
..\masmx usingv -lnoy ..\test.o3\usingv > ..\text.o3\usingv.txt
..\masmx utable -lnoy ..\test.o3\utable > ..\text.o3\utable.txt
..\masmx uzactor -lnoy ..\test.o3\uzactor > ..\text.o3\uzactor.txt
..\masmx v -lnoy ..\test.o3\v > ..\text.o3\v.txt
..\masmx var -lnoy ..\test.o3\var > ..\text.o3\var.txt
..\masmx vast -lnoy ..\test.o3\vast > ..\text.o3\vast.txt
..\masmx vector -lnoy ..\test.o3\vector > ..\text.o3\vector.txt
..\masmx viable -lnoy ..\test.o3\viable > ..\text.o3\viable.txt
..\masmx victim -lnoy ..\test.o3\victim > ..\text.o3\victim.txt
..\masmx visobar -lnoy ..\test.o3\visobar > ..\text.o3\visobar.txt
..\masmx vitest -lnoy ..\test.o3\vitest > ..\text.o3\vitest.txt
..\masmx vitest2 -lnoy ..\test.o3\vitest2 > ..\text.o3\vitest2.txt
..\masmx vitest3 -lnoy ..\test.o3\vitest3 > ..\text.o3\vitest3.txt
..\masmx void -lnoy ..\test.o3\void > ..\text.o3\void.txt
..\masmx vr -lnoy ..\test.o3\vr > ..\text.o3\vr.txt
..\masmx vsim -lnoy ..\test.o3\vsim > ..\text.o3\vsim.txt
..\masmx vsimpl -lnoy ..\test.o3\vsimpl > ..\text.o3\vsimpl.txt
..\masmx vsimpl2 -lnoy ..\test.o3\vsimpl2 > ..\text.o3\vsimpl2.txt
..\masmx vspace -lnoy ..\test.o3\vspace > ..\text.o3\vspace.txt
..\masmx wanayooz -lnoy ..\test.o3\wanayooz > ..\text.o3\wanayooz.txt
..\masmx watabout -lnoy ..\test.o3\watabout > ..\text.o3\watabout.txt
..\masmx watslong -lnoy ..\test.o3\watslong > ..\text.o3\watslong.txt
..\masmx weel -lnoy ..\test.o3\weel > ..\text.o3\weel.txt
..\masmx welblech -lnoy ..\test.o3\welblech > ..\text.o3\welblech.txt
..\masmx wellaugh -lnoy ..\test.o3\wellaugh > ..\text.o3\wellaugh.txt
..\masmx wellbad -lnoy ..\test.o3\wellbad > ..\text.o3\wellbad.txt
..\masmx wellfest -lnoy ..\test.o3\wellfest > ..\text.o3\wellfest.txt
..\masmx whereami -lnoy ..\test.o3\whereami > ..\text.o3\whereami.txt
..\masmx whether -lnoy ..\test.o3\whether > ..\text.o3\whether.txt
..\masmx why -lnoy ..\test.o3\why > ..\text.o3\why.txt
..\masmx wibl -lnoy ..\test.o3\wibl > ..\text.o3\wibl.txt
..\masmx wirr -lnoy ..\test.o3\wirr > ..\text.o3\wirr.txt
..\masmx wolverine -lnoy ..\test.o3\wolverine > ..\text.o3\wolverine.txt
..\masmx woodbits -lnoy ..\test.o3\woodbits > ..\text.o3\woodbits.txt
..\masmx worser -lnoy ..\test.o3\worser > ..\text.o3\worser.txt
..\masmx wozita -lnoy ..\test.o3\wozita > ..\text.o3\wozita.txt
..\masmx wyzat -lnoy ..\test.o3\wyzat > ..\text.o3\wyzat.txt
..\masmx xtrem -lnoy ..\test.o3\xtrem > ..\text.o3\xtrem.txt
..\masmx yanutha -lnoy ..\test.o3\yanutha > ..\text.o3\yanutha.txt
..\masmx yasimi -lnoy ..\test.o3\yasimi > ..\text.o3\yasimi.txt
..\masmx yepnope -lnoy ..\test.o3\yepnope > ..\text.o3\yepnope.txt
..\masmx yoho -lnoy ..\test.o3\yoho > ..\text.o3\yoho.txt
..\masmx yowl -lnoy ..\test.o3\yowl > ..\text.o3\yowl.txt
..\masmx ytup -lnoy ..\test.o3\ytup > ..\text.o3\ytup.txt
..\masmx zactor -lnoy ..\test.o3\zactor > ..\text.o3\zactor.txt
..\masmx zibble -lnoy ..\test.o3\zibble > ..\text.o3\zibble.txt
..\masmx zipit -lnoy ..\test.o3\zipit > ..\text.o3\zipit.txt
..\masmx zoto -lnoy ..\test.o3\zoto > ..\text.o3\zoto.txt
..\masmx ztup -lnoy ..\test.o3\ztup > ..\text.o3\ztup.txt
call ..\linkpart
call ..\coldfire
call ..\ppc_kern
