del ..\gtest.zo3\*.*
del ..\gtext.zo3\*.*
..\gmasmz 1101 ..\test.zo3\1101.txo -lo> ..\text.zo3\1101.txt
..\gmasmz 1103 ..\test.zo3\1103.txo -lo> ..\text.zo3\1103.txt
..\gmasmz 14 ..\test.zo3\14.txo -lo> ..\text.zo3\14.txt
..\gmasmz 16lib24 ..\test.zo3\16lib24.txo -lo> ..\text.zo3\16lib24.txt
..\gmasmz 1st ..\test.zo3\1st.txo -lo> ..\text.zo3\1st.txt
..\gmasmz 2468 ..\test.zo3\2468.txo -lo> ..\text.zo3\2468.txt
..\gmasmz 2nd ..\test.zo3\2nd.txo -lo> ..\text.zo3\2nd.txt
..\gmasmz 2manif ..\test.zo3\2manif.txo -lo> ..\text.zo3\2manif.txt
..\gmasmz 3rd ..\test.zo3\3rd.txo -lo> ..\text.zo3\3rd.txt
..\gmasmz 3byte ..\test.zo3\3byte.txo -lo> ..\text.zo3\3byte.txt
..\gmasmz @ ..\test.zo3\@.txo -lo> ..\text.zo3\@.txt
..\gmasmz @1 ..\test.zo3\@1.txo -lo> ..\text.zo3\@1.txt
..\gmasmz about ..\test.zo3\about.txo -lo> ..\text.zo3\about.txt
..\gmasmz algebra ..\test.zo3\algebra.txo -lo> ..\text.zo3\algebra.txt
..\gmasmz app ..\test.zo3\app.txo -lo> ..\text.zo3\app.txt
..\gmasmz app7 ..\test.zo3\app7.txo -lo> ..\text.zo3\app7.txt
..\gmasmz aqt ..\test.zo3\aqt.txo -lo> ..\text.zo3\aqt.txt
..\gmasmz azuli ..\test.zo3\azuli.txo -lo> ..\text.zo3\azuli.txt
..\gmasmz balance ..\test.zo3\balance.txo -lo> ..\text.zo3\balance.txt
..\gmasmz big48 ..\test.zo3\big48.txo -lo> ..\text.zo3\big48.txt
..\gmasmz bogle ..\test.zo3\bogle.txo -lo> ..\text.zo3\bogle.txt
..\gmasmz btest ..\test.zo3\btest.txo -lo> ..\text.zo3\btest.txt
..\gmasmz buy_sell ..\test.zo3\buy_sell.txo -lo> ..\text.zo3\buy_sell.txt
..\gmasmz capsule ..\test.zo3\capsule.txo -lo> ..\text.zo3\capsule.txt
..\gmasmz code ..\test.zo3\code.txo -lo> ..\text.zo3\code.txt
..\gmasmz commas ..\test.zo3\commas.txo -lo> ..\text.zo3\commas.txt
..\gmasmz cqt ..\test.zo3\cqt.txo -lo> ..\text.zo3\cqt.txt
..\gmasmz ctest ..\test.zo3\ctest.txo -lo> ..\text.zo3\ctest.txt
..\gmasmz d ..\test.zo3\d.txo -lo> ..\text.zo3\d.txt
..\gmasmz ddd ..\test.zo3\ddd.txo -lo> ..\text.zo3\ddd.txt
..\gmasmz dfp ..\test.zo3\dfp.txo -lo> ..\text.zo3\dfp.txt
..\gmasmz dfp16 ..\test.zo3\dfp16.txo -lo> ..\text.zo3\dfp16.txt
..\gmasmz do1 ..\test.zo3\do1.txo -lo> ..\text.zo3\do1.txt
..\gmasmz dollar ..\test.zo3\dollar.txo -lo> ..\text.zo3\dollar.txt
..\gmasmz dollar1 ..\test.zo3\dollar1.txo -lo> ..\text.zo3\dollar1.txt
..\gmasmz drat ..\test.zo3\drat.txo -lo> ..\text.zo3\drat.txt
..\gmasmz dup ..\test.zo3\dup.txo -lo> ..\text.zo3\dup.txt
..\gmasmz dx ..\test.zo3\dx.txo -lo> ..\text.zo3\dx.txt
..\gmasmz edit ..\test.zo3\edit.txo -lo> ..\text.zo3\edit.txt
..\gmasmz eq ..\test.zo3\eq.txo -lo> ..\text.zo3\eq.txt
..\gmasmz export ..\test.zo3\export.txo -lo> ..\text.zo3\export.txt
..\gmasmz fatalp ..\test.zo3\fatalp.txo -lo> ..\text.zo3\fatalp.txt
# ..\gmasmz feelup ..\test.zo3\feelup.txo -lo> ..\text.zo3\feelup.txt
..\gmasmz tremp ..\test.zo3\tremp -lo > ..\text.zo3\tremp.txt
..\gmasmz forgot ..\test.zo3\forgot.txo -lo> ..\text.zo3\forgot.txt
..\gmasmz form ..\test.zo3\form.txo -lo> ..\text.zo3\form.txt
..\gmasmz fp ..\test.zo3\fp.txo -lo> ..\text.zo3\fp.txt
..\gmasmz fp32 ..\test.zo3\fp32.txo -lo> ..\text.zo3\fp32.txt
..\gmasmz fpsize ..\test.zo3\fpsize.txo -lo> ..\text.zo3\fpsize.txt
..\gmasmz fptest ..\test.zo3\fptest.txo -lo> ..\text.zo3\fptest.txt
..\gmasmz fptestu ..\test.zo3\fptestu.txo -lo> ..\text.zo3\fptestu.txt
..\gmasmz fpx ..\test.zo3\fpx.txo -lo> ..\text.zo3\fpx.txt
..\gmasmz fs ..\test.zo3\fs.txo -lo> ..\text.zo3\fs.txt
..\gmasmz fs32 ..\test.zo3\fs32.txo -lo> ..\text.zo3\fs32.txt
..\gmasmz fx ..\test.zo3\fx.txo -lo> ..\text.zo3\fx.txt
..\gmasmz gflo ..\test.zo3\gflo.txo -lo> ..\text.zo3\gflo.txt
..\gmasmz grade ..\test.zo3\grade.txo -lo> ..\text.zo3\grade.txt
..\gmasmz grig ..\test.zo3\grig.txo -lo> ..\text.zo3\grig.txt
..\gmasmz grind ..\test.zo3\grind.txo -lo > ..\text.zo3\grind.txt
..\gmasmz grobags ..\test.zo3\grobags.txo -lo> ..\text.zo3\grobags.txt
..\gmasmz hflo ..\test.zo3\hflo.txo -lo> ..\text.zo3\hflo.txt
..\gmasmz howslow ..\test.zo3\howslow.txo -lo> ..\text.zo3\howslow.txt
..\gmasmz ieee754 ..\test.zo3\ieee754.txo -lo> ..\text.zo3\ieee754.txt
..\gmasmz ieeef ..\test.zo3\ieeef.txo -lo> ..\text.zo3\ieeef.txt
..\gmasmz if ..\test.zo3\if.txo -lo> ..\text.zo3\if.txt
..\gmasmz iffy ..\test.zo3\iffy.txo -lo> ..\text.zo3\iffy.txt
..\gmasmz ifwise ..\test.zo3\ifwise.txo -lo> ..\text.zo3\ifwise.txt
..\gmasmz immediat ..\test.zo3\immediat.txo -lo> ..\text.zo3\immediat.txt
..\gmasmz import ..\test.zo3\import.txo -lo> ..\text.zo3\import.txt
..\gmasmz inc ..\test.zo3\inc.txo -lo> ..\text.zo3\inc.txt
..\gmasmz inc1 ..\test.zo3\inc1.txo -lo> ..\text.zo3\inc1.txt
..\gmasmz inc2 ..\test.zo3\inc2.txo -lo> ..\text.zo3\inc2.txt
..\gmasmz inc3 ..\test.zo3\inc3.txo -lo> ..\text.zo3\inc3.txt
..\gmasmz j2 ..\test.zo3\j2.txo -lo> ..\text.zo3\j2.txt
..\gmasmz labels ..\test.zo3\labels.txo -lo> ..\text.zo3\labels.txt
..\gmasmz ldes ..\test.zo3\ldes.txo -lo> ..\text.zo3\ldes.txt
..\gmasmz leggy ..\test.zo3\leggy.txo -lo> ..\text.zo3\leggy.txt
..\gmasmz liable ..\test.zo3\liable.txo -lo> ..\text.zo3\liable.txt
..\gmasmz literal ..\test.zo3\literal.txo -lo> ..\text.zo3\literal.txt
..\gmasmz ll ..\test.zo3\ll.txo -lo> ..\text.zo3\ll.txt
..\gmasmz ll2 ..\test.zo3\ll2.txo -lo> ..\text.zo3\ll2.txt
..\gmasmz luri ..\test.zo3\luri.txo -lo> ..\text.zo3\luri.txt
..\gmasmz mafcol1 ..\test.zo3\mafcol1.txo -lo> ..\text.zo3\mafcol1.txt
..\gmasmz mango ..\test.zo3\mango.txo -lo> ..\text.zo3\mango.txt
..\gmasmz map10g ..\test.zo3\map10g.txo -lo> ..\text.zo3\map10g.txt
..\gmasmz map8g ..\test.zo3\map8g.txo -lo> ..\text.zo3\map8g.txt
..\gmasmz masm7 ..\test.zo3\masm7.txo -lo> ..\text.zo3\masm7.txt
..\gmasmz maxfloat ..\test.zo3\maxfloat.txo -lo> ..\text.zo3\maxfloat.txt
..\gmasmz maxtini ..\test.zo3\maxtini.txo -lo> ..\text.zo3\maxtini.txt
..\gmasmz maxwini ..\test.zo3\maxwini.txo -lo> ..\text.zo3\maxwini.txt
..\gmasmz more ..\test.zo3\more.txo -lo> ..\text.zo3\more.txt
..\gmasmz n ..\test.zo3\n.txo -lo> ..\text.zo3\n.txt
..\gmasmz name ..\test.zo3\name.txo -lo> ..\text.zo3\name.txt
..\gmasmz netio ..\test.zo3\netio.txo -lo> ..\text.zo3\netio.txt
..\gmasmz nipit ..\test.zo3\nipit.txo -lo> ..\text.zo3\nipit.txt
..\gmasmz nostroph ..\test.zo3\nostroph.txo -lo> ..\text.zo3\nostroph.txt
..\gmasmz notvast ..\test.zo3\notvast.txo -lo> ..\text.zo3\notvast.txt
..\gmasmz nuri ..\test.zo3\nuri.txo -lo> ..\text.zo3\nuri.txt
..\gmasmz nvg ..\test.zo3\nvg.txo -lo> ..\text.zo3\nvg.txt
..\gmasmz o ..\test.zo3\o.txo -lo> ..\text.zo3\o.txt
..\gmasmz outline ..\test.zo3\outline.txo -lo> ..\text.zo3\outline.txt
..\gmasmz prelink ..\test.zo3\prelink.txo -lo> ..\text.zo3\prelink.txt
..\gmasmz q ..\test.zo3\q.txo -lo> ..\text.zo3\q.txt
..\gmasmz qb2i ..\test.zo3\qb2i.txo -lo> ..\text.zo3\qb2i.txt
..\gmasmz quicki ..\test.zo3\quicki.txo -lo> ..\text.zo3\quicki.txt
..\gmasmz qzuli ..\test.zo3\qzuli.txo -lo> ..\text.zo3\qzuli.txt
..\gmasmz qzweli ..\test.zo3\qzweli.txo -lo> ..\text.zo3\qzweli.txt
..\gmasmz random ..\test.zo3\random.txo -lo> ..\text.zo3\random.txt
..\gmasmz rel ..\test.zo3\rel.txo -lo> ..\text.zo3\rel.txt
..\gmasmz rel2 ..\test.zo3\rel2.txo -lo> ..\text.zo3\rel2.txt
..\gmasmz remindme ..\test.zo3\remindme.txo -lo> ..\text.zo3\remindme.txt
..\gmasmz rino ..\test.zo3\rino.txo -lo> ..\text.zo3\rino.txt
..\gmasmz rounding ..\test.zo3\rounding.txo -lo> ..\text.zo3\rounding.txt
..\gmasmz s ..\test.zo3\s.txo -lo> ..\text.zo3\s.txt
..\gmasmz scally ..\test.zo3\scally.txo -lo> ..\text.zo3\scally.txt
..\gmasmz see ..\test.zo3\see.txo -lo> ..\text.zo3\see.txt
..\gmasmz simples ..\test.zo3\simples.txo -lo> ..\text.zo3\simples.txt
..\gmasmz snozeli ..\test.zo3\snozeli.txo -lo> ..\text.zo3\snozeli.txt
..\gmasmz space ..\test.zo3\space.txo -lo> ..\text.zo3\space.txt
..\gmasmz steps ..\test.zo3\steps.txo -lo> ..\text.zo3\steps.txt
..\gmasmz strophe ..\test.zo3\strophe.txo -lo> ..\text.zo3\strophe.txt
..\gmasmz subs ..\test.zo3\subs.txo -lo> ..\text.zo3\subs.txt
..\gmasmz suficsee ..\test.zo3\suficsee.txo -lo> ..\text.zo3\suficsee.txt
..\gmasmz tcp_rxip ..\test.zo3\tcp_rxip.txo -lo> ..\text.zo3\tcp_rxip.txt
..\gmasmz trivial ..\test.zo3\trivial.txo -lo> ..\text.zo3\trivial.txt
..\gmasmz trtab2 ..\test.zo3\trtab2.txo -lo> ..\text.zo3\trtab2.txt
..\gmasmz ttable ..\test.zo3\ttable.txo -lo> ..\text.zo3\ttable.txt
..\gmasmz vsim ..\test.zo3\vsim.txo -lo> ..\text.zo3\vsim.txt
..\gmasmz whereami ..\test.zo3\whereami.txo -lo> ..\text.zo3\whereami.txt
..\gmasmz whether ..\test.zo3\whether.txo -lo> ..\text.zo3\whether.txt
..\gmasmz yepnope ..\test.zo3\yepnope.txo -lo> ..\text.zo3\yepnope.txt
..\gmasmz zipit ..\test.zo3\zipit.txo -lo> ..\text.zo3\zipit.txt
..\gmasmz abit ..\test.zo3\abit.txo -lo> ..\text.zo3\abit.txt
..\gmasmz addo ..\test.zo3\addo.txo -lo> ..\text.zo3\addo.txt
..\gmasmz addu ..\test.zo3\addu.txo -lo> ..\text.zo3\addu.txt
..\gmasmz addz ..\test.zo3\addz.txo -lo> ..\text.zo3\addz.txt
..\gmasmz adsomor1 ..\test.zo3\adsomor1.txo -lo> ..\text.zo3\adsomor1.txt
..\gmasmz adsomor2 ..\test.zo3\adsomor2.txo -lo> ..\text.zo3\adsomor2.txt
..\gmasmz adsomor3 ..\test.zo3\adsomor3.txo -lo> ..\text.zo3\adsomor3.txt
..\gmasmz adsomor4 ..\test.zo3\adsomor4.txo -lo> ..\text.zo3\adsomor4.txt
..\gmasmz afile ..\test.zo3\afile.txo -lo> ..\text.zo3\afile.txt
..\gmasmz aglimpse ..\test.zo3\aglimpse.txo -lo> ..\text.zo3\aglimpse.txt
..\gmasmz agranoy ..\test.zo3\agranoy.txo -lo> ..\text.zo3\agranoy.txt
..\gmasmz ajoko ..\test.zo3\ajoko.txo -lo> ..\text.zo3\ajoko.txt
..\gmasmz align ..\test.zo3\align.txo -lo> ..\text.zo3\align.txt
..\gmasmz allyoobl ..\test.zo3\allyoobl.txo -lo> ..\text.zo3\allyoobl.txt
..\gmasmz anew ..\test.zo3\anew.txo -lo> ..\text.zo3\anew.txt
..\gmasmz another ..\test.zo3\another.txo -lo> ..\text.zo3\another.txt
..\gmasmz aon ..\test.zo3\aon.txo -lo> ..\text.zo3\aon.txt
..\gmasmz app1 ..\test.zo3\app1.txo -lo> ..\text.zo3\app1.txt
..\gmasmz app2 ..\test.zo3\app2.txo -lo> ..\text.zo3\app2.txt
..\gmasmz app3 ..\test.zo3\app3.txo -lo> ..\text.zo3\app3.txt
..\gmasmz app4 ..\test.zo3\app4.txo -lo> ..\text.zo3\app4.txt
..\gmasmz appoint ..\test.zo3\appoint.txo -lo> ..\text.zo3\appoint.txt
..\gmasmz approx ..\test.zo3\approx.txo -lo> ..\text.zo3\approx.txt
..\gmasmz arm ..\test.zo3\arm.txo -lo> ..\text.zo3\arm.txt
..\gmasmz array ..\test.zo3\array.txo -lo> ..\text.zo3\array.txt
..\gmasmz arrayok ..\test.zo3\arrayok.txo -lo> ..\text.zo3\arrayok.txt
..\gmasmz asample ..\test.zo3\asample.txo -lo> ..\text.zo3\asample.txt
..\gmasmz ast ..\test.zo3\ast.txo -lo> ..\text.zo3\ast.txt
..\gmasmz atest ..\test.zo3\atest.txo -lo> ..\text.zo3\atest.txt
..\gmasmz attempt ..\test.zo3\attempt.txo -lo> ..\text.zo3\attempt.txt
..\gmasmz avast ..\test.zo3\avast.txo -lo> ..\text.zo3\avast.txt
..\gmasmz avastok ..\test.zo3\avastok.txo -lo> ..\text.zo3\avastok.txt
..\gmasmz avenu ..\test.zo3\avenu.txo -lo> ..\text.zo3\avenu.txt
..\gmasmz awail ..\test.zo3\awail.txo -lo> ..\text.zo3\awail.txt
..\gmasmz awain ..\test.zo3\awain.txo -lo> ..\text.zo3\awain.txt
..\gmasmz away ..\test.zo3\away.txo -lo> ..\text.zo3\away.txt
..\gmasmz awkward ..\test.zo3\awkward.txo -lo> ..\text.zo3\awkward.txt
..\gmasmz b ..\test.zo3\b.txo -lo> ..\text.zo3\b.txt
..\gmasmz badly ..\test.zo3\badly.txo -lo> ..\text.zo3\badly.txt
..\gmasmz banks ..\test.zo3\banks.txo -lo> ..\text.zo3\banks.txt
..\gmasmz banks2 ..\test.zo3\banks2.txo -lo> ..\text.zo3\banks2.txt
..\gmasmz basal1 ..\test.zo3\basal1.txo -lo> ..\text.zo3\basal1.txt
..\gmasmz basalall ..\test.zo3\basalall.txo -lo> ..\text.zo3\basalall.txt
..\gmasmz basalone ..\test.zo3\basalone.txo -lo> ..\text.zo3\basalone.txt
..\gmasmz basalthr ..\test.zo3\basalthr.txo -lo> ..\text.zo3\basalthr.txt
..\gmasmz basaltwo ..\test.zo3\basaltwo.txo -lo> ..\text.zo3\basaltwo.txt
..\gmasmz basis ..\test.zo3\basis.txo -lo> ..\text.zo3\basis.txt
..\gmasmz bdw ..\test.zo3\bdw.txo -lo> ..\text.zo3\bdw.txt
..\gmasmz bequf ..\test.zo3\bequf.txo -lo> ..\text.zo3\bequf.txt
..\gmasmz big ..\test.zo3\big.txo -lo> ..\text.zo3\big.txt
..\gmasmz bitsof ..\test.zo3\bitsof.txo -lo> ..\text.zo3\bitsof.txt
..\gmasmz blanks ..\test.zo3\blanks.txo -lo> ..\text.zo3\blanks.txt
..\gmasmz bonkers ..\test.zo3\bonkers.txo -lo> ..\text.zo3\bonkers.txt
..\gmasmz bounded ..\test.zo3\bounded.txo -lo> ..\text.zo3\bounded.txt
..\gmasmz boxy ..\test.zo3\boxy.txo -lo> ..\text.zo3\boxy.txt
..\gmasmz bqt ..\test.zo3\bqt.txo -lo> ..\text.zo3\bqt.txt
..\gmasmz brickie ..\test.zo3\brickie.txo -lo> ..\text.zo3\brickie.txt
..\gmasmz brozzing ..\test.zo3\brozzing.txo -lo> ..\text.zo3\brozzing.txt
..\gmasmz bway ..\test.zo3\bway.txo -lo> ..\text.zo3\bway.txt
..\gmasmz cancan ..\test.zo3\cancan.txo -lo> ..\text.zo3\cancan.txt
..\gmasmz carryon ..\test.zo3\carryon.txo -lo> ..\text.zo3\carryon.txt
..\gmasmz case ..\test.zo3\case.txo -lo> ..\text.zo3\case.txt
..\gmasmz cases ..\test.zo3\cases.txo -lo> ..\text.zo3\cases.txt
..\gmasmz cdml ..\test.zo3\cdml.txo -lo> ..\text.zo3\cdml.txt
..\gmasmz cheese ..\test.zo3\cheese.txo -lo> ..\text.zo3\cheese.txt
..\gmasmz comment ..\test.zo3\comment.txo -lo> ..\text.zo3\comment.txt
..\gmasmz comment1 ..\test.zo3\comment1.txo -lo> ..\text.zo3\comment1.txt
..\gmasmz complex ..\test.zo3\complex.txo -lo> ..\text.zo3\complex.txt
..\gmasmz compo ..\test.zo3\compo.txo -lo> ..\text.zo3\compo.txt
..\gmasmz compose ..\test.zo3\compose.txo -lo> ..\text.zo3\compose.txt
..\gmasmz constanz ..\test.zo3\constanz.txo -lo> ..\text.zo3\constanz.txt
..\gmasmz context ..\test.zo3\context.txo -lo> ..\text.zo3\context.txt
..\gmasmz contrary ..\test.zo3\contrary.txo -lo> ..\text.zo3\contrary.txt
..\gmasmz controb2 ..\test.zo3\controb2.txo -lo> ..\text.zo3\controb2.txt
..\gmasmz control1 ..\test.zo3\control1.txo -lo> ..\text.zo3\control1.txt
..\gmasmz control2 ..\test.zo3\control2.txo -lo> ..\text.zo3\control2.txt
..\gmasmz control3 ..\test.zo3\control3.txo -lo> ..\text.zo3\control3.txt
..\gmasmz control4 ..\test.zo3\control4.txo -lo> ..\text.zo3\control4.txt
..\gmasmz crabble ..\test.zo3\crabble.txo -lo> ..\text.zo3\crabble.txt
..\gmasmz dd ..\test.zo3\dd.txo -lo> ..\text.zo3\dd.txt
..\gmasmz dde ..\test.zo3\dde.txo -lo> ..\text.zo3\dde.txt
..\gmasmz decode ..\test.zo3\decode.txo -lo> ..\text.zo3\decode.txt
..\gmasmz deep ..\test.zo3\deep.txo -lo> ..\text.zo3\deep.txt
..\gmasmz deep_lit ..\test.zo3\deep_lit.txo -lo> ..\text.zo3\deep_lit.txt
..\gmasmz demo1 ..\test.zo3\demo1.txo -lo> ..\text.zo3\demo1.txt
..\gmasmz demo2 ..\test.zo3\demo2.txo -lo> ..\text.zo3\demo2.txt
..\gmasmz demo3 ..\test.zo3\demo3.txo -lo> ..\text.zo3\demo3.txt
..\gmasmz detune ..\test.zo3\detune.txo -lo> ..\text.zo3\detune.txt
..\gmasmz dfp16 ..\test.zo3\dfp16.txo -lo> ..\text.zo3\dfp16.txt
..\gmasmz diffi ..\test.zo3\diffi.txo -lo> ..\text.zo3\diffi.txt
..\gmasmz dl ..\test.zo3\dl.txo -lo> ..\text.zo3\dl.txt
..\gmasmz do ..\test.zo3\do.txo -lo> ..\text.zo3\do.txt
..\gmasmz do2 ..\test.zo3\do2.txo -lo> ..\text.zo3\do2.txt
..\gmasmz do3 ..\test.zo3\do3.txo -lo> ..\text.zo3\do3.txt
..\gmasmz do32 ..\test.zo3\do32.txo -lo> ..\text.zo3\do32.txt
..\gmasmz do4 ..\test.zo3\do4.txo -lo> ..\text.zo3\do4.txt
..\gmasmz dogma ..\test.zo3\dogma.txo -lo> ..\text.zo3\dogma.txt
..\gmasmz dotable ..\test.zo3\dotable.txo -lo> ..\text.zo3\dotable.txt
..\gmasmz dudif ..\test.zo3\dudif.txo -lo> ..\text.zo3\dudif.txt
..\gmasmz dumexa ..\test.zo3\dumexa.txo -lo> ..\text.zo3\dumexa.txt
..\gmasmz elboaze ..\test.zo3\elboaze.txo -lo> ..\text.zo3\elboaze.txt
..\gmasmz elf ..\test.zo3\elf.txo -lo> ..\text.zo3\elf.txt
..\gmasmz entrada ..\test.zo3\entrada.txo -lo> ..\text.zo3\entrada.txt
..\gmasmz environ ..\test.zo3\environ.txo -lo> ..\text.zo3\environ.txt
..\gmasmz equf ..\test.zo3\equf.txo -lo> ..\text.zo3\equf.txt
..\gmasmz equf32 ..\test.zo3\equf32.txo -lo> ..\text.zo3\equf32.txt
..\gmasmz expo ..\test.zo3\expo.txo -lo> ..\text.zo3\expo.txt
..\gmasmz f ..\test.zo3\f.txo -lo> ..\text.zo3\f.txt
..\gmasmz f2f ..\test.zo3\f2f.txo -lo> ..\text.zo3\f2f.txt
..\gmasmz factor ..\test.zo3\factor.txo -lo> ..\text.zo3\factor.txt
..\gmasmz fames ..\test.zo3\fames.txo -lo> ..\text.zo3\fames.txt
..\gmasmz fff ..\test.zo3\fff.txo -lo> ..\text.zo3\fff.txt
..\gmasmz flags ..\test.zo3\flags.txo -lo> ..\text.zo3\flags.txt
..\gmasmz forjoy ..\test.zo3\forjoy.txo -lo> ..\text.zo3\forjoy.txt
..\gmasmz fragment ..\test.zo3\fragment.txo -lo> ..\text.zo3\fragment.txt
..\gmasmz frame2 ..\test.zo3\frame2.txo -lo> ..\text.zo3\frame2.txt
..\gmasmz fref ..\test.zo3\fref.txo -lo> ..\text.zo3\fref.txt
..\gmasmz fruit ..\test.zo3\fruit.txo -lo> ..\text.zo3\fruit.txt
..\gmasmz frung ..\test.zo3\frung.txo -lo> ..\text.zo3\frung.txt
..\gmasmz fs32 ..\test.zo3\fs32.txo -lo> ..\text.zo3\fs32.txt
..\gmasmz fs48 ..\test.zo3\fs48.txo -lo> ..\text.zo3\fs48.txt
..\gmasmz further ..\test.zo3\further.txo -lo> ..\text.zo3\further.txt
..\gmasmz fzero ..\test.zo3\fzero.txo -lo> ..\text.zo3\fzero.txt
..\gmasmz general ..\test.zo3\general.txo -lo> ..\text.zo3\general.txt
..\gmasmz gfactor ..\test.zo3\gfactor.txo -lo> ..\text.zo3\gfactor.txt
..\gmasmz gfar ..\test.zo3\gfar.txo -lo> ..\text.zo3\gfar.txt
..\gmasmz gframe2 ..\test.zo3\gframe2.txo -lo> ..\text.zo3\gframe2.txt
..\gmasmz gfurther ..\test.zo3\gfurther.txo -lo> ..\text.zo3\gfurther.txt
..\gmasmz goodbit ..\test.zo3\goodbit.txo -lo> ..\text.zo3\goodbit.txt
..\gmasmz gram ..\test.zo3\gram.txo -lo> ..\text.zo3\gram.txt
..\gmasmz gross ..\test.zo3\gross.txo -lo> ..\text.zo3\gross.txt
..\gmasmz grum ..\test.zo3\grum.txo -lo> ..\text.zo3\grum.txt
..\gmasmz gscale22 ..\test.zo3\gscale22.txo -lo> ..\text.zo3\gscale22.txt
..\gmasmz gscale23 ..\test.zo3\gscale23.txo -lo> ..\text.zo3\gscale23.txt
..\gmasmz gscale24 ..\test.zo3\gscale24.txo -lo> ..\text.zo3\gscale24.txt
..\gmasmz gsoso ..\test.zo3\gsoso.txo -lo> ..\text.zo3\gsoso.txt
..\gmasmz gworser ..\test.zo3\gworser.txo -lo> ..\text.zo3\gworser.txt
..\gmasmz gwyllmp ..\test.zo3\gwyllmp.txo -lo> ..\text.zo3\gwyllmp.txt
..\gmasmz gzactor ..\test.zo3\gzactor.txo -lo> ..\text.zo3\gzactor.txt
..\gmasmz haive ..\test.zo3\haive.txo -lo> ..\text.zo3\haive.txt
..\gmasmz handfull ..\test.zo3\handfull.txo -lo> ..\text.zo3\handfull.txt
..\gmasmz hangobar ..\test.zo3\hangobar.txo -lo> ..\text.zo3\hangobar.txt
..\gmasmz high ..\test.zo3\high.txo -lo> ..\text.zo3\high.txt
..\gmasmz howmany ..\test.zo3\howmany.txo -lo> ..\text.zo3\howmany.txt
..\gmasmz hwis ..\test.zo3\hwis.txo -lo> ..\text.zo3\hwis.txt
..\gmasmz ican ..\test.zo3\ican.txo -lo> ..\text.zo3\ican.txt
..\gmasmz ieee754 ..\test.zo3\ieee754.txo -lo> ..\text.zo3\ieee754.txt
..\gmasmz ieee754s ..\test.zo3\ieee754s.txo -lo> ..\text.zo3\ieee754s.txt
..\gmasmz ifp ..\test.zo3\ifp.txo -lo> ..\text.zo3\ifp.txt
..\gmasmz iii ..\test.zo3\iii.txo -lo> ..\text.zo3\iii.txt
..\gmasmz info ..\test.zo3\info.txo -lo> ..\text.zo3\info.txt
..\gmasmz inside ..\test.zo3\inside.txo -lo> ..\text.zo3\inside.txt
..\gmasmz intrepid ..\test.zo3\intrepid.txo -lo> ..\text.zo3\intrepid.txt
..\gmasmz intune ..\test.zo3\intune.txo -lo> ..\text.zo3\intune.txt
..\gmasmz iscale1 ..\test.zo3\iscale1.txo -lo> ..\text.zo3\iscale1.txt
..\gmasmz iscale2 ..\test.zo3\iscale2.txo -lo> ..\text.zo3\iscale2.txt
..\gmasmz iscale3 ..\test.zo3\iscale3.txo -lo> ..\text.zo3\iscale3.txt
..\gmasmz iside1 ..\test.zo3\iside1.txo -lo> ..\text.zo3\iside1.txt
..\gmasmz isobar ..\test.zo3\isobar.txo -lo> ..\text.zo3\isobar.txt
..\gmasmz isobar1 ..\test.zo3\isobar1.txo -lo> ..\text.zo3\isobar1.txt
..\gmasmz isthatso ..\test.zo3\isthatso.txo -lo> ..\text.zo3\isthatso.txt
..\gmasmz j3 ..\test.zo3\j3.txo -lo> ..\text.zo3\j3.txt
..\gmasmz justname ..\test.zo3\justname.txo -lo> ..\text.zo3\justname.txt
..\gmasmz keeptry ..\test.zo3\keeptry.txo -lo> ..\text.zo3\keeptry.txt
..\gmasmz kette ..\test.zo3\kette.txo -lo> ..\text.zo3\kette.txt
..\gmasmz l ..\test.zo3\l.txo -lo> ..\text.zo3\l.txt
..\gmasmz langobar ..\test.zo3\langobar.txo -lo> ..\text.zo3\langobar.txt
..\gmasmz largle ..\test.zo3\largle.txo -lo> ..\text.zo3\largle.txt
..\gmasmz lcodes ..\test.zo3\lcodes.txo -lo> ..\text.zo3\lcodes.txt
..\gmasmz letsbya ..\test.zo3\letsbya.txo -lo> ..\text.zo3\letsbya.txt
..\gmasmz linitup ..\test.zo3\linitup.txo -lo> ..\text.zo3\linitup.txt
..\gmasmz lit ..\test.zo3\lit.txo -lo> ..\text.zo3\lit.txt
..\gmasmz lit8051 ..\test.zo3\lit8051.txo -lo> ..\text.zo3\lit8051.txt
..\gmasmz little ..\test.zo3\little.txo -lo> ..\text.zo3\little.txt
..\gmasmz ll3 ..\test.zo3\ll3.txo -lo> ..\text.zo3\ll3.txt
..\gmasmz ll4 ..\test.zo3\ll4.txo -lo> ..\text.zo3\ll4.txt
..\gmasmz ll5 ..\test.zo3\ll5.txo -lo> ..\text.zo3\ll5.txt
..\gmasmz ll5abs ..\test.zo3\ll5abs.txo -lo> ..\text.zo3\ll5abs.txt
..\gmasmz ll6 ..\test.zo3\ll6.txo -lo> ..\text.zo3\ll6.txt
..\gmasmz ll6abs ..\test.zo3\ll6abs.txo -lo> ..\text.zo3\ll6abs.txt
..\gmasmz lodation ..\test.zo3\lodation.txo -lo> ..\text.zo3\lodation.txt
..\gmasmz longjump ..\test.zo3\longjump.txo -lo> ..\text.zo3\longjump.txt
..\gmasmz loopy ..\test.zo3\loopy.txo -lo> ..\text.zo3\loopy.txt
..\gmasmz lorg ..\test.zo3\lorg.txo -lo> ..\text.zo3\lorg.txt
..\gmasmz lorgle ..\test.zo3\lorgle.txo -lo> ..\text.zo3\lorgle.txt
..\gmasmz m ..\test.zo3\m.txo -lo> ..\text.zo3\m.txt
..\gmasmz mangle ..\test.zo3\mangle.txo -lo> ..\text.zo3\mangle.txt
..\gmasmz manif ..\test.zo3\manif.txo -lo> ..\text.zo3\manif.txt
..\gmasmz many ..\test.zo3\many.txo -lo> ..\text.zo3\many.txt
..\gmasmz map ..\test.zo3\map.txo -lo> ..\text.zo3\map.txt
..\gmasmz map1 ..\test.zo3\map1.txo -lo> ..\text.zo3\map1.txt
..\gmasmz map10 ..\test.zo3\map10.txo -lo> ..\text.zo3\map10.txt
..\gmasmz map11 ..\test.zo3\map11.txo -lo> ..\text.zo3\map11.txt
..\gmasmz map12 ..\test.zo3\map12.txo -lo> ..\text.zo3\map12.txt
..\gmasmz map15 ..\test.zo3\map15.txo -lo> ..\text.zo3\map15.txt
..\gmasmz map2 ..\test.zo3\map2.txo -lo> ..\text.zo3\map2.txt
..\gmasmz map3 ..\test.zo3\map3.txo -lo> ..\text.zo3\map3.txt
..\gmasmz map4 ..\test.zo3\map4.txo -lo> ..\text.zo3\map4.txt
..\gmasmz map5 ..\test.zo3\map5.txo -lo> ..\text.zo3\map5.txt
..\gmasmz map6 ..\test.zo3\map6.txo -lo> ..\text.zo3\map6.txt
..\gmasmz map7 ..\test.zo3\map7.txo -lo> ..\text.zo3\map7.txt
..\gmasmz map7g ..\test.zo3\map7g.txo -lo> ..\text.zo3\map7g.txt
..\gmasmz map8 ..\test.zo3\map8.txo -lo> ..\text.zo3\map8.txt
..\gmasmz map9 ..\test.zo3\map9.txo -lo> ..\text.zo3\map9.txt
..\gmasmz mary ..\test.zo3\mary.txo -lo> ..\text.zo3\mary.txt
..\gmasmz maxfloat ..\test.zo3\maxfloat.txo -lo> ..\text.zo3\maxfloat.txt
..\gmasmz maxmaxi ..\test.zo3\maxmaxi.txo -lo> ..\text.zo3\maxmaxi.txt
..\gmasmz mbank ..\test.zo3\mbank.txo -lo> ..\text.zo3\mbank.txt
..\gmasmz mbank1 ..\test.zo3\mbank1.txo -lo> ..\text.zo3\mbank1.txt
..\gmasmz ml ..\test.zo3\ml.txo -lo> ..\text.zo3\ml.txt
..\gmasmz mlingba ..\test.zo3\mlingba.txo -lo> ..\text.zo3\mlingba.txt
..\gmasmz modest ..\test.zo3\modest.txo -lo> ..\text.zo3\modest.txt
..\gmasmz mojo ..\test.zo3\mojo.txo -lo> ..\text.zo3\mojo.txt
..\gmasmz mouli ..\test.zo3\mouli.txo -lo> ..\text.zo3\mouli.txt
..\gmasmz movem ..\test.zo3\movem.txo -lo> ..\text.zo3\movem.txt
..\gmasmz multest ..\test.zo3\multest.txo -lo> ..\text.zo3\multest.txt
..\gmasmz multitr ..\test.zo3\multitr.txo -lo> ..\text.zo3\multitr.txt
..\gmasmz mungle ..\test.zo3\mungle.txo -lo> ..\text.zo3\mungle.txt
..\gmasmz names ..\test.zo3\names.txo -lo> ..\text.zo3\names.txt
..\gmasmz nang ..\test.zo3\nang.txo -lo> ..\text.zo3\nang.txt
..\gmasmz needle ..\test.zo3\needle.txo -lo> ..\text.zo3\needle.txt
..\gmasmz nest ..\test.zo3\nest.txo -lo> ..\text.zo3\nest.txt
..\gmasmz netbio ..\test.zo3\netbio.txo -lo> ..\text.zo3\netbio.txt
..\gmasmz netvalue ..\test.zo3\netvalue.txo -lo> ..\text.zo3\netvalue.txt
..\gmasmz new ..\test.zo3\new.txo -lo> ..\text.zo3\new.txt
..\gmasmz newby ..\test.zo3\newby.txo -lo> ..\text.zo3\newby.txt
..\gmasmz norkette ..\test.zo3\norkette.txo -lo> ..\text.zo3\norkette.txt
..\gmasmz nosedive ..\test.zo3\nosedive.txo -lo> ..\text.zo3\nosedive.txt
..\gmasmz noso ..\test.zo3\noso.txo -lo> ..\text.zo3\noso.txt
..\gmasmz notmany ..\test.zo3\notmany.txo -lo> ..\text.zo3\notmany.txt
..\gmasmz notso ..\test.zo3\notso.txo -lo> ..\text.zo3\notso.txt
..\gmasmz ocycle ..\test.zo3\ocycle.txo -lo> ..\text.zo3\ocycle.txt
..\gmasmz oddly ..\test.zo3\oddly.txo -lo> ..\text.zo3\oddly.txt
..\gmasmz offset ..\test.zo3\offset.txo -lo> ..\text.zo3\offset.txt
..\gmasmz ok1 ..\test.zo3\ok1.txo -lo> ..\text.zo3\ok1.txt
..\gmasmz one ..\test.zo3\one.txo -lo> ..\text.zo3\one.txt
..\gmasmz onetwo ..\test.zo3\onetwo.txo -lo> ..\text.zo3\onetwo.txt
..\gmasmz oreally ..\test.zo3\oreally.txo -lo> ..\text.zo3\oreally.txt
..\gmasmz orgalign ..\test.zo3\orgalign.txo -lo> ..\text.zo3\orgalign.txt
..\gmasmz otherwis ..\test.zo3\otherwis.txo -lo> ..\text.zo3\otherwis.txt
..\gmasmz outrage ..\test.zo3\outrage.txo -lo> ..\text.zo3\outrage.txt
..\gmasmz outside ..\test.zo3\outside.txo -lo> ..\text.zo3\outside.txt
..\gmasmz overlaid ..\test.zo3\overlaid.txo -lo> ..\text.zo3\overlaid.txt
..\gmasmz overlay ..\test.zo3\overlay.txo -lo> ..\text.zo3\overlay.txt
..\gmasmz p ..\test.zo3\p.txo -lo> ..\text.zo3\p.txt
..\gmasmz packem ..\test.zo3\packem.txo -lo> ..\text.zo3\packem.txt
..\gmasmz paraform ..\test.zo3\paraform.txo -lo> ..\text.zo3\paraform.txt
..\gmasmz param ..\test.zo3\param.txo -lo> ..\text.zo3\param.txt
..\gmasmz paren ..\test.zo3\paren.txo -lo> ..\text.zo3\paren.txt
..\gmasmz passes ..\test.zo3\passes.txo -lo> ..\text.zo3\passes.txt
..\gmasmz passive ..\test.zo3\passive.txo -lo> ..\text.zo3\passive.txt
..\gmasmz perform ..\test.zo3\perform.txo -lo> ..\text.zo3\perform.txt
..\gmasmz plain ..\test.zo3\plain.txo -lo> ..\text.zo3\plain.txt
..\gmasmz plank ..\test.zo3\plank.txo -lo> ..\text.zo3\plank.txt
..\gmasmz plobbo ..\test.zo3\plobbo.txo -lo> ..\text.zo3\plobbo.txt
..\gmasmz ppc1 ..\test.zo3\ppc1.txo -lo> ..\text.zo3\ppc1.txt
..\gmasmz ppcsinga ..\test.zo3\ppcsinga.txo -lo> ..\text.zo3\ppcsinga.txt
..\gmasmz ppcsingb ..\test.zo3\ppcsingb.txo -lo> ..\text.zo3\ppcsingb.txt
..\gmasmz ppcsingr ..\test.zo3\ppcsingr.txo -lo> ..\text.zo3\ppcsingr.txt
..\gmasmz ppcuvast ..\test.zo3\ppcuvast.txo -lo> ..\text.zo3\ppcuvast.txt
..\gmasmz pratisla ..\test.zo3\pratisla.txo -lo> ..\text.zo3\pratisla.txt
..\gmasmz predikat ..\test.zo3\predikat.txo -lo> ..\text.zo3\predikat.txt
..\gmasmz proceds ..\test.zo3\proceds.txo -lo> ..\text.zo3\proceds.txt
..\gmasmz proxy ..\test.zo3\proxy.txo -lo> ..\text.zo3\proxy.txt
..\gmasmz ptup ..\test.zo3\ptup.txo -lo> ..\text.zo3\ptup.txt
..\gmasmz pusingv ..\test.zo3\pusingv.txo -lo> ..\text.zo3\pusingv.txt
..\gmasmz pvusinga ..\test.zo3\pvusinga.txo -lo> ..\text.zo3\pvusinga.txt
..\gmasmz pzero ..\test.zo3\pzero.txo -lo> ..\text.zo3\pzero.txt
..\gmasmz q1 ..\test.zo3\q1.txo -lo> ..\text.zo3\q1.txt
..\gmasmz qati ..\test.zo3\qati.txo -lo> ..\text.zo3\qati.txt
..\gmasmz qbig ..\test.zo3\qbig.txo -lo> ..\text.zo3\qbig.txt
..\gmasmz qf ..\test.zo3\qf.txo -lo> ..\text.zo3\qf.txt
..\gmasmz qflic ..\test.zo3\qflic.txo -lo> ..\text.zo3\qflic.txt
..\gmasmz qpart ..\test.zo3\qpart.txo -lo> ..\text.zo3\qpart.txt
..\gmasmz qplain ..\test.zo3\qplain.txo -lo> ..\text.zo3\qplain.txt
..\gmasmz qt ..\test.zo3\qt.txo -lo> ..\text.zo3\qt.txt
..\gmasmz quidgeo ..\test.zo3\quidgeo.txo -lo> ..\text.zo3\quidgeo.txt
..\gmasmz quitebad ..\test.zo3\quitebad.txo -lo> ..\text.zo3\quitebad.txt
..\gmasmz quo ..\test.zo3\quo.txo -lo> ..\text.zo3\quo.txt
..\gmasmz quo1 ..\test.zo3\quo1.txo -lo> ..\text.zo3\quo1.txt
..\gmasmz quo2 ..\test.zo3\quo2.txo -lo> ..\text.zo3\quo2.txt
..\gmasmz quo3 ..\test.zo3\quo3.txo -lo> ..\text.zo3\quo3.txt
..\gmasmz quo4 ..\test.zo3\quo4.txo -lo> ..\text.zo3\quo4.txt
..\gmasmz quo5 ..\test.zo3\quo5.txo -lo> ..\text.zo3\quo5.txt
..\gmasmz r ..\test.zo3\r.txo -lo> ..\text.zo3\r.txt
..\gmasmz r_u_rel ..\test.zo3\r_u_rel.txo -lo> ..\text.zo3\r_u_rel.txt
..\gmasmz radalupu ..\test.zo3\radalupu.txo -lo> ..\text.zo3\radalupu.txt
..\gmasmz really ..\test.zo3\really.txo -lo> ..\text.zo3\really.txt
..\gmasmz reco ..\test.zo3\reco.txo -lo> ..\text.zo3\reco.txt
..\gmasmz recurs ..\test.zo3\recurs.txo -lo> ..\text.zo3\recurs.txt
..\gmasmz relj ..\test.zo3\relj.txo -lo> ..\text.zo3\relj.txt
..\gmasmz relja ..\test.zo3\relja.txo -lo> ..\text.zo3\relja.txt
..\gmasmz relstack ..\test.zo3\relstack.txo -lo> ..\text.zo3\relstack.txt
..\gmasmz rempack ..\test.zo3\rempack.txo -lo> ..\text.zo3\rempack.txt
..\gmasmz rempart ..\test.zo3\rempart.txo -lo> ..\text.zo3\rempart.txt
..\gmasmz rename ..\test.zo3\rename.txo -lo> ..\text.zo3\rename.txt
..\gmasmz rep ..\test.zo3\rep.txo -lo> ..\text.zo3\rep.txt
..\gmasmz res ..\test.zo3\res.txo -lo> ..\text.zo3\res.txt
..\gmasmz risobar ..\test.zo3\risobar.txo -lo> ..\text.zo3\risobar.txt
..\gmasmz rough ..\test.zo3\rough.txo -lo> ..\text.zo3\rough.txt
..\gmasmz roundelay ..\test.zo3\roundelay.txo -lo> ..\text.zo3\roundelay.txt
..\gmasmz rplain ..\test.zo3\rplain.txo -lo> ..\text.zo3\rplain.txt
..\gmasmz rumad ..\test.zo3\rumad.txo -lo> ..\text.zo3\rumad.txt
..\gmasmz ryatha ..\test.zo3\ryatha.txo -lo> ..\text.zo3\ryatha.txt
..\gmasmz sample ..\test.zo3\sample.txo -lo> ..\text.zo3\sample.txt
..\gmasmz sample2 ..\test.zo3\sample2.txo -lo> ..\text.zo3\sample2.txt
..\gmasmz scabrous ..\test.zo3\scabrous.txo -lo> ..\text.zo3\scabrous.txt
..\gmasmz scale ..\test.zo3\scale.txo -lo> ..\text.zo3\scale.txt
..\gmasmz scale1 ..\test.zo3\scale1.txo -lo> ..\text.zo3\scale1.txt
..\gmasmz scale2 ..\test.zo3\scale2.txo -lo> ..\text.zo3\scale2.txt
..\gmasmz scale22 ..\test.zo3\scale22.txo -lo> ..\text.zo3\scale22.txt
..\gmasmz scale23 ..\test.zo3\scale23.txo -lo> ..\text.zo3\scale23.txt
..\gmasmz scale24 ..\test.zo3\scale24.txo -lo> ..\text.zo3\scale24.txt
..\gmasmz scale3 ..\test.zo3\scale3.txo -lo> ..\text.zo3\scale3.txt
..\gmasmz scale4 ..\test.zo3\scale4.txo -lo> ..\text.zo3\scale4.txt
..\gmasmz scale5 ..\test.zo3\scale5.txo -lo> ..\text.zo3\scale5.txt
..\gmasmz scale6 ..\test.zo3\scale6.txo -lo> ..\text.zo3\scale6.txt
..\gmasmz scale8 ..\test.zo3\scale8.txo -lo> ..\text.zo3\scale8.txt
..\gmasmz scally2 ..\test.zo3\scally2.txo -lo> ..\text.zo3\scally2.txt
..\gmasmz scally3 ..\test.zo3\scally3.txo -lo> ..\text.zo3\scally3.txt
..\gmasmz scally4 ..\test.zo3\scally4.txo -lo> ..\text.zo3\scally4.txt
..\gmasmz scandal ..\test.zo3\scandal.txo -lo> ..\text.zo3\scandal.txt
..\gmasmz scrabble ..\test.zo3\scrabble.txo -lo> ..\text.zo3\scrabble.txt
..\gmasmz see2it ..\test.zo3\see2it.txo -lo> ..\text.zo3\see2it.txt
..\gmasmz seomac ..\test.zo3\seomac.txo -lo> ..\text.zo3\seomac.txt
..\gmasmz set ..\test.zo3\set.txo -lo> ..\text.zo3\set.txt
..\gmasmz shifty ..\test.zo3\shifty.txo -lo> ..\text.zo3\shifty.txt
..\gmasmz sim ..\test.zo3\sim.txo -lo> ..\text.zo3\sim.txt
..\gmasmz similar ..\test.zo3\similar.txo -lo> ..\text.zo3\similar.txt
..\gmasmz simple ..\test.zo3\simple.txo -lo> ..\text.zo3\simple.txt
..\gmasmz simpler ..\test.zo3\simpler.txo -lo> ..\text.zo3\simpler.txt
..\gmasmz simplify ..\test.zo3\simplify.txo -lo> ..\text.zo3\simplify.txt
..\gmasmz sky ..\test.zo3\sky.txo -lo> ..\text.zo3\sky.txt
..\gmasmz sleunig ..\test.zo3\sleunig.txo -lo> ..\text.zo3\sleunig.txt
..\gmasmz slingba ..\test.zo3\slingba.txo -lo> ..\text.zo3\slingba.txt
..\gmasmz slipcan ..\test.zo3\slipcan.txo -lo> ..\text.zo3\slipcan.txt
..\gmasmz slipshod ..\test.zo3\slipshod.txo -lo> ..\text.zo3\slipshod.txt
..\gmasmz smaragd ..\test.zo3\smaragd.txo -lo> ..\text.zo3\smaragd.txt
..\gmasmz smaragd1 ..\test.zo3\smaragd1.txo -lo> ..\text.zo3\smaragd1.txt
..\gmasmz smaragd7 ..\test.zo3\smaragd7.txo -lo> ..\text.zo3\smaragd7.txt
..\gmasmz snappie ..\test.zo3\snappie.txo -lo> ..\text.zo3\snappie.txt
..\gmasmz snippie ..\test.zo3\snippie.txo -lo> ..\text.zo3\snippie.txt
..\gmasmz somestuf ..\test.zo3\somestuf.txo -lo> ..\text.zo3\somestuf.txt
..\gmasmz somular ..\test.zo3\somular.txo -lo> ..\text.zo3\somular.txt
..\gmasmz soso ..\test.zo3\soso.txo -lo> ..\text.zo3\soso.txt
..\gmasmz spitz ..\test.zo3\spitz.txo -lo> ..\text.zo3\spitz.txt
..\gmasmz splativo ..\test.zo3\splativo.txo -lo> ..\text.zo3\splativo.txt
..\gmasmz sprativo ..\test.zo3\sprativo.txo -lo> ..\text.zo3\sprativo.txt
..\gmasmz squeeze ..\test.zo3\squeeze.txo -lo> ..\text.zo3\squeeze.txt
..\gmasmz stack ..\test.zo3\stack.txo -lo> ..\text.zo3\stack.txt
..\gmasmz stcomple ..\test.zo3\stcomple.txo -lo> ..\text.zo3\stcomple.txt
..\gmasmz steamer ..\test.zo3\steamer.txo -lo> ..\text.zo3\steamer.txt
..\gmasmz step1 ..\test.zo3\step1.txo -lo> ..\text.zo3\step1.txt
..\gmasmz step2 ..\test.zo3\step2.txo -lo> ..\text.zo3\step2.txt
..\gmasmz sterm ..\test.zo3\sterm.txo -lo> ..\text.zo3\sterm.txt
..\gmasmz strahl ..\test.zo3\strahl.txo -lo> ..\text.zo3\strahl.txt
..\gmasmz strain ..\test.zo3\strain.txo -lo> ..\text.zo3\strain.txt
..\gmasmz straling ..\test.zo3\straling.txo -lo> ..\text.zo3\straling.txt
..\gmasmz strange ..\test.zo3\strange.txo -lo> ..\text.zo3\strange.txt
..\gmasmz strial1 ..\test.zo3\strial1.txo -lo> ..\text.zo3\strial1.txt
..\gmasmz strial2 ..\test.zo3\strial2.txo -lo> ..\text.zo3\strial2.txt
..\gmasmz strial3 ..\test.zo3\strial3.txo -lo> ..\text.zo3\strial3.txt
..\gmasmz strial4 ..\test.zo3\strial4.txo -lo> ..\text.zo3\strial4.txt
..\gmasmz strial5 ..\test.zo3\strial5.txo -lo> ..\text.zo3\strial5.txt
..\gmasmz strial6 ..\test.zo3\strial6.txo -lo> ..\text.zo3\strial6.txt
..\gmasmz stringli ..\test.zo3\stringli.txo -lo> ..\text.zo3\stringli.txt
..\gmasmz strugl5 ..\test.zo3\strugl5.txo -lo> ..\text.zo3\strugl5.txt
..\gmasmz stsimple ..\test.zo3\stsimple.txo -lo> ..\text.zo3\stsimple.txt
..\gmasmz stt ..\test.zo3\stt.txo -lo> ..\text.zo3\stt.txt
..\gmasmz subfi ..\test.zo3\subfi.txo -lo> ..\text.zo3\subfi.txt
..\gmasmz submarine ..\test.zo3\submarine.txo -lo> ..\text.zo3\submarine.txt
..\gmasmz subs1 ..\test.zo3\subs1.txo -lo> ..\text.zo3\subs1.txt
..\gmasmz suppose ..\test.zo3\suppose.txo -lo> ..\text.zo3\suppose.txt
..\gmasmz synonyms ..\test.zo3\synonyms.txo -lo> ..\text.zo3\synonyms.txt
..\gmasmz sysgo ..\test.zo3\sysgo.txo -lo> ..\text.zo3\sysgo.txt
..\gmasmz table ..\test.zo3\table.txo -lo> ..\text.zo3\table.txt
..\gmasmz tally2 ..\test.zo3\tally2.txo -lo> ..\text.zo3\tally2.txt
..\gmasmz tally3 ..\test.zo3\tally3.txo -lo> ..\text.zo3\tally3.txt
..\gmasmz tally4 ..\test.zo3\tally4.txo -lo> ..\text.zo3\tally4.txt
..\gmasmz tarsub ..\test.zo3\tarsub.txo -lo> ..\text.zo3\tarsub.txt
..\gmasmz tcp_in ..\test.zo3\tcp_in.txo -lo> ..\text.zo3\tcp_in.txt
..\gmasmz temp ..\test.zo3\temp.txo -lo> ..\text.zo3\temp.txt
..\gmasmz temper ..\test.zo3\temper.txo -lo> ..\text.zo3\temper.txt
..\gmasmz tempo ..\test.zo3\tempo.txo -lo> ..\text.zo3\tempo.txt
..\gmasmz term ..\test.zo3\term.txo -lo> ..\text.zo3\term.txt
..\gmasmz terrify1 ..\test.zo3\terrify1.txo -lo> ..\text.zo3\terrify1.txt
..\gmasmz terrify2 ..\test.zo3\terrify2.txo -lo> ..\text.zo3\terrify2.txt
..\gmasmz terrify3 ..\test.zo3\terrify3.txo -lo> ..\text.zo3\terrify3.txt
..\gmasmz these ..\test.zo3\these.txo -lo> ..\text.zo3\these.txt
..\gmasmz thing ..\test.zo3\thing.txo -lo> ..\text.zo3\thing.txt
..\gmasmz three4 ..\test.zo3\three4.txo -lo> ..\text.zo3\three4.txt
..\gmasmz thru ..\test.zo3\thru.txo -lo> ..\text.zo3\thru.txt
..\gmasmz times ..\test.zo3\times.txo -lo> ..\text.zo3\times.txt
..\gmasmz tisobar ..\test.zo3\tisobar.txo -lo> ..\text.zo3\tisobar.txt
..\gmasmz tla ..\test.zo3\tla.txo -lo> ..\text.zo3\tla.txt
..\gmasmz together ..\test.zo3\together.txo -lo> ..\text.zo3\together.txt
..\gmasmz tomp ..\test.zo3\tomp.txo -lo> ..\text.zo3\tomp.txt
..\gmasmz toozl ..\test.zo3\toozl.txo -lo> ..\text.zo3\toozl.txt
..\gmasmz trail ..\test.zo3\trail.txo -lo> ..\text.zo3\trail.txt
..\gmasmz trait ..\test.zo3\trait.txo -lo> ..\text.zo3\trait.txt
..\gmasmz trangle ..\test.zo3\trangle.txo -lo> ..\text.zo3\trangle.txt
..\gmasmz transport ..\test.zo3\transport.txo -lo> ..\text.zo3\transport.txt
..\gmasmz tranwys ..\test.zo3\tranwys.txo -lo> ..\text.zo3\tranwys.txt
..\gmasmz trau ..\test.zo3\trau.txo -lo> ..\text.zo3\trau.txt
..\gmasmz trbyte ..\test.zo3\trbyte.txo -lo> ..\text.zo3\trbyte.txt
..\gmasmz tree ..\test.zo3\tree.txo -lo> ..\text.zo3\tree.txt
..\gmasmz trees ..\test.zo3\trees.txo -lo> ..\text.zo3\trees.txt
..\gmasmz tribit ..\test.zo3\tribit.txo -lo> ..\text.zo3\tribit.txt
..\gmasmz tricki ..\test.zo3\tricki.txo -lo> ..\text.zo3\tricki.txt
..\gmasmz trinsic ..\test.zo3\trinsic.txo -lo> ..\text.zo3\trinsic.txt
..\gmasmz trip ..\test.zo3\trip.txo -lo> ..\text.zo3\trip.txt
..\gmasmz trivs ..\test.zo3\trivs.txo -lo> ..\text.zo3\trivs.txt
..\gmasmz trtab ..\test.zo3\trtab.txo -lo> ..\text.zo3\trtab.txt
..\gmasmz tryafew ..\test.zo3\tryafew.txo -lo> ..\text.zo3\tryafew.txt
..\gmasmz trysome ..\test.zo3\trysome.txo -lo> ..\text.zo3\trysome.txt
..\gmasmz tump ..\test.zo3\tump.txo -lo> ..\text.zo3\tump.txt
..\gmasmz tumpoon ..\test.zo3\tumpoon.txo -lo> ..\text.zo3\tumpoon.txt
..\gmasmz tumpshie ..\test.zo3\tumpshie.txo -lo> ..\text.zo3\tumpshie.txt
..\gmasmz twiggy ..\test.zo3\twiggy.txo -lo> ..\text.zo3\twiggy.txt
..\gmasmz tz ..\test.zo3\tz.txo -lo> ..\text.zo3\tz.txt
..\gmasmz uart ..\test.zo3\uart.txo -lo> ..\text.zo3\uart.txt
..\gmasmz udp_rxip ..\test.zo3\udp_rxip.txo -lo> ..\text.zo3\udp_rxip.txt
..\gmasmz updown ..\test.zo3\updown.txo -lo> ..\text.zo3\updown.txt
..\gmasmz using ..\test.zo3\using.txo -lo> ..\text.zo3\using.txt
..\gmasmz usinga ..\test.zo3\usinga.txo -lo> ..\text.zo3\usinga.txt
..\gmasmz usingb ..\test.zo3\usingb.txo -lo> ..\text.zo3\usingb.txt
..\gmasmz usingl ..\test.zo3\usingl.txo -lo> ..\text.zo3\usingl.txt
..\gmasmz usingpv ..\test.zo3\usingpv.txo -lo> ..\text.zo3\usingpv.txt
..\gmasmz usingr ..\test.zo3\usingr.txo -lo> ..\text.zo3\usingr.txt
..\gmasmz usingv ..\test.zo3\usingv.txo -lo> ..\text.zo3\usingv.txt
..\gmasmz utable ..\test.zo3\utable.txo -lo> ..\text.zo3\utable.txt
..\gmasmz uzactor ..\test.zo3\uzactor.txo -lo> ..\text.zo3\uzactor.txt
..\gmasmz v ..\test.zo3\v.txo -lo> ..\text.zo3\v.txt
..\gmasmz var ..\test.zo3\var.txo -lo> ..\text.zo3\var.txt
..\gmasmz vast ..\test.zo3\vast.txo -lo> ..\text.zo3\vast.txt
..\gmasmz vector ..\test.zo3\vector.txo -lo> ..\text.zo3\vector.txt
..\gmasmz viable ..\test.zo3\viable.txo -lo> ..\text.zo3\viable.txt
..\gmasmz victim ..\test.zo3\victim.txo -lo> ..\text.zo3\victim.txt
..\gmasmz visobar ..\test.zo3\visobar.txo -lo> ..\text.zo3\visobar.txt
..\gmasmz vitest ..\test.zo3\vitest.txo -lo> ..\text.zo3\vitest.txt
..\gmasmz vitest2 ..\test.zo3\vitest2.txo -lo> ..\text.zo3\vitest2.txt
..\gmasmz vitest3 ..\test.zo3\vitest3.txo -lo> ..\text.zo3\vitest3.txt
..\gmasmz void ..\test.zo3\void.txo -lo> ..\text.zo3\void.txt
..\gmasmz vr ..\test.zo3\vr.txo -lo> ..\text.zo3\vr.txt
..\gmasmz vsimpl ..\test.zo3\vsimpl.txo -lo> ..\text.zo3\vsimpl.txt
..\gmasmz vsimpl2 ..\test.zo3\vsimpl2.txo -lo> ..\text.zo3\vsimpl2.txt
..\gmasmz vspace ..\test.zo3\vspace.txo -lo> ..\text.zo3\vspace.txt
..\gmasmz wanayooz ..\test.zo3\wanayooz.txo -lo> ..\text.zo3\wanayooz.txt
..\gmasmz watabout ..\test.zo3\watabout.txo -lo> ..\text.zo3\watabout.txt
..\gmasmz watslong ..\test.zo3\watslong.txo -lo> ..\text.zo3\watslong.txt
..\gmasmz weel ..\test.zo3\weel.txo -lo> ..\text.zo3\weel.txt
..\gmasmz welblech ..\test.zo3\welblech.txo -lo> ..\text.zo3\welblech.txt
..\gmasmz wellaugh ..\test.zo3\wellaugh.txo -lo> ..\text.zo3\wellaugh.txt
..\gmasmz wellfest ..\test.zo3\wellfest.txo -lo> ..\text.zo3\wellfest.txt
..\gmasmz why ..\test.zo3\why.txo -lo> ..\text.zo3\why.txt
..\gmasmz wibl ..\test.zo3\wibl.txo -lo> ..\text.zo3\wibl.txt
..\gmasmz wolverine ..\test.zo3\wolverine.txo -lo> ..\text.zo3\wolverine.txt
..\gmasmz woodbits ..\test.zo3\woodbits.txo -lo> ..\text.zo3\woodbits.txt
..\gmasmz worser ..\test.zo3\worser.txo -lo> ..\text.zo3\worser.txt
..\gmasmz wozita ..\test.zo3\wozita.txo -lo> ..\text.zo3\wozita.txt
..\gmasmz wyzat ..\test.zo3\wyzat.txo -lo> ..\text.zo3\wyzat.txt
..\gmasmz xtrem ..\test.zo3\xtrem.txo -lo> ..\text.zo3\xtrem.txt
..\gmasmz yanutha ..\test.zo3\yanutha.txo -lo> ..\text.zo3\yanutha.txt
..\gmasmz yoho ..\test.zo3\yoho.txo -lo> ..\text.zo3\yoho.txt
..\gmasmz yowl ..\test.zo3\yowl.txo -lo> ..\text.zo3\yowl.txt
..\gmasmz ytup ..\test.zo3\ytup.txo -lo> ..\text.zo3\ytup.txt
..\gmasmz zactor ..\test.zo3\zactor.txo -lo> ..\text.zo3\zactor.txt
..\gmasmz zibble ..\test.zo3\zibble.txo -lo> ..\text.zo3\zibble.txt
..\gmasmz zoto ..\test.zo3\zoto.txo -lo> ..\text.zo3\zoto.txt
..\gmasmz ztup ..\test.zo3\ztup.txo -lo> ..\text.zo3\ztup.txt
..\gmasmz alyat ..\test.zo3\alyat.txo -lo > ..\text.zo3\alyat.txt
..\gmasmz continu ..\test.zo3\continu.txo -lo > ..\text.zo3\continu.txt
..\gmasmz gap ..\test.zo3\gap.txo -lo > ..\text.zo3\gap.txt
..\gmasmz mikros ..\test.zo3\mikros.txo -lo > ..\text.zo3\mikros.txt
..\gmasmz blanquo ..\test.zo3\blanquo.txo -lo > ..\text.zo3\blanquo.txt
..\gmasmz cc ..\test.zo3\cc.txo -lo > ..\text.zo3\cc.txt
..\gmasmz strangely ..\test.zo3\strangely.txo -lo > ..\text.zo3\strangely.txt
..\gmasmz stretch ..\test.zo3\stretch.txo -lo > ..\text.zo3\stretch.txt
..\gmasmz wirr ..\test.zo3\wirr.txo -lo > ..\text.zo3\wirr.txt
..\gmasmz keyword ..\test.zo3\keyword.txo -lo > ..\text.zo3\keyword.txt

..\gmasmz hinge ..\test.zo3\hinge.txo -loy > ..\text.zo3\hinge.txt
..\gmasmz hubert ..\test.zo3\hubert.txo -loy > ..\text.zo3\hubert.txt
..\gmasmz prango ..\test.zo3\prango.txo -loy > ..\text.zo3\prango.txt
..\gmasmz prango32 ..\test.zo3\prango32.txo -loy > ..\text.zo3\prango32.txt
..\gmasmz yasimi ..\test.zo3\yasimi -loy > ..\text.zo3\yasimi.txt
..\gmasmz yanamba ..\test.zo3\yanamba -loy > ..\text.zo3\yanamba.txt

..\gmasmz ldes2 ..\test.zo3\ldes2 -lo > ..\text.zo3\ldes2.txt

..\gmasmz a1 ..\test.zo3\a1 -lo > ..\text.zo3\a1.txt
..\gmasmz a1 ..\test.zo3\a2 -loc > ..\text.zo3\a2.txt
..\gmasmz a1 ..\test.zo3\a3 -loz > ..\text.zo3\a3.txt
..\gmasmz a1 ..\test.zo3\a4 -locz > ..\text.zo3\a4.txt

..\gmasmz reappear ..\test.zo3\reappear -lno > ..\text.zo3\reappear.txt

pushd ..\emulate
..\masmz xdr_lib8 ..\test.zo3\xdr_lib8 -loFG > ..\text.zo3\xdr_lib8.txt
popd

