del /Q  ..\test.o3\*
del /Q  ..\text.o3\*
..\masmx 1101 ..\test.o3\1101.txo -loy > ..\text.o3\1101.txt
..\masmx 1103 ..\test.o3\1103.txo -loy > ..\text.o3\1103.txt
..\masmx 14 ..\test.o3\14.txo -loy > ..\text.o3\14.txt
..\masmx 16lib24 ..\test.o3\16lib24.txo -loy > ..\text.o3\16lib24.txt
..\masmx 1st ..\test.o3\1st.txo -loy > ..\text.o3\1st.txt
..\masmx 2468 ..\test.o3\2468.txo -loy > ..\text.o3\2468.txt
..\masmx 2nd ..\test.o3\2nd.txo -loy > ..\text.o3\2nd.txt
..\masmx 2manif ..\test.o3\2manif.txo -loy > ..\text.o3\2manif.txt
..\masmx 3rd ..\test.o3\3rd.txo -loy > ..\text.o3\3rd.txt
..\masmx 3byte ..\test.o3\3byte.txo -loy > ..\text.o3\3byte.txt
..\masmx @ ..\test.o3\@.txo -loy > ..\text.o3\@.txt
..\masmx @1 ..\test.o3\@1.txo -loy > ..\text.o3\@1.txt
..\masmx about ..\test.o3\about.txo -loy > ..\text.o3\about.txt
..\masmx algebra ..\test.o3\algebra.txo -loy > ..\text.o3\algebra.txt
..\masmx app ..\test.o3\app.txo -loy > ..\text.o3\app.txt
..\masmx app7 ..\test.o3\app7.txo -loy > ..\text.o3\app7.txt
..\masmx aqt ..\test.o3\aqt.txo -loy > ..\text.o3\aqt.txt
..\masmx azuli ..\test.o3\azuli.txo -loy > ..\text.o3\azuli.txt
..\masmx balance ..\test.o3\balance.txo -loy > ..\text.o3\balance.txt
..\masmx bang ..\test.o3\bang -loy > ..\text.o3\bang.txt
..\masmx base_d ..\test.o3\base_d -loy > ..\text.o3\base_d.txt
..\masmx betaille ..\test.o3\betaille -loy > ..\text.o3\betaille.txt
..\masmx big48 ..\test.o3\big48.txo -loy > ..\text.o3\big48.txt
..\masmx bogle ..\test.o3\bogle.txo -loy > ..\text.o3\bogle.txt
..\masmx btest ..\test.o3\btest.txo -loy > ..\text.o3\btest.txt
..\masmx buy_sell ..\test.o3\buy_sell.txo -loy > ..\text.o3\buy_sell.txt
..\masmx capsule ..\test.o3\capsule.txo -loy > ..\text.o3\capsule.txt
..\masmx code ..\test.o3\code.txo -loy > ..\text.o3\code.txt
..\masmx commas ..\test.o3\commas.txo -loy > ..\text.o3\commas.txt
..\masmx cqt ..\test.o3\cqt.txo -loy > ..\text.o3\cqt.txt
..\masmx ctest ..\test.o3\ctest.txo -loy > ..\text.o3\ctest.txt
..\masmx d ..\test.o3\d.txo -loy > ..\text.o3\d.txt
..\masmx ddd ..\test.o3\ddd.txo -loy > ..\text.o3\ddd.txt
..\masmx dfp ..\test.o3\dfp.txo -loy > ..\text.o3\dfp.txt
..\masmx dfp16 ..\test.o3\dfp16.txo -loy > ..\text.o3\dfp16.txt
..\masmx do1 ..\test.o3\do1.txo -loy > ..\text.o3\do1.txt
..\masmx dollar ..\test.o3\dollar.txo -loy > ..\text.o3\dollar.txt
..\masmx dollar1 ..\test.o3\dollar1.txo -loy > ..\text.o3\dollar1.txt
..\masmx drat ..\test.o3\drat.txo -loy > ..\text.o3\drat.txt
..\masmx dryland ..\test.o3\dryland -loy > ..\text.o3\dryland.txt
..\masmx dup ..\test.o3\dup.txo -loy > ..\text.o3\dup.txt
..\masmx dx ..\test.o3\dx.txo -loy > ..\text.o3\dx.txt
..\masmx edit ..\test.o3\edit.txo -loy > ..\text.o3\edit.txt
..\masmx eq ..\test.o3\eq.txo -loy > ..\text.o3\eq.txt
..\masmx export ..\test.o3\export.txo -loy > ..\text.o3\export.txt
..\masmx fatalp ..\test.o3\fatalp.txo -loy > ..\text.o3\fatalp.txt
# ..\masmx feelup ..\test.o3\feelup.txo -loy > ..\text.o3\feelup.txt
..\masmx tremp ..\test.o3\tremp -lo > ..\text.o3\tremp.txt
..\masmx forgot ..\test.o3\forgot.txo -loy > ..\text.o3\forgot.txt
..\masmx form ..\test.o3\form.txo -loy > ..\text.o3\form.txt
..\masmx fp ..\test.o3\fp.txo -loy > ..\text.o3\fp.txt
..\masmx fp32 ..\test.o3\fp32.txo -loy > ..\text.o3\fp32.txt
..\masmx fpsize ..\test.o3\fpsize.txo -loy > ..\text.o3\fpsize.txt
..\masmx fptest ..\test.o3\fptest.txo -loy > ..\text.o3\fptest.txt
..\masmx fptestu ..\test.o3\fptestu.txo -loy > ..\text.o3\fptestu.txt
..\masmx fpx ..\test.o3\fpx.txo -loy > ..\text.o3\fpx.txt
..\masmx fs ..\test.o3\fs.txo -loy > ..\text.o3\fs.txt
..\masmx fs32 ..\test.o3\fs32.txo -loy > ..\text.o3\fs32.txt
..\masmx fx ..\test.o3\fx.txo -loy > ..\text.o3\fx.txt
..\masmx gflo ..\test.o3\gflo.txo -loy > ..\text.o3\gflo.txt
..\masmx grade ..\test.o3\grade.txo -loy > ..\text.o3\grade.txt
..\masmx grig ..\test.o3\grig.txo -loy > ..\text.o3\grig.txt
..\masmx grind ..\test.o3\grind.txo -loy > ..\text.o3\grind.txt
..\masmx grobags ..\test.o3\grobags.txo -loy > ..\text.o3\grobags.txt
..\masmx hflo ..\test.o3\hflo.txo -loy > ..\text.o3\hflo.txt
..\masmx howslow ..\test.o3\howslow.txo -loy > ..\text.o3\howslow.txt
..\masmx ieee754 ..\test.o3\ieee754.txo -loy > ..\text.o3\ieee754.txt
..\masmx ieeef ..\test.o3\ieeef.txo -loy > ..\text.o3\ieeef.txt
..\masmx if ..\test.o3\if.txo -loy > ..\text.o3\if.txt
..\masmx iffy ..\test.o3\iffy.txo -loy > ..\text.o3\iffy.txt
..\masmx ifwise ..\test.o3\ifwise.txo -loy > ..\text.o3\ifwise.txt
..\masmx immediat ..\test.o3\immediat.txo -loy > ..\text.o3\immediat.txt
..\masmx import ..\test.o3\import.txo -loy > ..\text.o3\import.txt
..\masmx inc ..\test.o3\inc.txo -loy > ..\text.o3\inc.txt
..\masmx inc1 ..\test.o3\inc1.txo -loy > ..\text.o3\inc1.txt
..\masmx inc2 ..\test.o3\inc2.txo -loy > ..\text.o3\inc2.txt
..\masmx inc3 ..\test.o3\inc3.txo -loy > ..\text.o3\inc3.txt
..\masmx j2 ..\test.o3\j2.txo -loy > ..\text.o3\j2.txt
..\masmx labels ..\test.o3\labels.txo -loy > ..\text.o3\labels.txt
..\masmx ldes ..\test.o3\ldes.txo -loy > ..\text.o3\ldes.txt
..\masmx leggy ..\test.o3\leggy.txo -loy > ..\text.o3\leggy.txt
..\masmx liable ..\test.o3\liable.txo -loy > ..\text.o3\liable.txt
..\masmx literal ..\test.o3\literal.txo -loy > ..\text.o3\literal.txt
..\masmx ll ..\test.o3\ll.txo -loy > ..\text.o3\ll.txt
..\masmx ll2 ..\test.o3\ll2.txo -loy > ..\text.o3\ll2.txt
..\masmx luri ..\test.o3\luri.txo -loy > ..\text.o3\luri.txt
..\masmx mafcol1 ..\test.o3\mafcol1.txo -loy > ..\text.o3\mafcol1.txt
..\masmx malfun ..\test.o3\malfun.txo -oy > ..\text.o3\malfun.txt
..\masmx malpro ..\test.o3\malpro.txo -oy > ..\text.o3\malpro.txt
..\masmx malprobe ..\test.o3\malprobe.txo -oy > ..\text.o3\malprobe.txt
..\masmx mango ..\test.o3\mango.txo -loy > ..\text.o3\mango.txt
..\masmx map10g ..\test.o3\map10g.txo -loy > ..\text.o3\map10g.txt
..\masmx map8g ..\test.o3\map8g.txo -loy > ..\text.o3\map8g.txt
..\masmx masm7 ..\test.o3\masm7.txo -loy > ..\text.o3\masm7.txt
..\masmx maxfloat ..\test.o3\maxfloat.txo -loy > ..\text.o3\maxfloat.txt
..\masmx maxtini ..\test.o3\maxtini.txo -loy > ..\text.o3\maxtini.txt
..\masmx maxwini ..\test.o3\maxwini.txo -loy > ..\text.o3\maxwini.txt
..\masmx more ..\test.o3\more.txo -loy > ..\text.o3\more.txt
..\masmx n ..\test.o3\n.txo -loy > ..\text.o3\n.txt
..\masmx name ..\test.o3\name.txo -loy > ..\text.o3\name.txt
..\masmx netio ..\test.o3\netio.txo -loy > ..\text.o3\netio.txt
..\masmx nipit ..\test.o3\nipit.txo -loy > ..\text.o3\nipit.txt
..\masmx nostroph ..\test.o3\nostroph.txo -loy > ..\text.o3\nostroph.txt
..\masmx notvast ..\test.o3\notvast.txo -loy > ..\text.o3\notvast.txt
..\masmx nuri ..\test.o3\nuri.txo -loy > ..\text.o3\nuri.txt
..\masmx nvg ..\test.o3\nvg.txo -loy > ..\text.o3\nvg.txt
..\masmx o ..\test.o3\o.txo -loy > ..\text.o3\o.txt
..\masmx outline ..\test.o3\outline.txo -loy > ..\text.o3\outline.txt
..\masmx prelink ..\test.o3\prelink.txo -loy > ..\text.o3\prelink.txt
..\masmx q ..\test.o3\q.txo -loy > ..\text.o3\q.txt
..\masmx qb2i ..\test.o3\qb2i.txo -loy > ..\text.o3\qb2i.txt
..\masmx questit ..\test.o3\questit -lnoky > ..\text.o3\questit.txt
..\masmx quicki ..\test.o3\quicki.txo -loy > ..\text.o3\quicki.txt
..\masmx qzuli ..\test.o3\qzuli.txo -loy > ..\text.o3\qzuli.txt
..\masmx qzweli ..\test.o3\qzweli.txo -loy > ..\text.o3\qzweli.txt
..\masmx random ..\test.o3\random.txo -loy > ..\text.o3\random.txt
..\masmx rel ..\test.o3\rel.txo -loy > ..\text.o3\rel.txt
..\masmx rel2 ..\test.o3\rel2.txo -loy > ..\text.o3\rel2.txt
..\masmx remindme ..\test.o3\remindme.txo -loy > ..\text.o3\remindme.txt
..\masmx rino ..\test.o3\rino.txo -loy > ..\text.o3\rino.txt
..\masmx rounding ..\test.o3\rounding.txo -loy > ..\text.o3\rounding.txt
..\masmx s ..\test.o3\s.txo -loy > ..\text.o3\s.txt
..\masmx scally ..\test.o3\scally.txo -loy > ..\text.o3\scally.txt
..\masmx see ..\test.o3\see.txo -loy > ..\text.o3\see.txt
..\masmx simples ..\test.o3\simples.txo -loy > ..\text.o3\simples.txt
..\masmx snozeli ..\test.o3\snozeli.txo -loy > ..\text.o3\snozeli.txt
..\masmx space ..\test.o3\space.txo -loy > ..\text.o3\space.txt
..\masmx steps ..\test.o3\steps.txo -loy > ..\text.o3\steps.txt
..\masmx strophe ..\test.o3\strophe.txo -loy > ..\text.o3\strophe.txt
..\masmx subs ..\test.o3\subs.txo -loy > ..\text.o3\subs.txt
..\masmx suficsee ..\test.o3\suficsee.txo -loy > ..\text.o3\suficsee.txt
..\masmx tcp_rxip ..\test.o3\tcp_rxip.txo -loy > ..\text.o3\tcp_rxip.txt
..\masmx trivial ..\test.o3\trivial.txo -loy > ..\text.o3\trivial.txt
..\masmx trtab2 ..\test.o3\trtab2.txo -loy > ..\text.o3\trtab2.txt
..\masmx ttable ..\test.o3\ttable.txo -loy > ..\text.o3\ttable.txt
..\masmx vsim ..\test.o3\vsim.txo -loy > ..\text.o3\vsim.txt
..\masmx whereami ..\test.o3\whereami.txo -loy > ..\text.o3\whereami.txt
..\masmx whether ..\test.o3\whether.txo -loy > ..\text.o3\whether.txt
..\masmx yepnope ..\test.o3\yepnope.txo -loy > ..\text.o3\yepnope.txt
..\masmx zipit ..\test.o3\zipit.txo -loy > ..\text.o3\zipit.txt
..\masmx abit ..\test.o3\abit.txo -loy > ..\text.o3\abit.txt
..\masmx addo ..\test.o3\addo.txo -loy > ..\text.o3\addo.txt
..\masmx addu ..\test.o3\addu.txo -loy > ..\text.o3\addu.txt
..\masmx addz ..\test.o3\addz.txo -loy > ..\text.o3\addz.txt
..\masmx adsomor1 ..\test.o3\adsomor1.txo -loy > ..\text.o3\adsomor1.txt
..\masmx adsomor2 ..\test.o3\adsomor2.txo -loy > ..\text.o3\adsomor2.txt
..\masmx adsomor3 ..\test.o3\adsomor3.txo -loy > ..\text.o3\adsomor3.txt
..\masmx adsomor4 ..\test.o3\adsomor4.txo -loy > ..\text.o3\adsomor4.txt
..\masmx afile ..\test.o3\afile.txo -loy > ..\text.o3\afile.txt
..\masmx aglimpse ..\test.o3\aglimpse.txo -loy > ..\text.o3\aglimpse.txt
..\masmx agranoy ..\test.o3\agranoy.txo -loy > ..\text.o3\agranoy.txt
..\masmx ajoko ..\test.o3\ajoko.txo -loy > ..\text.o3\ajoko.txt
..\masmx align ..\test.o3\align.txo -loy > ..\text.o3\align.txt
..\masmx allyoobl ..\test.o3\allyoobl.txo -loy > ..\text.o3\allyoobl.txt
..\masmx anew ..\test.o3\anew.txo -loy > ..\text.o3\anew.txt
..\masmx another ..\test.o3\another.txo -loy > ..\text.o3\another.txt
..\masmx aon ..\test.o3\aon.txo -loy > ..\text.o3\aon.txt
..\masmx app1 ..\test.o3\app1.txo -loy > ..\text.o3\app1.txt
..\masmx app2 ..\test.o3\app2.txo -loy > ..\text.o3\app2.txt
..\masmx app3 ..\test.o3\app3.txo -loy > ..\text.o3\app3.txt
..\masmx app4 ..\test.o3\app4.txo -loy > ..\text.o3\app4.txt
..\masmx appoint ..\test.o3\appoint.txo -loy > ..\text.o3\appoint.txt
..\masmx approx ..\test.o3\approx.txo -loy > ..\text.o3\approx.txt
..\masmx arm ..\test.o3\arm.txo -loy > ..\text.o3\arm.txt
..\masmx array ..\test.o3\array.txo -loy > ..\text.o3\array.txt
..\masmx arrayok ..\test.o3\arrayok.txo -loy > ..\text.o3\arrayok.txt
..\masmx asample ..\test.o3\asample.txo -loy > ..\text.o3\asample.txt
..\masmx ast ..\test.o3\ast.txo -loy > ..\text.o3\ast.txt
..\masmx atest ..\test.o3\atest.txo -loy > ..\text.o3\atest.txt
..\masmx attempt ..\test.o3\attempt.txo -loy > ..\text.o3\attempt.txt
..\masmx avast ..\test.o3\avast.txo -lo > ..\text.o3\avast.txt
..\masmx avastok ..\test.o3\avastok.txo -lo > ..\text.o3\avastok.txt
..\masmx avenu ..\test.o3\avenu.txo -loy > ..\text.o3\avenu.txt
..\masmx awail ..\test.o3\awail.txo -loy > ..\text.o3\awail.txt
..\masmx awain ..\test.o3\awain.txo -loy > ..\text.o3\awain.txt
..\masmx away ..\test.o3\away.txo -loy > ..\text.o3\away.txt
..\masmx awkward ..\test.o3\awkward.txo -loy > ..\text.o3\awkward.txt
..\masmx b ..\test.o3\b.txo -loy > ..\text.o3\b.txt
..\masmx badly ..\test.o3\badly.txo -loy > ..\text.o3\badly.txt
..\masmx banks ..\test.o3\banks.txo -loy > ..\text.o3\banks.txt
..\masmx banks2 ..\test.o3\banks2.txo -loy > ..\text.o3\banks2.txt
..\masmx basal1 ..\test.o3\basal1.txo -loy > ..\text.o3\basal1.txt
..\masmx basalall ..\test.o3\basalall.txo -loy > ..\text.o3\basalall.txt
..\masmx basalone ..\test.o3\basalone.txo -loy > ..\text.o3\basalone.txt
..\masmx basalthr ..\test.o3\basalthr.txo -loy > ..\text.o3\basalthr.txt
..\masmx basaltwo ..\test.o3\basaltwo.txo -loy > ..\text.o3\basaltwo.txt
..\masmx basis ..\test.o3\basis.txo -loy > ..\text.o3\basis.txt
..\masmx bdw ..\test.o3\bdw.txo -loy > ..\text.o3\bdw.txt
..\masmx bequf ..\test.o3\bequf.txo -loy > ..\text.o3\bequf.txt
..\masmx big ..\test.o3\big.txo -loy > ..\text.o3\big.txt
..\masmx bitsof ..\test.o3\bitsof.txo -loy > ..\text.o3\bitsof.txt
..\masmx blanks ..\test.o3\blanks.txo -loy > ..\text.o3\blanks.txt
..\masmx bonkers ..\test.o3\bonkers.txo -loy > ..\text.o3\bonkers.txt
..\masmx bounded ..\test.o3\bounded.txo -loy > ..\text.o3\bounded.txt
..\masmx boxy ..\test.o3\boxy.txo -loy > ..\text.o3\boxy.txt
..\masmx bqt ..\test.o3\bqt.txo -loy > ..\text.o3\bqt.txt
..\masmx brickie ..\test.o3\brickie.txo -loy > ..\text.o3\brickie.txt
..\masmx brozzing ..\test.o3\brozzing.txo -loy > ..\text.o3\brozzing.txt
..\masmx bway ..\test.o3\bway.txo -loy > ..\text.o3\bway.txt
..\masmx cancan ..\test.o3\cancan.txo -loy > ..\text.o3\cancan.txt
..\masmx carryon ..\test.o3\carryon.txo -loy > ..\text.o3\carryon.txt
..\masmx case ..\test.o3\case.txo -loy > ..\text.o3\case.txt
..\masmx cases ..\test.o3\cases.txo -loy > ..\text.o3\cases.txt
..\masmx cdml ..\test.o3\cdml.txo -loy > ..\text.o3\cdml.txt
..\masmx cheese ..\test.o3\cheese.txo -loy > ..\text.o3\cheese.txt
..\masmx comment ..\test.o3\comment.txo -loy > ..\text.o3\comment.txt
..\masmx comment1 ..\test.o3\comment1.txo -loy > ..\text.o3\comment1.txt
..\masmx complex ..\test.o3\complex.txo -loy > ..\text.o3\complex.txt
..\masmx compo ..\test.o3\compo.txo -loy > ..\text.o3\compo.txt
..\masmx compose ..\test.o3\compose.txo -loy > ..\text.o3\compose.txt
..\masmx constanz ..\test.o3\constanz.txo -loy > ..\text.o3\constanz.txt
..\masmx context ..\test.o3\context.txo -loy > ..\text.o3\context.txt
..\masmx contrary ..\test.o3\contrary.txo -loy > ..\text.o3\contrary.txt
..\masmx controb2 ..\test.o3\controb2.txo -loy > ..\text.o3\controb2.txt
..\masmx control1 ..\test.o3\control1.txo -loy > ..\text.o3\control1.txt
..\masmx control2 ..\test.o3\control2.txo -loy > ..\text.o3\control2.txt
..\masmx control3 ..\test.o3\control3.txo -loy > ..\text.o3\control3.txt
..\masmx control4 ..\test.o3\control4.txo -loy > ..\text.o3\control4.txt
..\masmx crabble ..\test.o3\crabble.txo -loy > ..\text.o3\crabble.txt
..\masmx dd ..\test.o3\dd.txo -loy > ..\text.o3\dd.txt
..\masmx dde ..\test.o3\dde.txo -loy > ..\text.o3\dde.txt
..\masmx decode ..\test.o3\decode.txo -loy > ..\text.o3\decode.txt
..\masmx deep ..\test.o3\deep.txo -loy > ..\text.o3\deep.txt
..\masmx deep_lit ..\test.o3\deep_lit.txo -loy > ..\text.o3\deep_lit.txt
..\masmx demo1 ..\test.o3\demo1.txo -lo > ..\text.o3\demo1.txt
..\masmx demo2 ..\test.o3\demo2.txo -lo > ..\text.o3\demo2.txt
..\masmx demo3 ..\test.o3\demo3.txo -lo > ..\text.o3\demo3.txt
..\masmx detune ..\test.o3\detune.txo -loy > ..\text.o3\detune.txt
..\masmx dfp16 ..\test.o3\dfp16.txo -loy > ..\text.o3\dfp16.txt
..\masmx diffi ..\test.o3\diffi.txo -loy > ..\text.o3\diffi.txt
..\masmx dl ..\test.o3\dl.txo -loy > ..\text.o3\dl.txt
..\masmx do ..\test.o3\do.txo -loy > ..\text.o3\do.txt
..\masmx do2 ..\test.o3\do2.txo -loy > ..\text.o3\do2.txt
..\masmx do3 ..\test.o3\do3.txo -loy > ..\text.o3\do3.txt
..\masmx do32 ..\test.o3\do32.txo -loy > ..\text.o3\do32.txt
..\masmx do4 ..\test.o3\do4.txo -loy > ..\text.o3\do4.txt
..\masmx dogma ..\test.o3\dogma.txo -loy > ..\text.o3\dogma.txt
..\masmx dotable ..\test.o3\dotable.txo -loy > ..\text.o3\dotable.txt
..\masmx dudif ..\test.o3\dudif.txo -loy > ..\text.o3\dudif.txt
..\masmx dumexa ..\test.o3\dumexa.txo -loy > ..\text.o3\dumexa.txt
..\masmx elboaze ..\test.o3\elboaze.txo -loy > ..\text.o3\elboaze.txt
..\masmx elf ..\test.o3\elf.txo -loy > ..\text.o3\elf.txt
..\masmx entrada ..\test.o3\entrada.txo -loy > ..\text.o3\entrada.txt
..\masmx environ ..\test.o3\environ.txo -loy > ..\text.o3\environ.txt
..\masmx equf ..\test.o3\equf.txo -loy > ..\text.o3\equf.txt
..\masmx equf32 ..\test.o3\equf32.txo -loy > ..\text.o3\equf32.txt
..\masmx expo ..\test.o3\expo.txo -loy > ..\text.o3\expo.txt
..\masmx f ..\test.o3\f.txo -loy > ..\text.o3\f.txt
..\masmx f2f ..\test.o3\f2f.txo -loy > ..\text.o3\f2f.txt
..\masmx factor ..\test.o3\factor.txo -loy > ..\text.o3\factor.txt
..\masmx fames ..\test.o3\fames.txo -lo > ..\text.o3\fames.txt
..\masmx fff ..\test.o3\fff.txo -loy > ..\text.o3\fff.txt
..\masmx flags ..\test.o3\flags.txo -loy > ..\text.o3\flags.txt
..\masmx forjoy ..\test.o3\forjoy.txo -loy > ..\text.o3\forjoy.txt
..\masmx fragment ..\test.o3\fragment.txo -loy > ..\text.o3\fragment.txt
..\masmx frame2 ..\test.o3\frame2.txo -loy > ..\text.o3\frame2.txt
..\masmx fref ..\test.o3\fref.txo -loy > ..\text.o3\fref.txt
..\masmx fruit ..\test.o3\fruit.txo -loy > ..\text.o3\fruit.txt
..\masmx frung ..\test.o3\frung.txo -loy > ..\text.o3\frung.txt
..\masmx fs32 ..\test.o3\fs32.txo -loy > ..\text.o3\fs32.txt
..\masmx fs48 ..\test.o3\fs48.txo -loy > ..\text.o3\fs48.txt
..\masmx further ..\test.o3\further.txo -loy > ..\text.o3\further.txt
..\masmx fzero ..\test.o3\fzero.txo -loy > ..\text.o3\fzero.txt
..\masmx general ..\test.o3\general.txo -loy > ..\text.o3\general.txt
..\masmx gfactor ..\test.o3\gfactor.txo -loy > ..\text.o3\gfactor.txt
..\masmx gfar ..\test.o3\gfar.txo -loy > ..\text.o3\gfar.txt
..\masmx gframe2 ..\test.o3\gframe2.txo -loy > ..\text.o3\gframe2.txt
..\masmx gfurther ..\test.o3\gfurther.txo -loy > ..\text.o3\gfurther.txt
..\masmx goodbit ..\test.o3\goodbit.txo -loy > ..\text.o3\goodbit.txt
..\masmx gram ..\test.o3\gram.txo -loy > ..\text.o3\gram.txt
..\masmx gross ..\test.o3\gross.txo -loy > ..\text.o3\gross.txt
..\masmx grum ..\test.o3\grum.txo -loy > ..\text.o3\grum.txt
..\masmx gscale22 ..\test.o3\gscale22.txo -loy > ..\text.o3\gscale22.txt
..\masmx gscale23 ..\test.o3\gscale23.txo -loy > ..\text.o3\gscale23.txt
..\masmx gscale24 ..\test.o3\gscale24.txo -loy > ..\text.o3\gscale24.txt
..\masmx gsoso ..\test.o3\gsoso.txo -loy > ..\text.o3\gsoso.txt
..\masmx gworser ..\test.o3\gworser.txo -loy > ..\text.o3\gworser.txt
..\masmx gwyllmp ..\test.o3\gwyllmp.txo -loy > ..\text.o3\gwyllmp.txt
..\masmx gzactor ..\test.o3\gzactor.txo -loy > ..\text.o3\gzactor.txt
..\masmx haive ..\test.o3\haive.txo -loy > ..\text.o3\haive.txt
..\masmx handfull ..\test.o3\handfull.txo -loy > ..\text.o3\handfull.txt
..\masmx hangobar ..\test.o3\hangobar.txo -loy > ..\text.o3\hangobar.txt
..\masmx high ..\test.o3\high.txo -loy > ..\text.o3\high.txt
..\masmx howmany ..\test.o3\howmany.txo -loy > ..\text.o3\howmany.txt
..\masmx hwis ..\test.o3\hwis.txo -loy > ..\text.o3\hwis.txt
..\masmx ican ..\test.o3\ican.txo -loy > ..\text.o3\ican.txt
..\masmx ieee754 ..\test.o3\ieee754.txo -loy > ..\text.o3\ieee754.txt
..\masmx ieee754s ..\test.o3\ieee754s.txo -loy > ..\text.o3\ieee754s.txt
..\masmx ifp ..\test.o3\ifp.txo -loy > ..\text.o3\ifp.txt
..\masmx iii ..\test.o3\iii.txo -loy > ..\text.o3\iii.txt
..\masmx info ..\test.o3\info.txo -loy > ..\text.o3\info.txt
..\masmx inside ..\test.o3\inside.txo -loy > ..\text.o3\inside.txt
..\masmx intrepid ..\test.o3\intrepid.txo -loy > ..\text.o3\intrepid.txt
..\masmx intune ..\test.o3\intune.txo -loy > ..\text.o3\intune.txt
..\masmx iscale1 ..\test.o3\iscale1.txo -loy > ..\text.o3\iscale1.txt
..\masmx iscale2 ..\test.o3\iscale2.txo -loy > ..\text.o3\iscale2.txt
..\masmx iscale3 ..\test.o3\iscale3.txo -loy > ..\text.o3\iscale3.txt
..\masmx iside1 ..\test.o3\iside1.txo -loy > ..\text.o3\iside1.txt
..\masmx isobar ..\test.o3\isobar.txo -loy > ..\text.o3\isobar.txt
..\masmx isobar1 ..\test.o3\isobar1.txo -loy > ..\text.o3\isobar1.txt
..\masmx isthatso ..\test.o3\isthatso.txo -loy > ..\text.o3\isthatso.txt
..\masmx j3 ..\test.o3\j3.txo -loy > ..\text.o3\j3.txt
..\masmx justname ..\test.o3\justname.txo -loy > ..\text.o3\justname.txt
..\masmx keeptry ..\test.o3\keeptry.txo -loy > ..\text.o3\keeptry.txt
..\masmx keyword ..\test.o3\keyword.txo -loy > ..\text.o3\keyword.txt
..\masmx l ..\test.o3\l.txo -loy > ..\text.o3\l.txt
..\masmx langobar ..\test.o3\langobar.txo -loy > ..\text.o3\langobar.txt
..\masmx largle ..\test.o3\largle.txo -loy > ..\text.o3\largle.txt
..\masmx lcodes ..\test.o3\lcodes.txo -loy > ..\text.o3\lcodes.txt
..\masmx letsbya ..\test.o3\letsbya.txo -loy > ..\text.o3\letsbya.txt
..\masmx linitup ..\test.o3\linitup.txo -loy > ..\text.o3\linitup.txt
..\masmx lit ..\test.o3\lit.txo -loy > ..\text.o3\lit.txt
..\masmx lit8051 ..\test.o3\lit8051.txo -loy > ..\text.o3\lit8051.txt
..\masmx little ..\test.o3\little.txo -loy > ..\text.o3\little.txt
..\masmx ll3 ..\test.o3\ll3.txo -loy > ..\text.o3\ll3.txt
..\masmx ll4 ..\test.o3\ll4.txo -loy > ..\text.o3\ll4.txt
..\masmx ll5 ..\test.o3\ll5.txo -loy > ..\text.o3\ll5.txt
..\masmx ll5abs ..\test.o3\ll5abs.txo -loy > ..\text.o3\ll5abs.txt
..\masmx ll6 ..\test.o3\ll6.txo -loy > ..\text.o3\ll6.txt
..\masmx ll6abs ..\test.o3\ll6abs.txo -loy > ..\text.o3\ll6abs.txt
..\masmx lodation ..\test.o3\lodation.txo -loy > ..\text.o3\lodation.txt
..\masmx longjump ..\test.o3\longjump.txo -loy > ..\text.o3\longjump.txt
..\masmx loopy ..\test.o3\loopy.txo -loy > ..\text.o3\loopy.txt
..\masmx lorg ..\test.o3\lorg.txo -loy > ..\text.o3\lorg.txt
..\masmx lorgle ..\test.o3\lorgle.txo -loy > ..\text.o3\lorgle.txt
..\masmx m ..\test.o3\m.txo -loy > ..\text.o3\m.txt
..\masmx mangle ..\test.o3\mangle.txo -loy > ..\text.o3\mangle.txt
..\masmx manif ..\test.o3\manif.txo -loy > ..\text.o3\manif.txt
..\masmx many ..\test.o3\many.txo -loy > ..\text.o3\many.txt
..\masmx map ..\test.o3\map.txo -loy > ..\text.o3\map.txt
..\masmx map1 ..\test.o3\map1.txo -loy > ..\text.o3\map1.txt
..\masmx map10 ..\test.o3\map10.txo -loy > ..\text.o3\map10.txt
..\masmx map11 ..\test.o3\map11.txo -loy > ..\text.o3\map11.txt
..\masmx map12 ..\test.o3\map12.txo -loy > ..\text.o3\map12.txt
..\masmx map15 ..\test.o3\map15.txo -loy > ..\text.o3\map15.txt
..\masmx map2 ..\test.o3\map2.txo -loy > ..\text.o3\map2.txt
..\masmx map3 ..\test.o3\map3.txo -loy > ..\text.o3\map3.txt
..\masmx map4 ..\test.o3\map4.txo -loy > ..\text.o3\map4.txt
..\masmx map5 ..\test.o3\map5.txo -loy > ..\text.o3\map5.txt
..\masmx map6 ..\test.o3\map6.txo -loy > ..\text.o3\map6.txt
..\masmx map7 ..\test.o3\map7.txo -loy > ..\text.o3\map7.txt
..\masmx map7g ..\test.o3\map7g.txo -loy > ..\text.o3\map7g.txt
..\masmx map8 ..\test.o3\map8.txo -loy > ..\text.o3\map8.txt
..\masmx map9 ..\test.o3\map9.txo -loy > ..\text.o3\map9.txt
..\masmx mary ..\test.o3\mary.txo -loy > ..\text.o3\mary.txt
..\masmx maxfloat ..\test.o3\maxfloat.txo -loy > ..\text.o3\maxfloat.txt
..\masmx maxmaxi ..\test.o3\maxmaxi.txo -lo > ..\text.o3\maxmaxi.txt
..\masmx mbank ..\test.o3\mbank.txo -loy > ..\text.o3\mbank.txt
..\masmx mbank1 ..\test.o3\mbank1.txo -loy > ..\text.o3\mbank1.txt
..\masmx ml ..\test.o3\ml.txo -loy > ..\text.o3\ml.txt
..\masmx mlingba ..\test.o3\mlingba.txo -loy > ..\text.o3\mlingba.txt
lstring -b ..\test.o3\mlingba.txo ..\test.o3\mlingba
..\masmx modest ..\test.o3\modest.txo -loy > ..\text.o3\modest.txt
..\masmx mojo ..\test.o3\mojo.txo -loy > ..\text.o3\mojo.txt
..\masmx mouli ..\test.o3\mouli.txo -loy > ..\text.o3\mouli.txt
..\masmx movem ..\test.o3\movem.txo -loy > ..\text.o3\movem.txt
..\masmx multest ..\test.o3\multest.txo -loy > ..\text.o3\multest.txt
..\masmx multitr ..\test.o3\multitr.txo -loy > ..\text.o3\multitr.txt
..\masmx mungle ..\test.o3\mungle.txo -loy > ..\text.o3\mungle.txt
..\masmx names ..\test.o3\names.txo -lo > ..\text.o3\names.txt
..\masmx nang ..\test.o3\nang.txo -loy > ..\text.o3\nang.txt
..\masmx needle ..\test.o3\needle.txo -loy > ..\text.o3\needle.txt
..\masmx nest ..\test.o3\nest.txo -loy > ..\text.o3\nest.txt
..\masmx netbio ..\test.o3\netbio.txo -loy > ..\text.o3\netbio.txt
..\masmx netvalue ..\test.o3\netvalue.txo -loy > ..\text.o3\netvalue.txt
..\masmx new ..\test.o3\new.txo -loy > ..\text.o3\new.txt
..\masmx newby ..\test.o3\newby.txo -loy > ..\text.o3\newby.txt
..\masmx newdata ..\test.o3\newdata.txo -loy > ..\text.o3\newdata.txt
..\masmx norkette ..\test.o3\norkette.txo -loy > ..\text.o3\norkette.txt
..\masmx nosedive ..\test.o3\nosedive.txo -loy > ..\text.o3\nosedive.txt
..\masmx noso ..\test.o3\noso.txo -loy > ..\text.o3\noso.txt
..\masmx notmany ..\test.o3\notmany.txo -loy > ..\text.o3\notmany.txt
..\masmx notso ..\test.o3\notso.txo -loy > ..\text.o3\notso.txt
..\masmx ocycle ..\test.o3\ocycle.txo -loy > ..\text.o3\ocycle.txt
..\masmx oddly ..\test.o3\oddly.txo -loy > ..\text.o3\oddly.txt
..\masmx offset ..\test.o3\offset.txo -loy > ..\text.o3\offset.txt
..\masmx ok1 ..\test.o3\ok1.txo -loy > ..\text.o3\ok1.txt
..\masmx one ..\test.o3\one.txo -loy > ..\text.o3\one.txt
..\masmx onetwo ..\test.o3\onetwo.txo -loy > ..\text.o3\onetwo.txt
..\masmx oreally ..\test.o3\oreally.txo -loy > ..\text.o3\oreally.txt
..\masmx orgalign ..\test.o3\orgalign.txo -loy > ..\text.o3\orgalign.txt
..\masmx otherwis ..\test.o3\otherwis.txo -loy > ..\text.o3\otherwis.txt
..\masmx outrage ..\test.o3\outrage.txo -loy > ..\text.o3\outrage.txt
..\masmx outside ..\test.o3\outside.txo -loy > ..\text.o3\outside.txt
..\masmx overlaid ..\test.o3\overlaid.txo -loy > ..\text.o3\overlaid.txt
..\masmx overlay ..\test.o3\overlay.txo -loy > ..\text.o3\overlay.txt
..\masmx p ..\test.o3\p.txo -loy > ..\text.o3\p.txt
..\masmx packem ..\test.o3\packem.txo -loy > ..\text.o3\packem.txt
..\masmx paraform ..\test.o3\paraform.txo -loy > ..\text.o3\paraform.txt
..\masmx param ..\test.o3\param.txo -loy > ..\text.o3\param.txt
..\masmx paren ..\test.o3\paren.txo -loy > ..\text.o3\paren.txt
..\masmx passes ..\test.o3\passes.txo -loy > ..\text.o3\passes.txt
..\masmx passive ..\test.o3\passive.txo -loy > ..\text.o3\passive.txt
..\masmx perform ..\test.o3\perform.txo -loy > ..\text.o3\perform.txt
..\masmx plain ..\test.o3\plain.txo -loy > ..\text.o3\plain.txt
..\masmx plank ..\test.o3\plank.txo -loy > ..\text.o3\plank.txt
..\masmx plobbo ..\test.o3\plobbo.txo -loy > ..\text.o3\plobbo.txt
..\masmx ppc1 ..\test.o3\ppc1.txo -loy > ..\text.o3\ppc1.txt
..\masmx ppcsinga ..\test.o3\ppcsinga.txo -loy > ..\text.o3\ppcsinga.txt
..\masmx ppcsingb ..\test.o3\ppcsingb.txo -loy > ..\text.o3\ppcsingb.txt
..\masmx ppcsingr ..\test.o3\ppcsingr.txo -loy > ..\text.o3\ppcsingr.txt
..\masmx ppcuvast ..\test.o3\ppcuvast.txo -lo > ..\text.o3\ppcuvast.txt
..\masmx pratisla ..\test.o3\pratisla.txo -loy > ..\text.o3\pratisla.txt
..\masmx predikat ..\test.o3\predikat.txo -loy > ..\text.o3\predikat.txt
..\masmx proceds ..\test.o3\proceds.txo -loy > ..\text.o3\proceds.txt
..\masmx proxy ..\test.o3\proxy.txo -loy > ..\text.o3\proxy.txt
..\masmx ptup ..\test.o3\ptup.txo -loy > ..\text.o3\ptup.txt
..\masmx pusingv ..\test.o3\pusingv.txo -loy > ..\text.o3\pusingv.txt
..\masmx pvusinga ..\test.o3\pvusinga.txo -loy > ..\text.o3\pvusinga.txt
..\masmx pzero ..\test.o3\pzero.txo -loy > ..\text.o3\pzero.txt
..\masmx q1 ..\test.o3\q1.txo -loy > ..\text.o3\q1.txt
..\masmx qati ..\test.o3\qati.txo -loy > ..\text.o3\qati.txt
..\masmx qbig ..\test.o3\qbig.txo -loy > ..\text.o3\qbig.txt
..\masmx qf ..\test.o3\qf.txo -loy > ..\text.o3\qf.txt
..\masmx qflic ..\test.o3\qflic.txo -loy > ..\text.o3\qflic.txt
..\masmx qpart ..\test.o3\qpart.txo -loy > ..\text.o3\qpart.txt
..\masmx qplain ..\test.o3\qplain.txo -loy > ..\text.o3\qplain.txt
..\masmx qt ..\test.o3\qt.txo -loy > ..\text.o3\qt.txt
..\masmx quidgeo ..\test.o3\quidgeo.txo -loy > ..\text.o3\quidgeo.txt
..\masmx quitebad ..\test.o3\quitebad.txo -loy > ..\text.o3\quitebad.txt
..\masmx quo ..\test.o3\quo.txo -loy > ..\text.o3\quo.txt
..\masmx quo1 ..\test.o3\quo1.txo -loy > ..\text.o3\quo1.txt
..\masmx quo2 ..\test.o3\quo2.txo -loy > ..\text.o3\quo2.txt
..\masmx quo3 ..\test.o3\quo3.txo -loy > ..\text.o3\quo3.txt
..\masmx quo4 ..\test.o3\quo4.txo -loy > ..\text.o3\quo4.txt
..\masmx quo5 ..\test.o3\quo5.txo -loy > ..\text.o3\quo5.txt
..\masmx r ..\test.o3\r.txo -loy > ..\text.o3\r.txt
..\masmx r_u_rel ..\test.o3\r_u_rel.txo -loy > ..\text.o3\r_u_rel.txt
..\masmx radalupu ..\test.o3\radalupu.txo -loy > ..\text.o3\radalupu.txt
..\masmx really ..\test.o3\really.txo -loy > ..\text.o3\really.txt
..\masmx reco ..\test.o3\reco.txo -loy > ..\text.o3\reco.txt
..\masmx recurs ..\test.o3\recurs.txo -loy > ..\text.o3\recurs.txt
..\masmx relj ..\test.o3\relj.txo -loy > ..\text.o3\relj.txt
..\masmx relja ..\test.o3\relja.txo -loy > ..\text.o3\relja.txt
..\masmx relstack ..\test.o3\relstack.txo -loy > ..\text.o3\relstack.txt
..\masmx rempack ..\test.o3\rempack.txo -loy > ..\text.o3\rempack.txt
..\masmx rempart ..\test.o3\rempart.txo -loy > ..\text.o3\rempart.txt
..\masmx rename ..\test.o3\rename.txo -loy > ..\text.o3\rename.txt
..\masmx rep ..\test.o3\rep.txo -loy > ..\text.o3\rep.txt
..\masmx res ..\test.o3\res.txo -loy > ..\text.o3\res.txt
..\masmx risobar ..\test.o3\risobar.txo -loy > ..\text.o3\risobar.txt
..\masmx rough ..\test.o3\rough.txo -loy > ..\text.o3\rough.txt
..\masmx roundelay ..\test.o3\roundelay.txo -loy > ..\text.o3\roundelay.txt
..\masmx rplain ..\test.o3\rplain.txo -loy > ..\text.o3\rplain.txt
..\masmx rumad ..\test.o3\rumad.txo -loy > ..\text.o3\rumad.txt
..\masmx ryatha ..\test.o3\ryatha.txo -loy > ..\text.o3\ryatha.txt
..\masmx sample ..\test.o3\sample.txo -loy > ..\text.o3\sample.txt
..\masmx sample2 ..\test.o3\sample2.txo -loy > ..\text.o3\sample2.txt
..\masmx scabrous ..\test.o3\scabrous.txo -loy > ..\text.o3\scabrous.txt
..\masmx scale ..\test.o3\scale.txo -loy > ..\text.o3\scale.txt
..\masmx scale1 ..\test.o3\scale1.txo -loy > ..\text.o3\scale1.txt
..\masmx scale2 ..\test.o3\scale2.txo -loy > ..\text.o3\scale2.txt
..\masmx scale22 ..\test.o3\scale22.txo -loy > ..\text.o3\scale22.txt
..\masmx scale23 ..\test.o3\scale23.txo -loy > ..\text.o3\scale23.txt
..\masmx scale24 ..\test.o3\scale24.txo -loy > ..\text.o3\scale24.txt
..\masmx scale3 ..\test.o3\scale3.txo -loy > ..\text.o3\scale3.txt
..\masmx scale4 ..\test.o3\scale4.txo -loy > ..\text.o3\scale4.txt
..\masmx scale5 ..\test.o3\scale5.txo -loy > ..\text.o3\scale5.txt
..\masmx scale6 ..\test.o3\scale6.txo -loy > ..\text.o3\scale6.txt
..\masmx scale8 ..\test.o3\scale8.txo -loy > ..\text.o3\scale8.txt
..\masmx scally2 ..\test.o3\scally2.txo -loy > ..\text.o3\scally2.txt
..\masmx scally3 ..\test.o3\scally3.txo -loy > ..\text.o3\scally3.txt
..\masmx scally4 ..\test.o3\scally4.txo -loy > ..\text.o3\scally4.txt
..\masmx see2it ..\test.o3\see2it.txo -loy > ..\text.o3\see2it.txt
..\masmx seomac ..\test.o3\seomac.txo -loy > ..\text.o3\seomac.txt
..\masmx set ..\test.o3\set.txo -loy > ..\text.o3\set.txt
..\masmx shifty ..\test.o3\shifty.txo -loy > ..\text.o3\shifty.txt
..\masmx sim ..\test.o3\sim.txo -loy > ..\text.o3\sim.txt
..\masmx similar ..\test.o3\similar.txo -loy > ..\text.o3\similar.txt
..\masmx simple ..\test.o3\simple.txo -loy > ..\text.o3\simple.txt
..\masmx simpler ..\test.o3\simpler.txo -loy > ..\text.o3\simpler.txt
..\masmx simplify ..\test.o3\simplify.txo -loy > ..\text.o3\simplify.txt
..\masmx sky ..\test.o3\sky.txo -loy > ..\text.o3\sky.txt
..\masmx sleunig ..\test.o3\sleunig.txo -loy > ..\text.o3\sleunig.txt
..\masmx slingba ..\test.o3\slingba.txo -loy > ..\text.o3\slingba.txt
..\masmx slipcan ..\test.o3\slipcan.txo -loy > ..\text.o3\slipcan.txt
..\masmx slipshod ..\test.o3\slipshod.txo -loy > ..\text.o3\slipshod.txt
..\masmx smaragd ..\test.o3\smaragd.txo -loy > ..\text.o3\smaragd.txt
..\masmx smaragd1 ..\test.o3\smaragd1.txo -loy > ..\text.o3\smaragd1.txt
..\masmx smaragd7 ..\test.o3\smaragd7.txo -loy > ..\text.o3\smaragd7.txt
..\masmx snappie ..\test.o3\snappie.txo -loy > ..\text.o3\snappie.txt
..\masmx snippie ..\test.o3\snippie.txo -loy > ..\text.o3\snippie.txt
..\masmx somestuf ..\test.o3\somestuf.txo -loy > ..\text.o3\somestuf.txt
..\masmx somular ..\test.o3\somular.txo -loy > ..\text.o3\somular.txt
..\masmx soso ..\test.o3\soso.txo -loy > ..\text.o3\soso.txt
..\masmx spitz ..\test.o3\spitz.txo -loy > ..\text.o3\spitz.txt
..\masmx splativo ..\test.o3\splativo.txo -loy > ..\text.o3\splativo.txt
..\masmx sprativo ..\test.o3\sprativo.txo -loy > ..\text.o3\sprativo.txt
..\masmx squeeze ..\test.o3\squeeze.txo -loy > ..\text.o3\squeeze.txt
..\masmx stack ..\test.o3\stack.txo -loy > ..\text.o3\stack.txt
..\masmx stcomple ..\test.o3\stcomple.txo -loy > ..\text.o3\stcomple.txt
..\masmx steamer ..\test.o3\steamer.txo -loy > ..\text.o3\steamer.txt
..\masmx step1 ..\test.o3\step1.txo -loy > ..\text.o3\step1.txt
..\masmx step2 ..\test.o3\step2.txo -loy > ..\text.o3\step2.txt
..\masmx sterm ..\test.o3\sterm.txo -loy > ..\text.o3\sterm.txt
..\masmx strahl ..\test.o3\strahl.txo -loy > ..\text.o3\strahl.txt
..\masmx strahler ..\test.o3\strahler.txo -loy> ..\text.o3\strahler.txt
lstring -b ..\test.o3\strahler.txo ..\test.o3\strahler
..\masmx strain ..\test.o3\strain.txo -loy > ..\text.o3\strain.txt
..\masmx straling ..\test.o3\straling.txo -loy > ..\text.o3\straling.txt
lstring -b ..\test.o3\straling.txo ..\test.o3\straling
..\masmx strange ..\test.o3\strange.txo -loy > ..\text.o3\strange.txt
..\masmx strial1 ..\test.o3\strial1.txo -lo > ..\text.o3\strial1.txt
..\masmx strial2 ..\test.o3\strial2.txo -lo > ..\text.o3\strial2.txt
..\masmx strial3 ..\test.o3\strial3.txo -lo > ..\text.o3\strial3.txt
..\masmx strial4 ..\test.o3\strial4.txo -lo > ..\text.o3\strial4.txt
..\masmx strial5 ..\test.o3\strial5.txo -lo > ..\text.o3\strial5.txt
..\masmx strial6 ..\test.o3\strial6.txo -lo > ..\text.o3\strial6.txt
..\masmx stringli ..\test.o3\stringli.txo -loy > ..\text.o3\stringli.txt
..\masmx strugl5 ..\test.o3\strugl5.txo -loy > ..\text.o3\strugl5.txt
..\masmx stsimple ..\test.o3\stsimple.txo -loy > ..\text.o3\stsimple.txt
..\masmx stt ..\test.o3\stt.txo -loy > ..\text.o3\stt.txt
..\masmx subfi ..\test.o3\subfi.txo -loy > ..\text.o3\subfi.txt
..\masmx submarine ..\test.o3\submarine.txo -loy > ..\text.o3\submarine.txt
..\masmx subs1 ..\test.o3\subs1.txo -loy > ..\text.o3\subs1.txt
..\masmx suppose ..\test.o3\suppose.txo -loy > ..\text.o3\suppose.txt
..\masmx synonyms ..\test.o3\synonyms.txo -loy > ..\text.o3\synonyms.txt
..\masmx sysgo ..\test.o3\sysgo.txo -loy > ..\text.o3\sysgo.txt
..\masmx table ..\test.o3\table.txo -loy > ..\text.o3\table.txt
..\masmx tally2 ..\test.o3\tally2.txo -loy > ..\text.o3\tally2.txt
..\masmx tally3 ..\test.o3\tally3.txo -loy > ..\text.o3\tally3.txt
..\masmx tally4 ..\test.o3\tally4.txo -loy > ..\text.o3\tally4.txt
..\masmx tarsub ..\test.o3\tarsub.txo -loy > ..\text.o3\tarsub.txt
..\masmx tcp_in ..\test.o3\tcp_in.txo -loy > ..\text.o3\tcp_in.txt
..\masmx temper ..\test.o3\temper.txo -loy > ..\text.o3\temper.txt
..\masmx tempo ..\test.o3\tempo.txo -loy > ..\text.o3\tempo.txt
..\masmx term ..\test.o3\term.txo -loy > ..\text.o3\term.txt
..\masmx terrify1 ..\test.o3\terrify1.txo -loy > ..\text.o3\terrify1.txt
..\masmx terrify2 ..\test.o3\terrify2.txo -loy > ..\text.o3\terrify2.txt
..\masmx terrify3 ..\test.o3\terrify3.txo -loy > ..\text.o3\terrify3.txt
..\masmx these ..\test.o3\these.txo -loy > ..\text.o3\these.txt
..\masmx thing ..\test.o3\thing.txo -loy > ..\text.o3\thing.txt
..\masmx three4 ..\test.o3\three4.txo -loy > ..\text.o3\three4.txt
..\masmx thru ..\test.o3\thru.txo -loy > ..\text.o3\thru.txt
..\masmx times ..\test.o3\times.txo -loy > ..\text.o3\times.txt
..\masmx tisobar ..\test.o3\tisobar.txo -loy > ..\text.o3\tisobar.txt
..\masmx tla ..\test.o3\tla.txo -loy > ..\text.o3\tla.txt
..\masmx together ..\test.o3\together.txo -loy > ..\text.o3\together.txt
..\masmx tomp ..\test.o3\tomp.txo -loy > ..\text.o3\tomp.txt
..\masmx toozl ..\test.o3\toozl.txo -loy > ..\text.o3\toozl.txt
..\masmx trail ..\test.o3\trail.txo -loy > ..\text.o3\trail.txt
..\masmx trait ..\test.o3\trait.txo -loy > ..\text.o3\trait.txt
..\masmx trangle ..\test.o3\trangle.txo -loy > ..\text.o3\trangle.txt
..\masmx transport ..\test.o3\transport.txo -loy > ..\text.o3\transport.txt
..\masmx tranwys ..\test.o3\tranwys.txo -loy > ..\text.o3\tranwys.txt
..\masmx trau ..\test.o3\trau.txo -loy > ..\text.o3\trau.txt
..\masmx trbyte ..\test.o3\trbyte.txo -loy > ..\text.o3\trbyte.txt
..\masmx tree ..\test.o3\tree.txo -loy > ..\text.o3\tree.txt
..\masmx trees ..\test.o3\trees.txo -loy > ..\text.o3\trees.txt
..\masmx tribit ..\test.o3\tribit.txo -loy > ..\text.o3\tribit.txt
..\masmx tricki ..\test.o3\tricki.txo -loy > ..\text.o3\tricki.txt
..\masmx trip ..\test.o3\trip.txo -loy > ..\text.o3\trip.txt
..\masmx trivs ..\test.o3\trivs.txo -loy > ..\text.o3\trivs.txt
..\masmx trtab ..\test.o3\trtab.txo -loy > ..\text.o3\trtab.txt
..\masmx tryafew ..\test.o3\tryafew.txo -loy > ..\text.o3\tryafew.txt
..\masmx trysome ..\test.o3\trysome.txo -loy > ..\text.o3\trysome.txt
..\masmx tump ..\test.o3\tump.txo -loy > ..\text.o3\tump.txt
..\masmx tumpoon ..\test.o3\tumpoon.txo -loy > ..\text.o3\tumpoon.txt
..\masmx tumpshie ..\test.o3\tumpshie.txo -loy > ..\text.o3\tumpshie.txt
..\masmx twiggy ..\test.o3\twiggy.txo -loy > ..\text.o3\twiggy.txt
..\masmx tz ..\test.o3\tz.txo -loy > ..\text.o3\tz.txt
..\masmx uart ..\test.o3\uart.txo -loy > ..\text.o3\uart.txt
..\masmx udp_rxip ..\test.o3\udp_rxip.txo -loy > ..\text.o3\udp_rxip.txt
..\masmx updown ..\test.o3\updown.txo -loy > ..\text.o3\updown.txt
..\masmx using ..\test.o3\using.txo -loy > ..\text.o3\using.txt
..\masmx usinga ..\test.o3\usinga.txo -loy > ..\text.o3\usinga.txt
..\masmx usingb ..\test.o3\usingb.txo -loy > ..\text.o3\usingb.txt
..\masmx usingl ..\test.o3\usingl.txo -loy > ..\text.o3\usingl.txt
..\masmx usingpv ..\test.o3\usingpv.txo -loy > ..\text.o3\usingpv.txt
..\masmx usingr ..\test.o3\usingr.txo -loy > ..\text.o3\usingr.txt
..\masmx usingv ..\test.o3\usingv.txo -loy > ..\text.o3\usingv.txt
..\masmx utable ..\test.o3\utable.txo -loy > ..\text.o3\utable.txt
..\masmx uzactor ..\test.o3\uzactor.txo -loy > ..\text.o3\uzactor.txt
..\masmx v ..\test.o3\v.txo -loy > ..\text.o3\v.txt
..\masmx var ..\test.o3\var.txo -loy > ..\text.o3\var.txt
..\masmx vast ..\test.o3\vast.txo -lo > ..\text.o3\vast.txt
..\masmx vector ..\test.o3\vector.txo -loy > ..\text.o3\vector.txt
..\masmx viable ..\test.o3\viable.txo -loyI > ..\text.o3\viable.txt
..\masmx victim ..\test.o3\victim.txo -loy > ..\text.o3\victim.txt
..\masmx visobar ..\test.o3\visobar.txo -loy > ..\text.o3\visobar.txt
..\masmx vitest ..\test.o3\vitest.txo -loy > ..\text.o3\vitest.txt
..\masmx vitest2 ..\test.o3\vitest2.txo -loy > ..\text.o3\vitest2.txt
..\masmx vitest3 ..\test.o3\vitest3.txo -loy > ..\text.o3\vitest3.txt
..\masmx void ..\test.o3\void.txo -loy > ..\text.o3\void.txt
..\masmx vr ..\test.o3\vr.txo -loy > ..\text.o3\vr.txt
..\masmx vsimpl ..\test.o3\vsimpl.txo -loy > ..\text.o3\vsimpl.txt
..\masmx vsimpl2 ..\test.o3\vsimpl2.txo -loy > ..\text.o3\vsimpl2.txt
..\masmx vspace ..\test.o3\vspace.txo -loy > ..\text.o3\vspace.txt
..\masmx wanayooz ..\test.o3\wanayooz.txo -loy > ..\text.o3\wanayooz.txt
..\masmx watabout ..\test.o3\watabout.txo -loy > ..\text.o3\watabout.txt
..\masmx watslong ..\test.o3\watslong.txo -loy > ..\text.o3\watslong.txt
..\masmx weel ..\test.o3\weel.txo -loy > ..\text.o3\weel.txt
..\masmx welblech ..\test.o3\welblech.txo -loy > ..\text.o3\welblech.txt
..\masmx wellaugh ..\test.o3\wellaugh.txo -loy > ..\text.o3\wellaugh.txt
..\masmx wellfest ..\test.o3\wellfest.txo -loy > ..\text.o3\wellfest.txt
..\masmx why ..\test.o3\why.txo -loy > ..\text.o3\why.txt
..\masmx wibl ..\test.o3\wibl.txo -loy > ..\text.o3\wibl.txt
..\masmx wolverine ..\test.o3\wolverine.txo -loy > ..\text.o3\wolverine.txt
..\masmx woodbits ..\test.o3\woodbits.txo -loy > ..\text.o3\woodbits.txt
..\masmx worser ..\test.o3\worser.txo -loy > ..\text.o3\worser.txt
..\masmx wozita ..\test.o3\wozita.txo -loy > ..\text.o3\wozita.txt
..\masmx wyzat ..\test.o3\wyzat.txo -loy > ..\text.o3\wyzat.txt
..\masmx xtrem ..\test.o3\xtrem.txo -loy > ..\text.o3\xtrem.txt
..\masmx yanutha ..\test.o3\yanutha.txo -loy > ..\text.o3\yanutha.txt
..\masmx yoho ..\test.o3\yoho.txo -loy > ..\text.o3\yoho.txt
..\masmx yowl ..\test.o3\yowl.txo -loy > ..\text.o3\yowl.txt
..\masmx ytup ..\test.o3\ytup.txo -loy > ..\text.o3\ytup.txt
..\masmx zactor ..\test.o3\zactor.txo -loy > ..\text.o3\zactor.txt
..\masmx zibble ..\test.o3\zibble.txo -loy > ..\text.o3\zibble.txt
..\masmx zoto ..\test.o3\zoto.txo -loy > ..\text.o3\zoto.txt
..\masmx ztup ..\test.o3\ztup.txo -loy > ..\text.o3\ztup.txt
..\masmx alyat ..\test.o3\alyat.txo -loy > ..\text.o3\alyat.txt
..\masmx continu ..\test.o3\continu.txo -loy > ..\text.o3\continu.txt
..\masmx gap ..\test.o3\gap.txo -loy > ..\text.o3\gap.txt
..\masmx mikros ..\test.o3\mikros.txo -loy > ..\text.o3\mikros.txt
..\masmx bb ..\test.o3\bb.txo -loy > ..\text.o3\bb.txt
..\masmx blanquo ..\test.o3\blanquo.txo -loy > ..\text.o3\blanquo.txt
..\masmx cc ..\test.o3\cc.txo -loy > ..\text.o3\cc.txt
..\masmx strangely ..\test.o3\strangely.txo -loy > ..\text.o3\strangely.txt
..\masmx stretch ..\test.o3\stretch.txo -loy > ..\text.o3\stretch.txt
..\masmx wirr ..\test.o3\wirr.txo -loy > ..\text.o3\wirr.txt
..\masmx twinset ..\test.o3\twinset.txo -loy > ..\text.o3\twinset.txt
..\masmx dimsort ..\test.o3\dimsort.txo -loy > ..\text.o3\dimsort.txt
..\masmx notawdim ..\test.o3\notawdim.txo -loy > ..\text.o3\notawdim.txt

..\masmx hubert ..\test.o3\hubert.txo -loy > ..\text.o3\hubert.txt
..\masmx prango ..\test.o3\prango.txo -loy > ..\text.o3\prango.txt
..\masmx prango32 ..\test.o3\prango32.txo -loy > ..\text.o3\prango32.txt
..\masmx yasimi ..\test.o3\yasimi -loy > ..\text.o3\yasimi.txt
..\masmx yanamba ..\test.o3\yanamba -loy > ..\text.o3\yanamba.txt

..\masmx ldes2 ..\test.o3\ldes2 -loy > ..\text.o3\ldes2.txt
..\masmx a1 ..\test.o3\a1 -loy > ..\text.o3\a1.txt
..\masmx a1 ..\test.o3\a2 -locy > ..\text.o3\a2.txt
..\masmx a1 ..\test.o3\a3 -lozy > ..\text.o3\a3.txt
..\masmx a1 ..\test.o3\a4 -loczy > ..\text.o3\a4.txt
..\masmx reappear ..\test.o3\reappear -lnyo > ..\text.o3\reappear.txt

..\masmx quibble ..\test.o3\quibble -lynok > ..\text.o3\quibble.txt
..\masmx around ..\test.o3\around -loy > ..\text.o3\around.txt
..\masmx around ..\test.o3\around_wrong -loyE > ..\text.o3\around_wrong.txt
..\masmx scala ..\test.o3\scala -loy > ..\text.o3\scala.txt
..\masmx scala ..\test.o3\scala_wrong -loyE > ..\text.o3\scala_wrong.txt
..\masmx floating ..\test.o3\floating -loy > ..\text.o3\floating.txt
..\masmx unary ..\test.o3\unary -loy > ..\text.o3\unary.txt
..\masmx unary2 ..\test.o3\unary2 -loy > ..\text.o3\unary2.txt
..\masmx exporter ..\test.o3\exporter -loy > ..\text.o3\exporter.txt
..\masmx norty ..\test.o3\norty -loy > ..\text.o3\norty.txt
..\masmx tessuele ..\test.o3\tessuele -loy > ..\text.o3\tessuele.txt
..\masmx gessuele ..\test.o3\gessuele -loy > ..\text.o3\gessuele.txt
..\masmx noczeesc ..\test.o3\noczeesc -loy > ..\text.o3\noczeesc.txt
..\masmx o ..\test.o3\o -loy > ..\text.o3\o.txt
..\masmx questit ..\test.o3\questit -lyok > ..\text.o3\questit.txt
..\masmx stamp ..\test.o3\stamp -lyok > ..\text.o3\stamp.txt
..\masmx nuficsee ..\test.o3\nuficsee -lyok > ..\text.o3\nuficsee.txt
..\masmx paving ..\test.o3\paving -lyok > ..\text.o3\paving.txt
..\masmx relarith ..\test.o3\relarith -lyok > ..\text.o3\relarith.txt
..\masmx brachat ..\test.o3\brachat -lyok > ..\text.o3\brachat.txt
..\masmx mfeuille ..\test.o3\mfeuille -lyok > ..\text.o3\mfeuille.txt
..\masmx suffix ..\test.o3\suffix -lyok > ..\text.o3\suffix.txt
..\masmx celia ..\test.o3\celia -lyok > ..\text.o3\celia.txt
..\masmx xqt ..\test.o3\xqt -lyok > ..\text.o3\xqt.txt
..\masmx globule1 ..\test.o3\globule1 -lyok > ..\text.o3\globule1.txt
..\masmx globule2 ..\test.o3\globule2 -lyok > ..\text.o3\globule2.txt
..\masmx globule3 ..\test.o3\globule3 -lyok > ..\text.o3\globule3.txt
..\masmx globule4 ..\test.o3\globule4 -lyok > ..\text.o3\globule4.txt
..\masmx globules ..\test.o3\globules -lyok > ..\text.o3\globules.txt
..\masmx garbules ..\test.o3\garbules -lyok > ..\text.o3\garbules.txt
..\masmx ragaline ..\test.o3\ragaline -lyok > ..\text.o3\ragaline.txt
..\masmx forward ..\test.o3\forward -lyok > ..\text.o3\forward.txt
..\masmx macaroon ..\test.o3\macaroon -lyok > ..\text.o3\macaroon.txt
..\masmx crusti ..\test.o3\crusti -lyok > ..\text.o3\crusti.txt
..\masmx afar ..\test.o3\afar -lyok > ..\text.o3\afar.txt
..\masmx seriozha ..\test.o3\seriozha -lyok > ..\text.o3\seriozha.txt
..\masmx leriozha ..\test.o3\leriozha -lyok > ..\text.o3\leriozha.txt
..\masmx skillin ..\test.o3\skillin -lyok > ..\text.o3\skillin.txt
..\masmx nodcodl ..\test.o3\nodcodl -lyok > ..\text.o3\nodcodl.txt
..\masmx afar ..\test.o3\afar -lyok > ..\text.o3\afar.txt
..\masmx meringue ..\test.o3\meringue -lyok > ..\text.o3\meringue.txt
..\masmx r2xample ..\test.o3\r2xample -lyok > ..\text.o3\r2xample.txt
..\masmx boolean ..\test.o3\boolean -lyok > ..\text.o3\boolean.txt
..\masmx brin ..\test.o3\brin -lyok > ..\text.o3\brin.txt
..\masmx s2double ..\test.o3\s2double -lyok > ..\text.o3\s2double.txt
..\masmx r3xample ..\test.o3\r3xample -lyok > ..\text.o3\r3xample.txt
..\masmx babble ..\test.o3\babble -lyok > ..\text.o3\babble.txt
..\masmx record ..\test.o3\record -lyok > ..\text.o3\record.txt
..\masmx but ..\test.o3\but -lyok > ..\text.o3\but.txt
..\masmx moreover ..\test.o3\moreover -lyok > ..\text.o3\moreover.txt
..\masmx routines ..\test.o3\routines -lyok > ..\text.o3\routines.txt
..\masmx sockets ..\test.o3\sockets -lyok > ..\text.o3\sockets.txt
..\masmx i2string ..\test.o3\i2string -lyok > ..\text.o3\i2string.txt
..\masmx zcp ..\test.o3\zcp -lyok > ..\text.o3\zcp.txt
..\masmx gradual ..\test.o3\gradual -lyok > ..\text.o3\gradual.txt
..\masmx quickly ..\test.o3\quickly -lyok > ..\text.o3\quickly.txt
..\masmx signify ..\test.o3\signify -lyok > ..\text.o3\signify.txt
..\masmx paxels ..\test.o3\paxels -lyok > ..\text.o3\paxels.txt
..\masmx fieee754 ..\test.o3\fieee754 -lyok > ..\text.o3\fieee754
..\masmx paxout ..\test.o3\paxout -lyok > ..\text.o3\paxout.txt
..\masmx paxel16 ..\test.o3\paxel16 -lyok > ..\text.o3\paxel16.txt
..\masmx gardenia ..\test.o3\gardenia -lyok > ..\text.o3\gardenia.txt
..\masmx trag ..\test.o3\trag -lyok > ..\text.o3\trag.txt
..\masmx raft ..\test.o3\raft -lyok > ..\text.o3\raft.txt
..\masmx craft ..\test.o3\craft -lyok > ..\text.o3\craft.txt
..\masmx funs ..\test.o3\funs -lyok > ..\text.o3\funs.txt
..\masmx aehnlich ..\test.o3\aehnlich.txo -lyok > ..\text.o3\aehnlich.txt
..\masmx overlap ..\test.o3\overlap.txo -lyok > ..\text.o3\overlap.txt
..\masmx pxar ..\test.o3\pxar -lyok > ..\text.o3\pxar.txt
..\masmx targ ..\test.o3\targ -lyok > ..\text.o3\targ.txt
..\masmx tarq ..\test.o3\tarq -lyok > ..\text.o3\tarq.txt
..\masmx rounders ..\test.o3\roundere -lyokE > ..\text.o3\roundere.txt
..\masmx rounders ..\test.o3\rounderg -lyokG > ..\text.o3\rounderg.txt
..\masmx roundown ..\test.o3\roundown -lyok > ..\text.o3\roundown.txt

call ..\w32_dos.bat\linkpart
call ..\w32_dos.bat\coldfire
call ..\w32_dos.bat\ppc_kern

