del ..\test.zo3\*.*
del ..\text.zo3\*.*
..\masmx a1 ..\test.zo3\a2 -z > ..\text.zo3\a2.txo
..\masmx a1 ..\test.zo3\a3 -c > ..\text.zo3\a3.txo
..\masmx a1 ..\test.zo3\a4 -zc > ..\text.zo3\a4.txo
..\masmz 1101 -lno ..\test.zo3\1101 > ..\text.zo3\1101.txt
..\masmz 1103 -lno ..\test.zo3\1103 > ..\text.zo3\1103.txt
..\masmz 14 -lno ..\test.zo3\14 > ..\text.zo3\14.txt
..\masmz 16lib24 -lno ..\test.zo3\16lib24 > ..\text.zo3\16lib24.txt
..\masmz 1st -lno ..\test.zo3\1st > ..\text.zo3\1st.txt
..\masmz 2468 -lno ..\test.zo3\2468 > ..\text.zo3\2468.txt
..\masmz 2manif -lno ..\test.zo3\2manif > ..\text.zo3\2manif.txt
..\masmz 2nd -lno ..\test.zo3\2nd > ..\text.zo3\2nd.txt
..\masmz 3byte -lno ..\test.zo3\3byte > ..\text.zo3\3byte.txt
..\masmz 3rd -lno ..\test.zo3\3rd > ..\text.zo3\3rd.txt
..\masmz @ -lno ..\test.zo3\@ > ..\text.zo3\@.txt
..\masmz @1 -lno ..\test.zo3\@1 > ..\text.zo3\@1.txt
..\masmz a1 -lno ..\test.zo3\a1 > ..\text.zo3\a1.txt
..\masmz abit -lno ..\test.zo3\abit > ..\text.zo3\abit.txt
..\masmz about -lno ..\test.zo3\about > ..\text.zo3\about.txt
..\masmz addo -lno ..\test.zo3\addo > ..\text.zo3\addo.txt
..\masmz addu -lno ..\test.zo3\addu > ..\text.zo3\addu.txt
..\masmz addz -lno ..\test.zo3\addz > ..\text.zo3\addz.txt
..\masmz adsomor1 -lno ..\test.zo3\adsomor1 > ..\text.zo3\adsomor1.txt
..\masmz adsomor2 -lno ..\test.zo3\adsomor2 > ..\text.zo3\adsomor2.txt
..\masmz adsomor3 -lno ..\test.zo3\adsomor3 > ..\text.zo3\adsomor3.txt
..\masmz adsomor4 -lno ..\test.zo3\adsomor4 > ..\text.zo3\adsomor4.txt
..\masmz afile -lno ..\test.zo3\afile > ..\text.zo3\afile.txt
..\masmz aglimpse -lno ..\test.zo3\aglimpse > ..\text.zo3\aglimpse.txt
..\masmz agranoy -lno ..\test.zo3\agranoy > ..\text.zo3\agranoy.txt
..\masmz ajoko -lno ..\test.zo3\ajoko > ..\text.zo3\ajoko.txt
..\masmz algebra -lno ..\test.zo3\algebra > ..\text.zo3\algebra.txt
..\masmz align -lno ..\test.zo3\align > ..\text.zo3\align.txt
..\masmz allyoobl -lno ..\test.zo3\allyoobl > ..\text.zo3\allyoobl.txt
..\masmz alyat -lno ..\test.zo3\alyat > ..\text.zo3\alyat.txt
..\masmz anew -lno ..\test.zo3\anew > ..\text.zo3\anew.txt
..\masmz another -lno ..\test.zo3\another > ..\text.zo3\another.txt
..\masmz aon -lno ..\test.zo3\aon > ..\text.zo3\aon.txt
..\masmz app -lno ..\test.zo3\app > ..\text.zo3\app.txt
..\masmz app1 -lno ..\test.zo3\app1 > ..\text.zo3\app1.txt
..\masmz app2 -lno ..\test.zo3\app2 > ..\text.zo3\app2.txt
..\masmz app3 -lno ..\test.zo3\app3 > ..\text.zo3\app3.txt
..\masmz app4 -lno ..\test.zo3\app4 > ..\text.zo3\app4.txt
..\masmz app7 -lno ..\test.zo3\app7 > ..\text.zo3\app7.txt
..\masmz appoint -lno ..\test.zo3\appoint > ..\text.zo3\appoint.txt
..\masmz approx -lno ..\test.zo3\approx > ..\text.zo3\approx.txt
..\masmz aqt -lno ..\test.zo3\aqt > ..\text.zo3\aqt.txt
..\masmz arm -lno ..\test.zo3\arm > ..\text.zo3\arm.txt
..\masmz asample -lno ..\test.zo3\asample > ..\text.zo3\asample.txt
..\masmz atest -lno ..\test.zo3\atest > ..\text.zo3\atest.txt
..\masmz attempt -lno ..\test.zo3\attempt > ..\text.zo3\attempt.txt
..\masmz avenu -lno ..\test.zo3\avenu > ..\text.zo3\avenu.txt
..\masmz awail -lno ..\test.zo3\awail > ..\text.zo3\awail.txt
..\masmz awain -lno ..\test.zo3\awain > ..\text.zo3\awain.txt
..\masmz away -lno ..\test.zo3\away > ..\text.zo3\away.txt
..\masmz awkward -lno ..\test.zo3\awkward > ..\text.zo3\awkward.txt
..\masmz azuli -lno ..\test.zo3\azuli > ..\text.zo3\azuli.txt
..\masmz b -lno ..\test.zo3\b > ..\text.zo3\b.txt
..\masmz badly -lno ..\test.zo3\badly > ..\text.zo3\badly.txt
..\masmz balance -lno ..\test.zo3\balance > ..\text.zo3\balance.txt
..\masmz banks -lno ..\test.zo3\banks > ..\text.zo3\banks.txt
..\masmz banks2 -lno ..\test.zo3\banks2 > ..\text.zo3\banks2.txt
..\masmz basal1 -lno ..\test.zo3\basal1 > ..\text.zo3\basal1.txt
..\masmz basalall -lno ..\test.zo3\basalall > ..\text.zo3\basalall.txt
..\masmz basalone -lno ..\test.zo3\basalone > ..\text.zo3\basalone.txt
..\masmz basalthr -lno ..\test.zo3\basalthr > ..\text.zo3\basalthr.txt
..\masmz basaltwo -lno ..\test.zo3\basaltwo > ..\text.zo3\basaltwo.txt
..\masmz basis -lno ..\test.zo3\basis > ..\text.zo3\basis.txt
..\masmz bdw -lno ..\test.zo3\bdw > ..\text.zo3\bdw.txt
..\masmz bequf -lno ..\test.zo3\bequf > ..\text.zo3\bequf.txt
..\masmz big -lno ..\test.zo3\big > ..\text.zo3\big.txt
..\masmz big48 -lno ..\test.zo3\big48 > ..\text.zo3\big48.txt
..\masmz bitsof -lno ..\test.zo3\bitsof > ..\text.zo3\bitsof.txt
..\masmz blanks -lno ..\test.zo3\blanks > ..\text.zo3\blanks.txt
..\masmz blanquo -lno ..\test.zo3\blanquo > ..\text.zo3\blanquo.txt
..\masmz bogle -lno ..\test.zo3\bogle > ..\text.zo3\bogle.txt
..\masmz bonkers -lno ..\test.zo3\bonkers > ..\text.zo3\bonkers.txt
..\masmz bounded -lno ..\test.zo3\bounded > ..\text.zo3\bounded.txt
..\masmz boxy -lno ..\test.zo3\boxy > ..\text.zo3\boxy.txt
..\masmz bqt -lno ..\test.zo3\bqt > ..\text.zo3\bqt.txt
..\masmz brickie -lno ..\test.zo3\brickie > ..\text.zo3\brickie.txt
..\masmz btest -lno ..\test.zo3\btest > ..\text.zo3\btest.txt
..\masmz buy_sell -lno ..\test.zo3\buy_sell > ..\text.zo3\buy_sell.txt
..\masmz bway -lno ..\test.zo3\bway > ..\text.zo3\bway.txt
..\masmz cancan -lno ..\test.zo3\cancan > ..\text.zo3\cancan.txt
..\masmz carryon -lno ..\test.zo3\carryon > ..\text.zo3\carryon.txt
..\masmz case -lno ..\test.zo3\case > ..\text.zo3\case.txt
..\masmz cases -lno ..\test.zo3\cases > ..\text.zo3\cases.txt
..\masmz cc -lno ..\test.zo3\cc > ..\text.zo3\cc.txt
..\masmz cdml -lno ..\test.zo3\cdml > ..\text.zo3\cdml.txt
..\masmz cheese -lno ..\test.zo3\cheese > ..\text.zo3\cheese.txt
..\masmz code -lno ..\test.zo3\code > ..\text.zo3\code.txt
..\masmz commas -lno ..\test.zo3\commas > ..\text.zo3\commas.txt
..\masmz comment -lno ..\test.zo3\comment > ..\text.zo3\comment.txt
..\masmz comment1 -lno ..\test.zo3\comment1 > ..\text.zo3\comment1.txt
..\masmz compo -lno ..\test.zo3\compo > ..\text.zo3\compo.txt
..\masmz compose -lno ..\test.zo3\compose > ..\text.zo3\compose.txt
..\masmz constanz -lno ..\test.zo3\constanz > ..\text.zo3\constanz.txt
..\masmz context -lno ..\test.zo3\context > ..\text.zo3\context.txt
..\masmz continu -lno ..\test.zo3\continu > ..\text.zo3\continu.txt
..\masmz contrary -lno ..\test.zo3\contrary > ..\text.zo3\contrary.txt
..\masmz controb2 -lno ..\test.zo3\controb2 > ..\text.zo3\controb2.txt
..\masmz control1 -lno ..\test.zo3\control1 > ..\text.zo3\control1.txt
..\masmz control2 -lno ..\test.zo3\control2 > ..\text.zo3\control2.txt
..\masmz control3 -lno ..\test.zo3\control3 > ..\text.zo3\control3.txt
..\masmz control4 -lno ..\test.zo3\control4 > ..\text.zo3\control4.txt
..\masmz cqt -lno ..\test.zo3\cqt > ..\text.zo3\cqt.txt
..\masmz crabble -lno ..\test.zo3\crabble > ..\text.zo3\crabble.txt
..\masmz ctest -lno ..\test.zo3\ctest > ..\text.zo3\ctest.txt
..\masmz d -lno ..\test.zo3\d > ..\text.zo3\d.txt
..\masmz dd -lno ..\test.zo3\dd > ..\text.zo3\dd.txt
..\masmz ddd -lno ..\test.zo3\ddd > ..\text.zo3\ddd.txt
..\masmz dde -lno ..\test.zo3\dde > ..\text.zo3\dde.txt
..\masmz decode -lno ..\test.zo3\decode > ..\text.zo3\decode.txt
..\masmz deep -lno ..\test.zo3\deep > ..\text.zo3\deep.txt
..\masmz deep_lit -lno ..\test.zo3\deep_lit > ..\text.zo3\deep_lit.txt
..\masmz demo1 -lno ..\test.zo3\demo1 > ..\text.zo3\demo1.txt
..\masmz demo2 -lno ..\test.zo3\demo2 > ..\text.zo3\demo2.txt
..\masmz demo3 -lno ..\test.zo3\demo3 > ..\text.zo3\demo3.txt
..\masmz detune -lno ..\test.zo3\detune > ..\text.zo3\detune.txt
..\masmz dfp -lno ..\test.zo3\dfp > ..\text.zo3\dfp.txt
..\masmz dfp16 -lno ..\test.zo3\dfp16 > ..\text.zo3\dfp16.txt
..\masmz diffi -lno ..\test.zo3\diffi > ..\text.zo3\diffi.txt
..\masmz dl -lno ..\test.zo3\dl > ..\text.zo3\dl.txt
..\masmz do -lno ..\test.zo3\do > ..\text.zo3\do.txt
..\masmz do1 -lno ..\test.zo3\do1 > ..\text.zo3\do1.txt
..\masmz do2 -lno ..\test.zo3\do2 > ..\text.zo3\do2.txt
..\masmz do3 -lno ..\test.zo3\do3 > ..\text.zo3\do3.txt
..\masmz do32 -lno ..\test.zo3\do32 > ..\text.zo3\do32.txt
..\masmz do4 -lno ..\test.zo3\do4 > ..\text.zo3\do4.txt
..\masmz dogma -lno ..\test.zo3\dogma > ..\text.zo3\dogma.txt
..\masmz dollar -lno ..\test.zo3\dollar > ..\text.zo3\dollar.txt
..\masmz dollar1 -lno ..\test.zo3\dollar1 > ..\text.zo3\dollar1.txt
..\masmz dormouse -lno ..\test.zo3\dormouse > ..\text.zo3\dormouse.txt
..\masmz dotable -lno ..\test.zo3\dotable > ..\text.zo3\dotable.txt
..\masmz drat -lno ..\test.zo3\drat > ..\text.zo3\drat.txt
..\masmz dudif -lno ..\test.zo3\dudif > ..\text.zo3\dudif.txt
..\masmz dumexa -lno ..\test.zo3\dumexa > ..\text.zo3\dumexa.txt
..\masmz dup -lno ..\test.zo3\dup > ..\text.zo3\dup.txt
..\masmz dx -lno ..\test.zo3\dx > ..\text.zo3\dx.txt
..\masmz edit -lno ..\test.zo3\edit > ..\text.zo3\edit.txt
..\masmz elboaze -lno ..\test.zo3\elboaze > ..\text.zo3\elboaze.txt
..\masmz elf -lno ..\test.zo3\elf > ..\text.zo3\elf.txt
..\masmz entrada -lno ..\test.zo3\entrada > ..\text.zo3\entrada.txt
..\masmz environ -lno ..\test.zo3\environ > ..\text.zo3\environ.txt
..\masmz eq -lno ..\test.zo3\eq > ..\text.zo3\eq.txt
..\masmz equf -lno ..\test.zo3\equf > ..\text.zo3\equf.txt
..\masmz equf32 -lno ..\test.zo3\equf32 > ..\text.zo3\equf32.txt
..\masmz expo -lno ..\test.zo3\expo > ..\text.zo3\expo.txt
..\masmz export -lno ..\test.zo3\export > ..\text.zo3\export.txt
..\masmz f -lno ..\test.zo3\f > ..\text.zo3\f.txt
..\masmz f2f -lno ..\test.zo3\f2f > ..\text.zo3\f2f.txt
..\masmz factor -lno ..\test.zo3\factor > ..\text.zo3\factor.txt
..\masmz fames -lno ..\test.zo3\fames > ..\text.zo3\fames.txt
..\masmz fatalp -lno ..\test.zo3\fatalp > ..\text.zo3\fatalp.txt
..\masmz feelup -lno ..\test.zo3\feelup > ..\text.zo3\feelup.txt
..\masmz fff -lno ..\test.zo3\fff > ..\text.zo3\fff.txt
..\masmz flags -lno ..\test.zo3\flags > ..\text.zo3\flags.txt
..\masmz forgot -lno ..\test.zo3\forgot > ..\text.zo3\forgot.txt
..\masmz forjoy -lno ..\test.zo3\forjoy > ..\text.zo3\forjoy.txt
..\masmz form -lno ..\test.zo3\form > ..\text.zo3\form.txt
..\masmz fp -lno ..\test.zo3\fp > ..\text.zo3\fp.txt
..\masmz fp32 -lno ..\test.zo3\fp32 > ..\text.zo3\fp32.txt
..\masmz fpsize -lno ..\test.zo3\fpsize > ..\text.zo3\fpsize.txt
..\masmz fptest -lno ..\test.zo3\fptest > ..\text.zo3\fptest.txt
..\masmz fptestu -lno ..\test.zo3\fptestu > ..\text.zo3\fptestu.txt
..\masmz fpx -lno ..\test.zo3\fpx > ..\text.zo3\fpx.txt
..\masmz fragment -lno ..\test.zo3\fragment > ..\text.zo3\fragment.txt
..\masmz frame2 -lno ..\test.zo3\frame2 > ..\text.zo3\frame2.txt
..\masmz fref -lno ..\test.zo3\fref > ..\text.zo3\fref.txt
..\masmz frung -lno ..\test.zo3\frung > ..\text.zo3\frung.txt
..\masmz fs -lno ..\test.zo3\fs > ..\text.zo3\fs.txt
..\masmz fs32 -lno ..\test.zo3\fs32 > ..\text.zo3\fs32.txt
..\masmz fs48 -lno ..\test.zo3\fs48 > ..\text.zo3\fs48.txt
..\masmz further -lno ..\test.zo3\further > ..\text.zo3\further.txt
..\masmz fx -lno ..\test.zo3\fx > ..\text.zo3\fx.txt
..\masmz fzero -lno ..\test.zo3\fzero > ..\text.zo3\fzero.txt
..\masmz gap -lno ..\test.zo3\gap > ..\text.zo3\gap.txt
..\masmz general -lno ..\test.zo3\general > ..\text.zo3\general.txt
..\masmz gfactor -lno ..\test.zo3\gfactor > ..\text.zo3\gfactor.txt
..\masmz gfar -lno ..\test.zo3\gfar > ..\text.zo3\gfar.txt
..\masmz gflo -lno ..\test.zo3\gflo > ..\text.zo3\gflo.txt
..\masmz gframe2 -lno ..\test.zo3\gframe2 > ..\text.zo3\gframe2.txt
..\masmz gfurther -lno ..\test.zo3\gfurther > ..\text.zo3\gfurther.txt
..\masmz goodbit -lno ..\test.zo3\goodbit > ..\text.zo3\goodbit.txt
..\masmz grade -lno ..\test.zo3\grade > ..\text.zo3\grade.txt
..\masmz gram -lno ..\test.zo3\gram > ..\text.zo3\gram.txt
..\masmz grobags -lno ..\test.zo3\grobags > ..\text.zo3\grobags.txt
..\masmz gross -lno ..\test.zo3\gross > ..\text.zo3\gross.txt
..\masmz grum -lno ..\test.zo3\grum > ..\text.zo3\grum.txt
..\masmz gscale22 -lno ..\test.zo3\gscale22 > ..\text.zo3\gscale22.txt
..\masmz gscale23 -lno ..\test.zo3\gscale23 > ..\text.zo3\gscale23.txt
..\masmz gscale24 -lno ..\test.zo3\gscale24 > ..\text.zo3\gscale24.txt
..\masmz gsoso -lno ..\test.zo3\gsoso > ..\text.zo3\gsoso.txt
..\masmz gworser -lno ..\test.zo3\gworser > ..\text.zo3\gworser.txt
..\masmz gwyllmp -lno ..\test.zo3\gwyllmp > ..\text.zo3\gwyllmp.txt
..\masmz gzactor -lno ..\test.zo3\gzactor > ..\text.zo3\gzactor.txt
..\masmz haive -lno ..\test.zo3\haive > ..\text.zo3\haive.txt
..\masmz handfull -lno ..\test.zo3\handfull > ..\text.zo3\handfull.txt
..\masmz hangobar -lno ..\test.zo3\hangobar > ..\text.zo3\hangobar.txt
..\masmz hflo -lno ..\test.zo3\hflo > ..\text.zo3\hflo.txt
..\masmz high -lno ..\test.zo3\high > ..\text.zo3\high.txt
..\masmz hinge -lno ..\test.zo3\hinge > ..\text.zo3\hinge.txt
..\masmz howmany -lno ..\test.zo3\howmany > ..\text.zo3\howmany.txt
..\masmz howslow -lno ..\test.zo3\howslow > ..\text.zo3\howslow.txt
..\masmz hubert -lno ..\test.zo3\hubert > ..\text.zo3\hubert.txt
..\masmz hwis -lno ..\test.zo3\hwis > ..\text.zo3\hwis.txt
..\masmz ican -lno ..\test.zo3\ican > ..\text.zo3\ican.txt
..\masmz ieee754 -lno ..\test.zo3\ieee754 > ..\text.zo3\ieee754.txt
..\masmz ieee754s -lno ..\test.zo3\ieee754s > ..\text.zo3\ieee754s.txt
..\masmz ieeef -lno ..\test.zo3\ieeef > ..\text.zo3\ieeef.txt
..\masmz if -lno ..\test.zo3\if > ..\text.zo3\if.txt
..\masmz iffy -lno ..\test.zo3\iffy > ..\text.zo3\iffy.txt
..\masmz ifp -lno ..\test.zo3\ifp > ..\text.zo3\ifp.txt
..\masmz ifwise -lno ..\test.zo3\ifwise > ..\text.zo3\ifwise.txt
..\masmz iii -lno ..\test.zo3\iii > ..\text.zo3\iii.txt
..\masmz immediat -lno ..\test.zo3\immediat > ..\text.zo3\immediat.txt
..\masmz import -lno ..\test.zo3\import > ..\text.zo3\import.txt
..\masmz inc -lno ..\test.zo3\inc > ..\text.zo3\inc.txt
..\masmz inc1 -lno ..\test.zo3\inc1 > ..\text.zo3\inc1.txt
..\masmz inc2 -lno ..\test.zo3\inc2 > ..\text.zo3\inc2.txt
..\masmz inc3 -lno ..\test.zo3\inc3 > ..\text.zo3\inc3.txt
..\masmz info -lno ..\test.zo3\info > ..\text.zo3\info.txt
..\masmz inside -lno ..\test.zo3\inside > ..\text.zo3\inside.txt
..\masmz intrepid -lno ..\test.zo3\intrepid > ..\text.zo3\intrepid.txt
..\masmz intune -lno ..\test.zo3\intune > ..\text.zo3\intune.txt
..\masmz iscale1 -lno ..\test.zo3\iscale1 > ..\text.zo3\iscale1.txt
..\masmz iscale2 -lno ..\test.zo3\iscale2 > ..\text.zo3\iscale2.txt
..\masmz iscale3 -lno ..\test.zo3\iscale3 > ..\text.zo3\iscale3.txt
..\masmz iside1 -lno ..\test.zo3\iside1 > ..\text.zo3\iside1.txt
..\masmz isobar -lno ..\test.zo3\isobar > ..\text.zo3\isobar.txt
..\masmz isobar1 -lno ..\test.zo3\isobar1 > ..\text.zo3\isobar1.txt
..\masmz isthatso -lno ..\test.zo3\isthatso > ..\text.zo3\isthatso.txt
..\masmz j2 -lno ..\test.zo3\j2 > ..\text.zo3\j2.txt
..\masmz j3 -lno ..\test.zo3\j3 > ..\text.zo3\j3.txt
..\masmz justname -lno ..\test.zo3\justname > ..\text.zo3\justname.txt
..\masmz keeptry -lno ..\test.zo3\keeptry > ..\text.zo3\keeptry.txt
..\masmz kette -lno ..\test.zo3\kette > ..\text.zo3\kette.txt
..\masmz keyword -lno ..\test.zo3\keyword > ..\text.zo3\keyword.txt
..\masmz l -lno ..\test.zo3\l > ..\text.zo3\l.txt
..\masmz labels -lno ..\test.zo3\labels > ..\text.zo3\labels.txt
..\masmz langobar -lno ..\test.zo3\langobar > ..\text.zo3\langobar.txt
..\masmz largle -lno ..\test.zo3\largle > ..\text.zo3\largle.txt
..\masmz lcodes -lno ..\test.zo3\lcodes > ..\text.zo3\lcodes.txt
..\masmz ldes -lno ..\test.zo3\ldes > ..\text.zo3\ldes.txt
..\masmz ldes2 -lno ..\test.zo3\ldes2 > ..\text.zo3\ldes2.txt
..\masmz leggy -lno ..\test.zo3\leggy > ..\text.zo3\leggy.txt
..\masmz letsbya -lno ..\test.zo3\letsbya > ..\text.zo3\letsbya.txt
..\masmz liable -lno ..\test.zo3\liable > ..\text.zo3\liable.txt
..\masmz linitup -lno ..\test.zo3\linitup > ..\text.zo3\linitup.txt
..\masmz lit -lno ..\test.zo3\lit > ..\text.zo3\lit.txt
..\masmz lit8051 -lno ..\test.zo3\lit8051 > ..\text.zo3\lit8051.txt
..\masmz literal -lno ..\test.zo3\literal > ..\text.zo3\literal.txt
..\masmz little -lno ..\test.zo3\little > ..\text.zo3\little.txt
..\masmz ll -lno ..\test.zo3\ll > ..\text.zo3\ll.txt
..\masmz ll2 -lno ..\test.zo3\ll2 > ..\text.zo3\ll2.txt
..\masmz ll3 -lno ..\test.zo3\ll3 > ..\text.zo3\ll3.txt
..\masmz ll4 -lno ..\test.zo3\ll4 > ..\text.zo3\ll4.txt
..\masmz ll5 -lno ..\test.zo3\ll5 > ..\text.zo3\ll5.txt
..\masmz ll5abs -lno ..\test.zo3\ll5abs > ..\text.zo3\ll5abs.txt
..\masmz ll6 -lno ..\test.zo3\ll6 > ..\text.zo3\ll6.txt
..\masmz ll6abs -lno ..\test.zo3\ll6abs > ..\text.zo3\ll6abs.txt
..\masmz lodation -lno ..\test.zo3\lodation > ..\text.zo3\lodation.txt
..\masmz longjump -lno ..\test.zo3\longjump > ..\text.zo3\longjump.txt
..\masmz loopy -lno ..\test.zo3\loopy > ..\text.zo3\loopy.txt
..\masmz lorg -lno ..\test.zo3\lorg > ..\text.zo3\lorg.txt
..\masmz lorgle -lno ..\test.zo3\lorgle > ..\text.zo3\lorgle.txt
..\masmz luri -lno ..\test.zo3\luri > ..\text.zo3\luri.txt
..\masmz m -lno ..\test.zo3\m > ..\text.zo3\m.txt
..\masmz mafcol1 -lno ..\test.zo3\mafcol1 > ..\text.zo3\mafcol1.txt
..\masmz mangle -lno ..\test.zo3\mangle > ..\text.zo3\mangle.txt
..\masmz manif -lno ..\test.zo3\manif > ..\text.zo3\manif.txt
..\masmz many -lno ..\test.zo3\many > ..\text.zo3\many.txt
..\masmz map -lno ..\test.zo3\map > ..\text.zo3\map.txt
..\masmz map1 -lno ..\test.zo3\map1 > ..\text.zo3\map1.txt
..\masmz map10 -lno ..\test.zo3\map10 > ..\text.zo3\map10.txt
..\masmz map10g -lno ..\test.zo3\map10g > ..\text.zo3\map10g.txt
..\masmz map11 -lno ..\test.zo3\map11 > ..\text.zo3\map11.txt
..\masmz map12 -lno ..\test.zo3\map12 > ..\text.zo3\map12.txt
..\masmz map15 -lno ..\test.zo3\map15 > ..\text.zo3\map15.txt
..\masmz map2 -lno ..\test.zo3\map2 > ..\text.zo3\map2.txt
..\masmz map3 -lno ..\test.zo3\map3 > ..\text.zo3\map3.txt
..\masmz map4 -lno ..\test.zo3\map4 > ..\text.zo3\map4.txt
..\masmz map5 -lno ..\test.zo3\map5 > ..\text.zo3\map5.txt
..\masmz map6 -lno ..\test.zo3\map6 > ..\text.zo3\map6.txt
..\masmz map7 -lno ..\test.zo3\map7 > ..\text.zo3\map7.txt
..\masmz map7g -lno ..\test.zo3\map7g > ..\text.zo3\map7g.txt
..\masmz map8 -lno ..\test.zo3\map8 > ..\text.zo3\map8.txt
..\masmz map8g -lno ..\test.zo3\map8g > ..\text.zo3\map8g.txt
..\masmz map9 -lno ..\test.zo3\map9 > ..\text.zo3\map9.txt
..\masmz mary -lno ..\test.zo3\mary > ..\text.zo3\mary.txt
..\masmz masm7 -lno ..\test.zo3\masm7 > ..\text.zo3\masm7.txt
..\masmz maxfloat -lno ..\test.zo3\maxfloat > ..\text.zo3\maxfloat.txt
..\masmz maxmaxi -lnoz ..\test.zo3\maxmaxi > ..\text.zo3\maxmaxi.txt
..\masmz maxtini -lnoz ..\test.zo3\maxtini > ..\text.zo3\maxtini.txt
..\masmz maxwini -lnoz ..\test.zo3\maxwini > ..\text.zo3\maxwini.txt
..\masmz mikros -lno ..\test.zo3\mikros > ..\text.zo3\mikros.txt
..\masmz ml -lno ..\test.zo3\ml > ..\text.zo3\ml.txt
..\masmz mlingba -lno ..\test.zo3\mlingba > ..\text.zo3\mlingba.txt
..\masmz modest -lno ..\test.zo3\modest > ..\text.zo3\modest.txt
..\masmz mojo -lno ..\test.zo3\mojo > ..\text.zo3\mojo.txt
..\masmz more -lno ..\test.zo3\more > ..\text.zo3\more.txt
..\masmz mouli -lno ..\test.zo3\mouli > ..\text.zo3\mouli.txt
..\masmz movem -lno ..\test.zo3\movem > ..\text.zo3\movem.txt
..\masmz multest -lno ..\test.zo3\multest > ..\text.zo3\multest.txt
..\masmz multitr -lno ..\test.zo3\multitr > ..\text.zo3\multitr.txt
..\masmz mungle -lno ..\test.zo3\mungle > ..\text.zo3\mungle.txt
..\masmz n -lno ..\test.zo3\n > ..\text.zo3\n.txt
..\masmz name -lno ..\test.zo3\name > ..\text.zo3\name.txt
..\masmz names -lno ..\test.zo3\names > ..\text.zo3\names.txt
..\masmz nang -lno ..\test.zo3\nang > ..\text.zo3\nang.txt
..\masmz needle -lno ..\test.zo3\needle > ..\text.zo3\needle.txt
..\masmz nest -lno ..\test.zo3\nest > ..\text.zo3\nest.txt
..\masmz netbio -lno ..\test.zo3\netbio > ..\text.zo3\netbio.txt
..\masmz netio -lno ..\test.zo3\netio > ..\text.zo3\netio.txt
..\masmz netvalue -lno ..\test.zo3\netvalue > ..\text.zo3\netvalue.txt
..\masmz new -lno ..\test.zo3\new > ..\text.zo3\new.txt
..\masmz newby -lno ..\test.zo3\newby > ..\text.zo3\newby.txt
..\masmz nipit -lno ..\test.zo3\nipit > ..\text.zo3\nipit.txt
..\masmz norkette -lno ..\test.zo3\norkette > ..\text.zo3\norkette.txt
..\masmz nosedive -lno ..\test.zo3\nosedive > ..\text.zo3\nosedive.txt
..\masmz noso -lno ..\test.zo3\noso > ..\text.zo3\noso.txt
..\masmz nostroph -lno ..\test.zo3\nostroph > ..\text.zo3\nostroph.txt
..\masmz notmany -lno ..\test.zo3\notmany > ..\text.zo3\notmany.txt
..\masmz notso -lno ..\test.zo3\notso > ..\text.zo3\notso.txt
..\masmz notvast -lno ..\test.zo3\notvast > ..\text.zo3\notvast.txt
..\masmz nuri -lno ..\test.zo3\nuri > ..\text.zo3\nuri.txt
..\masmz nvg -lno ..\test.zo3\nvg > ..\text.zo3\nvg.txt
..\masmz o -lno ..\test.zo3\o > ..\text.zo3\o.txt
..\masmz oddly -lno ..\test.zo3\oddly > ..\text.zo3\oddly.txt
..\masmz offset -lno ..\test.zo3\offset > ..\text.zo3\offset.txt
..\masmz ok1 -lno ..\test.zo3\ok1 > ..\text.zo3\ok1.txt
..\masmz one -lno ..\test.zo3\one > ..\text.zo3\one.txt
..\masmz onetwo -lno ..\test.zo3\onetwo > ..\text.zo3\onetwo.txt
..\masmz oreally -lno ..\test.zo3\oreally > ..\text.zo3\oreally.txt
..\masmz orgalign -lno ..\test.zo3\orgalign > ..\text.zo3\orgalign.txt
..\masmz otherwis -lno ..\test.zo3\otherwis > ..\text.zo3\otherwis.txt
..\masmz outline -lno ..\test.zo3\outline > ..\text.zo3\outline.txt
..\masmz outrage -lno ..\test.zo3\outrage > ..\text.zo3\outrage.txt
..\masmz outside -lno ..\test.zo3\outside > ..\text.zo3\outside.txt
..\masmz p -lno ..\test.zo3\p > ..\text.zo3\p.txt
..\masmz packem -lno ..\test.zo3\packem > ..\text.zo3\packem.txt
..\masmz paraform -lno ..\test.zo3\paraform > ..\text.zo3\paraform.txt
..\masmz param -lno ..\test.zo3\param > ..\text.zo3\param.txt
..\masmz paren -lno ..\test.zo3\paren > ..\text.zo3\paren.txt
..\masmz passes -lno ..\test.zo3\passes > ..\text.zo3\passes.txt
..\masmz passive -lno ..\test.zo3\passive > ..\text.zo3\passive.txt
..\masmz perform -lno ..\test.zo3\perform > ..\text.zo3\perform.txt
..\masmz plain -lno ..\test.zo3\plain > ..\text.zo3\plain.txt
..\masmz plank -lno ..\test.zo3\plank > ..\text.zo3\plank.txt
..\masmz plobbo -lno ..\test.zo3\plobbo > ..\text.zo3\plobbo.txt
..\masmz prango -lno ..\test.zo3\prango > ..\text.zo3\prango.txt
..\masmz prango32 -lno ..\test.zo3\prango32 > ..\text.zo3\prango32.txt
..\masmz pratisla -lno ..\test.zo3\pratisla > ..\text.zo3\pratisla.txt
..\masmz predikat -lno ..\test.zo3\predikat > ..\text.zo3\predikat.txt
..\masmz prelink -lno ..\test.zo3\prelink > ..\text.zo3\prelink.txt
..\masmz proxy -lno ..\test.zo3\proxy > ..\text.zo3\proxy.txt
..\masmz ptup -lno ..\test.zo3\ptup > ..\text.zo3\ptup.txt
..\masmz pzero -lno ..\test.zo3\pzero > ..\text.zo3\pzero.txt
..\masmz q -lno ..\test.zo3\q > ..\text.zo3\q.txt
..\masmz q1 -lno ..\test.zo3\q1 > ..\text.zo3\q1.txt
..\masmz qati -lno ..\test.zo3\qati > ..\text.zo3\qati.txt
..\masmz qb2i -lno ..\test.zo3\qb2i > ..\text.zo3\qb2i.txt
..\masmz qbig -lno ..\test.zo3\qbig > ..\text.zo3\qbig.txt
..\masmz qf -lno ..\test.zo3\qf > ..\text.zo3\qf.txt
..\masmz qflic -lno ..\test.zo3\qflic > ..\text.zo3\qflic.txt
..\masmz qpart -lno ..\test.zo3\qpart > ..\text.zo3\qpart.txt
..\masmz qplain -lno ..\test.zo3\qplain > ..\text.zo3\qplain.txt
..\masmz qt -lno ..\test.zo3\qt > ..\text.zo3\qt.txt
..\masmz quicki -lno ..\test.zo3\quicki > ..\text.zo3\quicki.txt
..\masmz quidgeo -lno ..\test.zo3\quidgeo > ..\text.zo3\quidgeo.txt
..\masmz quitebad -lno ..\test.zo3\quitebad > ..\text.zo3\quitebad.txt
..\masmz quo -lno ..\test.zo3\quo > ..\text.zo3\quo.txt
..\masmz quo1 -lno ..\test.zo3\quo1 > ..\text.zo3\quo1.txt
..\masmz quo2 -lno ..\test.zo3\quo2 > ..\text.zo3\quo2.txt
..\masmz quo3 -lno ..\test.zo3\quo3 > ..\text.zo3\quo3.txt
..\masmz quo4 -lno ..\test.zo3\quo4 > ..\text.zo3\quo4.txt
..\masmz quo5 -lno ..\test.zo3\quo5 > ..\text.zo3\quo5.txt
..\masmz qzuli -lno ..\test.zo3\qzuli > ..\text.zo3\qzuli.txt
..\masmz qzweli -lno ..\test.zo3\qzweli > ..\text.zo3\qzweli.txt
..\masmz r -lno ..\test.zo3\r > ..\text.zo3\r.txt
..\masmz r_u_rel -lno ..\test.zo3\r_u_rel > ..\text.zo3\r_u_rel.txt
..\masmz radalupu -lno ..\test.zo3\radalupu > ..\text.zo3\radalupu.txt
..\masmz random -lno ..\test.zo3\random > ..\text.zo3\random.txt
..\masmz really -lno ..\test.zo3\really > ..\text.zo3\really.txt
..\masmz reappear -lno ..\test.zo3\reappear > ..\text.zo3\reappear.txt
..\masmz reco -lno ..\test.zo3\reco > ..\text.zo3\reco.txt
..\masmz recurs -lno ..\test.zo3\recurs > ..\text.zo3\recurs.txt
..\masmz rel -lno ..\test.zo3\rel > ..\text.zo3\rel.txt
..\masmz rel2 -lno ..\test.zo3\rel2 > ..\text.zo3\rel2.txt
..\masmz relj -lno ..\test.zo3\relj > ..\text.zo3\relj.txt
..\masmz relja -lno ..\test.zo3\relja > ..\text.zo3\relja.txt
..\masmz relstack -lno ..\test.zo3\relstack > ..\text.zo3\relstack.txt
..\masmz remindme -lno ..\test.zo3\remindme > ..\text.zo3\remindme.txt
..\masmz rempack -lno ..\test.zo3\rempack > ..\text.zo3\rempack.txt
..\masmz rempart -lno ..\test.zo3\rempart > ..\text.zo3\rempart.txt
..\masmz rename -lno ..\test.zo3\rename > ..\text.zo3\rename.txt
..\masmz rep -lno ..\test.zo3\rep > ..\text.zo3\rep.txt
..\masmz res -lno ..\test.zo3\res > ..\text.zo3\res.txt
..\masmz rino -lno ..\test.zo3\rino > ..\text.zo3\rino.txt
..\masmz risobar -lno ..\test.zo3\risobar > ..\text.zo3\risobar.txt
..\masmz rough -lno ..\test.zo3\rough > ..\text.zo3\rough.txt
..\masmz roundelay -lno ..\test.zo3\roundelay > ..\text.zo3\roundelay.txt
..\masmz rounding -lno ..\test.zo3\rounding > ..\text.zo3\rounding.txt
..\masmz rplain -lno ..\test.zo3\rplain > ..\text.zo3\rplain.txt
..\masmz rumad -lno ..\test.zo3\rumad > ..\text.zo3\rumad.txt
..\masmz ryatha -lno ..\test.zo3\ryatha > ..\text.zo3\ryatha.txt
..\masmz s -lno ..\test.zo3\s > ..\text.zo3\s.txt
..\masmz sample -lno ..\test.zo3\sample > ..\text.zo3\sample.txt
..\masmz sample2 -lno ..\test.zo3\sample2 > ..\text.zo3\sample2.txt
..\masmz scabrous -lno ..\test.zo3\scabrous > ..\text.zo3\scabrous.txt
..\masmz scale -lno ..\test.zo3\scale > ..\text.zo3\scale.txt
..\masmz scale1 -lno ..\test.zo3\scale1 > ..\text.zo3\scale1.txt
..\masmz scale2 -lno ..\test.zo3\scale2 > ..\text.zo3\scale2.txt
..\masmz scale22 -lno ..\test.zo3\scale22 > ..\text.zo3\scale22.txt
..\masmz scale23 -lno ..\test.zo3\scale23 > ..\text.zo3\scale23.txt
..\masmz scale24 -lno ..\test.zo3\scale24 > ..\text.zo3\scale24.txt
..\masmz scale3 -lno ..\test.zo3\scale3 > ..\text.zo3\scale3.txt
..\masmz scale4 -lno ..\test.zo3\scale4 > ..\text.zo3\scale4.txt
..\masmz scale5 -lno ..\test.zo3\scale5 > ..\text.zo3\scale5.txt
..\masmz scale6 -lno ..\test.zo3\scale6 > ..\text.zo3\scale6.txt
..\masmz scale8 -lno ..\test.zo3\scale8 > ..\text.zo3\scale8.txt
..\masmz scally -lno ..\test.zo3\scally > ..\text.zo3\scally.txt
..\masmz scally2 -lno ..\test.zo3\scally2 > ..\text.zo3\scally2.txt
..\masmz scally3 -lno ..\test.zo3\scally3 > ..\text.zo3\scally3.txt
..\masmz scally4 -lno ..\test.zo3\scally4 > ..\text.zo3\scally4.txt
..\masmz scandal -lno ..\test.zo3\scandal > ..\text.zo3\scandal.txt
..\masmz scrabble -lno ..\test.zo3\scrabble > ..\text.zo3\scrabble.txt
..\masmz see -lno ..\test.zo3\see > ..\text.zo3\see.txt
..\masmz see2it -lno ..\test.zo3\see2it > ..\text.zo3\see2it.txt
..\masmz seomac -lno ..\test.zo3\seomac > ..\text.zo3\seomac.txt
..\masmz set -lno ..\test.zo3\set > ..\text.zo3\set.txt
..\masmz shifty -lno ..\test.zo3\shifty > ..\text.zo3\shifty.txt
..\masmz sim -lno ..\test.zo3\sim > ..\text.zo3\sim.txt
..\masmz similar -lno ..\test.zo3\similar > ..\text.zo3\similar.txt
..\masmz simple -lno ..\test.zo3\simple > ..\text.zo3\simple.txt
..\masmz simpler -lno ..\test.zo3\simpler > ..\text.zo3\simpler.txt
..\masmz simples -lno ..\test.zo3\simples > ..\text.zo3\simples.txt
..\masmz simplify -lno ..\test.zo3\simplify > ..\text.zo3\simplify.txt
..\masmz sipit -lno ..\test.zo3\sipit > ..\text.zo3\sipit.txt
..\masmz sky -lno ..\test.zo3\sky > ..\text.zo3\sky.txt
..\masmz sleunig -lno ..\test.zo3\sleunig > ..\text.zo3\sleunig.txt
..\masmz slingba -lno ..\test.zo3\slingba > ..\text.zo3\slingba.txt
..\masmz slipcan -lno ..\test.zo3\slipcan > ..\text.zo3\slipcan.txt
..\masmz slipshod -lno ..\test.zo3\slipshod > ..\text.zo3\slipshod.txt
..\masmz snappie -lno ..\test.zo3\snappie > ..\text.zo3\snappie.txt
..\masmz snippie -lno ..\test.zo3\snippie > ..\text.zo3\snippie.txt
..\masmz snozeli -lno ..\test.zo3\snozeli > ..\text.zo3\snozeli.txt
..\masmz somestuf -lno ..\test.zo3\somestuf > ..\text.zo3\somestuf.txt
..\masmz somular -lno ..\test.zo3\somular > ..\text.zo3\somular.txt
..\masmz soso -lno ..\test.zo3\soso > ..\text.zo3\soso.txt
..\masmz spitz -lno ..\test.zo3\spitz > ..\text.zo3\spitz.txt
..\masmz splativo -lno ..\test.zo3\splativo > ..\text.zo3\splativo.txt
..\masmz sprativo -lno ..\test.zo3\sprativo > ..\text.zo3\sprativo.txt
..\masmz squeeze -lno ..\test.zo3\squeeze > ..\text.zo3\squeeze.txt
..\masmz stack -lno ..\test.zo3\stack > ..\text.zo3\stack.txt
..\masmz stcomple -lno ..\test.zo3\stcomple > ..\text.zo3\stcomple.txt
..\masmz steamer -lno ..\test.zo3\steamer > ..\text.zo3\steamer.txt
..\masmz step1 -lno ..\test.zo3\step1 > ..\text.zo3\step1.txt
..\masmz step2 -lno ..\test.zo3\step2 > ..\text.zo3\step2.txt
..\masmz steps -lno ..\test.zo3\steps > ..\text.zo3\steps.txt
..\masmz strahl -lno ..\test.zo3\strahl > ..\text.zo3\strahl.txt
..\masmz strain -lno ..\test.zo3\strain > ..\text.zo3\strain.txt
..\masmz straling -lno ..\test.zo3\straling > ..\text.zo3\straling.txt
..\masmz strange -lno ..\test.zo3\strange > ..\text.zo3\strange.txt
..\masmz strangely -lno ..\test.zo3\strangely > ..\text.zo3\strangely.txt
..\masmz stretch -lno ..\test.zo3\stretch > ..\text.zo3\stretch.txt
..\masmz strial1 -lno ..\test.zo3\strial1 > ..\text.zo3\strial1.txt
..\masmz strial2 -lno ..\test.zo3\strial2 > ..\text.zo3\strial2.txt
..\masmz strial3 -lno ..\test.zo3\strial3 > ..\text.zo3\strial3.txt
..\masmz strial4 -lno ..\test.zo3\strial4 > ..\text.zo3\strial4.txt
..\masmz strial5 -lno ..\test.zo3\strial5 > ..\text.zo3\strial5.txt
..\masmz strial6 -lno ..\test.zo3\strial6 > ..\text.zo3\strial6.txt
..\masmz stringli -lno ..\test.zo3\stringli > ..\text.zo3\stringli.txt
..\masmz strophe -lno ..\test.zo3\strophe > ..\text.zo3\strophe.txt
..\masmz strugl5 -lno ..\test.zo3\strugl5 > ..\text.zo3\strugl5.txt
..\masmz stsimple -lno ..\test.zo3\stsimple > ..\text.zo3\stsimple.txt
..\masmz stt -lno ..\test.zo3\stt > ..\text.zo3\stt.txt
..\masmz subfi -lno ..\test.zo3\subfi > ..\text.zo3\subfi.txt
..\masmz submarine -lno ..\test.zo3\submarine > ..\text.zo3\submarine.txt
..\masmz subs -lno ..\test.zo3\subs > ..\text.zo3\subs.txt
..\masmz subs1 -lno ..\test.zo3\subs1 > ..\text.zo3\subs1.txt
..\masmz suficsee -lno ..\test.zo3\suficsee > ..\text.zo3\suficsee.txt
..\masmz suppose -lno ..\test.zo3\suppose > ..\text.zo3\suppose.txt
..\masmz synonyms -lno ..\test.zo3\synonyms > ..\text.zo3\synonyms.txt
..\masmz sysgo -lno ..\test.zo3\sysgo > ..\text.zo3\sysgo.txt
..\masmz table -lno ..\test.zo3\table > ..\text.zo3\table.txt
..\masmz tally2 -lno ..\test.zo3\tally2 > ..\text.zo3\tally2.txt
..\masmz tally3 -lno ..\test.zo3\tally3 > ..\text.zo3\tally3.txt
..\masmz tally4 -lno ..\test.zo3\tally4 > ..\text.zo3\tally4.txt
..\masmz tarsub -lno ..\test.zo3\tarsub > ..\text.zo3\tarsub.txt
..\masmz tcp_in -lno ..\test.zo3\tcp_in > ..\text.zo3\tcp_in.txt
..\masmz tcp_rxip -lno ..\test.zo3\tcp_rxip > ..\text.zo3\tcp_rxip.txt
..\masmz temp -lno ..\test.zo3\temp > ..\text.zo3\temp.txt
..\masmz temper -lno ..\test.zo3\temper > ..\text.zo3\temper.txt
..\masmz tempo -lno ..\test.zo3\tempo > ..\text.zo3\tempo.txt
..\masmz term -lno ..\test.zo3\term > ..\text.zo3\term.txt
..\masmz terrify1 -lno ..\test.zo3\terrify1 > ..\text.zo3\terrify1.txt
..\masmz terrify2 -lno ..\test.zo3\terrify2 > ..\text.zo3\terrify2.txt
..\masmz terrify3 -lno ..\test.zo3\terrify3 > ..\text.zo3\terrify3.txt
..\masmz these -lno ..\test.zo3\these > ..\text.zo3\these.txt
..\masmz thing -lno ..\test.zo3\thing > ..\text.zo3\thing.txt
..\masmz three4 -lno ..\test.zo3\three4 > ..\text.zo3\three4.txt
..\masmz thru -lno ..\test.zo3\thru > ..\text.zo3\thru.txt
..\masmz times -lno ..\test.zo3\times > ..\text.zo3\times.txt
..\masmz tisobar -lno ..\test.zo3\tisobar > ..\text.zo3\tisobar.txt
..\masmz tla -lno ..\test.zo3\tla > ..\text.zo3\tla.txt
..\masmz together -lno ..\test.zo3\together > ..\text.zo3\together.txt
..\masmz tomp -lno ..\test.zo3\tomp > ..\text.zo3\tomp.txt
..\masmz toozl -lno ..\test.zo3\toozl > ..\text.zo3\toozl.txt
..\masmz trail -lno ..\test.zo3\trail > ..\text.zo3\trail.txt
..\masmz trait -lno ..\test.zo3\trait > ..\text.zo3\trait.txt
..\masmz trangle -lno ..\test.zo3\trangle > ..\text.zo3\trangle.txt
..\masmz tranwys -lno ..\test.zo3\tranwys > ..\text.zo3\tranwys.txt
..\masmz trbyte -lno ..\test.zo3\trbyte > ..\text.zo3\trbyte.txt
..\masmz tribit -lno ..\test.zo3\tribit > ..\text.zo3\tribit.txt
..\masmz tricki -lno ..\test.zo3\tricki > ..\text.zo3\tricki.txt
..\masmz trinsic -lno ..\test.zo3\trinsic > ..\text.zo3\trinsic.txt
..\masmz trip -lno ..\test.zo3\trip > ..\text.zo3\trip.txt
..\masmz trivial -lno ..\test.zo3\trivial > ..\text.zo3\trivial.txt
..\masmz trivs -lno ..\test.zo3\trivs > ..\text.zo3\trivs.txt
..\masmz trtab -lno ..\test.zo3\trtab > ..\text.zo3\trtab.txt
..\masmz trtab2 -lno ..\test.zo3\trtab2 > ..\text.zo3\trtab2.txt
..\masmz tryafew -lno ..\test.zo3\tryafew > ..\text.zo3\tryafew.txt
..\masmz trysome -lno ..\test.zo3\trysome > ..\text.zo3\trysome.txt
..\masmz ttable -lno ..\test.zo3\ttable > ..\text.zo3\ttable.txt
..\masmz tump -lno ..\test.zo3\tump > ..\text.zo3\tump.txt
..\masmz tumpoon -lno ..\test.zo3\tumpoon > ..\text.zo3\tumpoon.txt
..\masmz tumpshie -lno ..\test.zo3\tumpshie > ..\text.zo3\tumpshie.txt
..\masmz tz -lno ..\test.zo3\tz > ..\text.zo3\tz.txt
..\masmz udp_rxip -lno ..\test.zo3\udp_rxip > ..\text.zo3\udp_rxip.txt
..\masmz updown -lno ..\test.zo3\updown > ..\text.zo3\updown.txt
..\masmz utable -lno ..\test.zo3\utable > ..\text.zo3\utable.txt
..\masmz uzactor -lno ..\test.zo3\uzactor > ..\text.zo3\uzactor.txt
..\masmz v -lno ..\test.zo3\v > ..\text.zo3\v.txt
..\masmz var -lno ..\test.zo3\var > ..\text.zo3\var.txt
..\masmz vast -lno ..\test.zo3\vast > ..\text.zo3\vast.txt
..\masmz vector -lno ..\test.zo3\vector > ..\text.zo3\vector.txt
..\masmz viable -lno ..\test.zo3\viable > ..\text.zo3\viable.txt
..\masmz victim -lno ..\test.zo3\victim > ..\text.zo3\victim.txt
..\masmz visobar -lno ..\test.zo3\visobar > ..\text.zo3\visobar.txt
..\masmz vitest -lno ..\test.zo3\vitest > ..\text.zo3\vitest.txt
..\masmz vitest2 -lno ..\test.zo3\vitest2 > ..\text.zo3\vitest2.txt
..\masmz vitest3 -lno ..\test.zo3\vitest3 > ..\text.zo3\vitest3.txt
..\masmz void -lno ..\test.zo3\void > ..\text.zo3\void.txt
..\masmz vr -lno ..\test.zo3\vr > ..\text.zo3\vr.txt
..\masmz vsim -lno ..\test.zo3\vsim > ..\text.zo3\vsim.txt
..\masmz vsimpl -lno ..\test.zo3\vsimpl > ..\text.zo3\vsimpl.txt
..\masmz vsimpl2 -lno ..\test.zo3\vsimpl2 > ..\text.zo3\vsimpl2.txt
..\masmz vspace -lno ..\test.zo3\vspace > ..\text.zo3\vspace.txt
..\masmz wanayooz -lno ..\test.zo3\wanayooz > ..\text.zo3\wanayooz.txt
..\masmz watabout -lno ..\test.zo3\watabout > ..\text.zo3\watabout.txt
..\masmz watslong -lno ..\test.zo3\watslong > ..\text.zo3\watslong.txt
..\masmz weel -lno ..\test.zo3\weel > ..\text.zo3\weel.txt
..\masmz whereami -lno ..\test.zo3\whereami > ..\text.zo3\whereami.txt
..\masmz whether -lno ..\test.zo3\whether > ..\text.zo3\whether.txt
..\masmz why -lno ..\test.zo3\why > ..\text.zo3\why.txt
..\masmz wibl -lno ..\test.zo3\wibl > ..\text.zo3\wibl.txt
..\masmz wirr -lno ..\test.zo3\wirr > ..\text.zo3\wirr.txt
..\masmz wolverine -lno ..\test.zo3\wolverine > ..\text.zo3\wolverine.txt
..\masmz woodbits -lno ..\test.zo3\woodbits > ..\text.zo3\woodbits.txt
..\masmz worser -lno ..\test.zo3\worser > ..\text.zo3\worser.txt
..\masmz wozita -lno ..\test.zo3\wozita > ..\text.zo3\wozita.txt
..\masmz wyzat -lno ..\test.zo3\wyzat > ..\text.zo3\wyzat.txt
..\masmz xtrem -lno ..\test.zo3\xtrem > ..\text.zo3\xtrem.txt
..\masmz yanutha -lno ..\test.zo3\yanutha > ..\text.zo3\yanutha.txt
..\masmz yasimi -lno ..\test.zo3\yasimi > ..\text.zo3\yasimi.txt
..\masmz yepnope -lno ..\test.zo3\yepnope > ..\text.zo3\yepnope.txt
..\masmz yoho -lno ..\test.zo3\yoho > ..\text.zo3\yoho.txt
..\masmz yowl -lno ..\test.zo3\yowl > ..\text.zo3\yowl.txt
..\masmz ytup -lno ..\test.zo3\ytup > ..\text.zo3\ytup.txt
..\masmz zactor -lno ..\test.zo3\zactor > ..\text.zo3\zactor.txt
..\masmz zibble -lno ..\test.zo3\zibble > ..\text.zo3\zibble.txt
..\masmz zipit -lno ..\test.zo3\zipit > ..\text.zo3\zipit.txt
..\masmz zoto -lno ..\test.zo3\zoto > ..\text.zo3\zoto.txt
..\masmz ztup -lno ..\test.zo3\ztup > ..\text.zo3\ztup.txt
